[package]
name = "messages-stress-data"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
exact-plan = { path = "../../../plan" }
exact-runner = { path = "../../../runner" }

[dev-dependencies]
contract = { path = "../../../contract/cli" }
exact-kernel = { path = "../../../kernel" }
