// The app's typed keys for its Swift module (LLP 1075.003 Q2, 1075.003.000
// Q1), written beside an Apple build by host/apple/build.mjs.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

/** The app's `data-*` and `hook` words as the Swift module's typed keys
 *  (LLP 1075.003 Q2, 1075.003.000 Q1), from app.json `data` and `hooks`:
 *  written beside the build, never committed. A hook key is made by the
 *  host's call (`ExactElement.hook`), so its initializer is the module's. */
export function writeDataKeys(app, path) {
  const camel = (w) => w.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const keys = (type, words) => words.map(w => `    public static let \`${camel(w)}\` = ${type}(${JSON.stringify(w)})\n`).join('');
  const text = `// @generated by host/apple/build.mjs from app.json \`data\` and \`hooks\` (LLP 1075.003 Q2, 1075.003.000 Q1). Do not edit.\n`
    + `/// One of the app's \`data-*\` words: \`route.data[.title]\`.\npublic struct ExactDataKey: Hashable, Sendable {\n    public let name: String\n    private init(_ name: String) { self.name = name }\n${keys('ExactDataKey', app.manifest.data ?? [])}}\n`
    + `/// One of the app's \`hook\` words: \`element.hook == .avatar\`.\npublic struct ExactHookKey: Hashable, Sendable {\n    public let name: String\n    init(_ name: String) { self.name = name }\n${keys('ExactHookKey', app.manifest.hooks ?? [])}}\n`;
  mkdirSync(dirname(path), { recursive: true });
  if (!existsSync(path) || readFileSync(path, 'utf8') !== text) writeFileSync(path, text);
}
