// The app's typed keys for its Swift module (LLP 1075.003 Q2, 1075.003.000
// Q1), written beside an Apple build by host/apple/build.mjs.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { hatchWords } from '../../scripts/app.mjs';

/** The app's `data-*` and `hatch` words as the Swift module's typed keys
 *  (LLP 1075.003 Q2, 1075.003.000 Q1), from app.json `data` and `hatches`:
 *  written beside the build, never committed. A hatch key is made by the
 *  host's call (`ExactElement.hatch`), so its initializer is the module's.
 *  Only the words `platform` handles are keys, so module code that names a
 *  word its platform does not handle fails to compile. */
export function writeDataKeys(app, path, platform) {
  const camel = (w) => w.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const keys = (type, words) => words.map(w => `    public static let \`${camel(w)}\` = ${type}(${JSON.stringify(w)})\n`).join('');
  const text = `// @generated by host/apple/build.mjs from app.json \`data\` and \`hatches\` (LLP 1075.003 Q2, 1075.003.000 Q1). Do not edit.\n`
    + `/// One of the app's \`data-*\` words: \`route.data[.title]\`.\npublic struct ExactDataKey: Hashable, Sendable {\n    public let name: String\n    private init(_ name: String) { self.name = name }\n${keys('ExactDataKey', app.manifest.data ?? [])}}\n`
    + `/// One of the app's \`hatch\` words: \`element.hatch == .avatar\`.\npublic struct ExactHatchKey: Hashable, Sendable {\n    public let name: String\n    init(_ name: String) { self.name = name }\n    /// The words this platform's module was built to handle, which the glue hands the host (LLP 1075.003.000.001 §4.3).\n    static let _words: [String] = ${JSON.stringify(hatchWords(app.manifest, platform))}\n${keys('ExactHatchKey', hatchWords(app.manifest, platform))}}\n`;
  mkdirSync(dirname(path), { recursive: true });
  if (!existsSync(path) || readFileSync(path, 'utf8') !== text) writeFileSync(path, text);
}
