use crate::{
    Component, Data, DataError, Entity, Query, QueryRows, Reader, Resource, Target, World, Writer,
};
use std::{fmt, marker::PhantomData};

/// Typed entity handle. Its Data representation is exactly Entity's; decoding
/// does not validate membership. World::row/edit check stale or incomplete IDs.
pub struct Id<K: Kind> {
    entity: Entity,
    kind: PhantomData<fn() -> K>,
}
impl<K: Kind> Id<K> {
    fn new(entity: Entity) -> Self {
        Self {
            entity,
            kind: PhantomData,
        }
    }
    /// Erase the kind for lower-level engine operations.
    pub fn entity(self) -> Entity {
        self.entity
    }
}
impl<K: Kind> Copy for Id<K> {}
impl<K: Kind> Clone for Id<K> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<K: Kind> Default for Id<K> {
    fn default() -> Self {
        Self::new(Entity::default())
    }
}
impl<K: Kind> PartialEq for Id<K> {
    fn eq(&self, other: &Self) -> bool {
        self.entity == other.entity
    }
}
impl<K: Kind> Eq for Id<K> {}
impl<K: Kind> fmt::Debug for Id<K> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple(std::any::type_name::<K>())
            .field(&self.entity)
            .finish()
    }
}
impl<K: Kind> Target for Id<K> {
    fn entity(self, world: &World) -> Option<Entity> {
        self.entity.entity(world)
    }
}
impl<K: Kind> Data for Id<K> {
    fn write(&self, w: &mut dyn Writer) {
        self.entity.write(w);
    }
    fn read(&mut self, r: &mut dyn Reader) -> Result<(), DataError> {
        self.entity.read(r)
    }
}

/// A failed typed boundary, naming the kind, entity and missing component.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KindError(String);
impl KindError {
    /// Diagnostic used by generated component checks.
    #[doc(hidden)]
    pub fn missing<K: Kind, C: Component>(entity: Entity) -> Self {
        Self(format!(
            "{} #{:?}: missing component {}",
            std::any::type_name::<K>(),
            entity,
            C::NAME
        ))
    }
}
impl fmt::Display for KindError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}
impl std::error::Error for KindError {}

/// A bundle of components with named row views, generated by derive(Kind).
/// Optional fields do not restrict membership; #[read] keeps an edit field shared.
/// Kinds have no storage or serialization of their own.
///
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Hero { pose: Transform }
/// #[derive(Kind)] struct Lamp { light: PointLight }
/// let mut world = World::new(60, 0);
/// let lamp = world.spawn_kind("lamp", Lamp { light: PointLight::default() });
/// world.row::<Hero>(lamp); // Id<Lamp> cannot address a Hero row.
/// ```
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Hero { pose: Transform, mesh: Mesh }
/// let hero = Hero { pose: Transform::default() }; // Missing required field.
/// ```
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Bad { score: u32 } // Data alone is not Component.
/// ```
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Generic<T> { value: T }
/// ```
pub trait Kind: Sized + 'static {
    /// Shared row view.
    type Ref<'w>;
    /// Editing row view.
    type Mut<'w>;
    /// Existing shared storage query.
    #[doc(hidden)]
    type Read: Query;
    /// Existing editing storage query.
    #[doc(hidden)]
    type Write: Query;
    /// Insert fields into the ordinary component columns.
    #[doc(hidden)]
    fn insert(self, world: &mut World, entity: Entity);
    /// Check required component membership without acquiring mutable leases.
    #[doc(hidden)]
    fn check(world: &World, entity: Entity) -> Result<(), KindError>;
    /// Wrap a shared query row.
    #[doc(hidden)]
    fn view<'w>(id: Id<Self>, values: <Self::Read as Query>::Owned<'w>) -> Self::Ref<'w>;
    /// Wrap an editing query row.
    #[doc(hidden)]
    fn view_mut<'w>(id: Id<Self>, values: <Self::Write as Query>::Owned<'w>) -> Self::Mut<'w>;
    /// Acquire shared leases for one entity.
    #[doc(hidden)]
    fn row(world: &World, id: Id<Self>) -> Result<Self::Ref<'_>, KindError>;
    /// Acquire editing leases for one entity.
    #[doc(hidden)]
    fn row_mut(world: &World, id: Id<Self>) -> Result<Self::Mut<'_>, KindError>;
}

/// Shared typed rows, in entity order, with one lease per column for the loop.
pub struct KindRows<'w, K: Kind>(QueryRows<'w, K::Read>);
impl<'w, K: Kind> KindRows<'w, K> {
    /// The sole row, or None; multiple matches panic with the kind's name.
    pub fn one(mut self) -> Option<K::Ref<'w>> {
        let row = self.next();
        assert!(
            self.next().is_none(),
            "expected one {}",
            std::any::type_name::<K>()
        );
        row
    }
}
impl<'w, K: Kind> Iterator for KindRows<'w, K> {
    type Item = K::Ref<'w>;
    fn next(&mut self) -> Option<Self::Item> {
        self.0
            .next_entity()
            .map(|(e, row)| K::view(Id::new(e), row))
    }
}
/// Editing typed rows. Escaping rows keep their disjoint storage leases alive.
pub struct KindRowsMut<'w, K: Kind>(QueryRows<'w, K::Write>);
impl<'w, K: Kind> KindRowsMut<'w, K> {
    /// The sole row, or None; multiple matches panic with the kind's name.
    pub fn one(mut self) -> Option<K::Mut<'w>> {
        let row = self.next();
        assert!(
            self.next().is_none(),
            "expected one {}",
            std::any::type_name::<K>()
        );
        row
    }
}
impl<'w, K: Kind> Iterator for KindRowsMut<'w, K> {
    type Item = K::Mut<'w>;
    fn next(&mut self) -> Option<Self::Item> {
        self.0
            .next_entity()
            .map(|(e, row)| K::view_mut(Id::new(e), row))
    }
}

impl World {
    /// Spawn the kind's components without adding a kind column or tag.
    pub fn spawn_kind<K: Kind>(&mut self, name: impl AsRef<str>, value: K) -> Id<K> {
        let entity = self.spawn_named(name, ());
        value.insert(self, entity);
        Id::new(entity)
    }
    /// Check an existing entity (including a scene entity) and give it a typed ID.
    pub fn bind<K: Kind>(&self, target: impl Target) -> Result<Id<K>, KindError> {
        let e = target.entity(self).ok_or_else(|| {
            KindError(format!(
                "{}: entity is absent or stale",
                std::any::type_name::<K>()
            ))
        })?;
        K::check(self, e)?;
        Ok(Id::new(e))
    }
    /// Resolve a named direct child once. Store the resulting ID in a component
    /// or resource; use data(skip) for a derived binding rebuilt after restore.
    pub fn child<K: Kind>(&self, parent: impl Target, name: &str) -> Result<Id<K>, KindError> {
        let parent = parent
            .entity(self)
            .ok_or_else(|| KindError("child's parent is absent".into()))?;
        let prefix = self
            .name(parent)
            .ok_or_else(|| KindError("child's parent is unnamed".into()))?;
        let path = format!("{prefix}/{name}");
        let child = self
            .bind::<K>(path.as_str())
            .map_err(|e| KindError(format!("{path}: {e}")))?;
        if self
            .get::<crate::Parent>(child)
            .is_none_or(|p| p.0 != parent)
        {
            return Err(KindError(format!(
                "{path}: expected direct child of {prefix}"
            )));
        }
        Ok(child)
    }
    /// Shared row access. Missing or stale components produce a named error.
    pub fn row<K: Kind>(&self, id: Id<K>) -> Result<K::Ref<'_>, KindError> {
        self.bind::<K>(id)?;
        K::row(self, id)
    }
    /// Read an established game invariant and release its shared leases at return.
    /// A stale or incomplete ID panics with the kind and missing component.
    pub fn with_row<K: Kind, R>(&self, id: Id<K>, f: impl FnOnce(&K::Ref<'_>) -> R) -> R {
        f(&self.row(id).unwrap_or_else(|e| panic!("{e}")))
    }
    /// Edit an established game invariant, releasing all leases at return.
    /// Validate before any mutable lease so a missing field does not dirty pages.
    pub fn edit<K: Kind, R>(&self, id: Id<K>, f: impl FnOnce(&mut K::Mut<'_>) -> R) -> R {
        self.bind::<K>(id).unwrap_or_else(|e| panic!("{e}"));
        f(&mut K::row_mut(self, id).unwrap_or_else(|e| panic!("{e}")))
    }
    /// Edit a resource, releasing its lease before returning the closure's result.
    pub fn edit_resource<T: Resource, R>(&self, f: impl FnOnce(&mut T) -> R) -> R {
        f(&mut self.resource_mut::<T>())
    }
    /// Shared entity-ordered rows; reads do not dirty pages or observation epochs.
    pub fn rows<K: Kind>(&self) -> KindRows<'_, K> {
        KindRows(self.query::<K::Read>().into_iter())
    }
    /// Entity-ordered rows with one editing lease per distinct component column.
    pub fn rows_mut<K: Kind>(&self) -> KindRowsMut<'_, K> {
        KindRowsMut(self.query::<K::Write>().into_iter())
    }
    /// Exactly one matching entity. Zero or multiple matches panic, naming K.
    pub fn the<K: Kind>(&self) -> Id<K> {
        let mut found = None;
        let mut count = 0;
        for e in self.entities().filter(|&e| K::check(self, e).is_ok()) {
            found = Some(Id::new(e));
            count += 1;
        }
        assert!(
            count == 1,
            "expected exactly one {}, found {count}",
            std::any::type_name::<K>()
        );
        found.unwrap()
    }
}
