use crate::{
    Component, Data, DataError, Entity, Query, QueryRows, Reader, Resource, Target, World, Writer,
};
use std::{fmt, marker::PhantomData};

/// Typed entity handle. Its Data representation is exactly Entity's; decoding
/// does not validate membership. World::row/edit check stale or incomplete IDs.
pub struct Id<K: Kind> {
    entity: Entity,
    kind: PhantomData<fn() -> K>,
}
impl<K: Kind> Id<K> {
    fn new(entity: Entity) -> Self {
        Self {
            entity,
            kind: PhantomData,
        }
    }
    /// Erase the kind for lower-level engine operations.
    pub fn entity(self) -> Entity {
        self.entity
    }
}
impl<K: Kind> Copy for Id<K> {}
impl<K: Kind> Clone for Id<K> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<K: Kind> Default for Id<K> {
    fn default() -> Self {
        Self::new(Entity::default())
    }
}
impl<K: Kind> PartialEq for Id<K> {
    fn eq(&self, other: &Self) -> bool {
        self.entity == other.entity
    }
}
impl<K: Kind> Eq for Id<K> {}
impl<K: Kind> fmt::Debug for Id<K> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple(std::any::type_name::<K>())
            .field(&self.entity)
            .finish()
    }
}
impl<K: Kind> Target for Id<K> {
    fn entity(self, world: &World) -> Option<Entity> {
        self.entity.entity(world)
    }
    fn describe(&self, world: &World) -> String {
        self.entity.describe(world)
    }
}
impl<K: Kind> Data for Id<K> {
    fn write(&self, w: &mut dyn Writer) {
        self.entity.write(w);
    }
    fn read(&mut self, r: &mut dyn Reader) -> Result<(), DataError> {
        self.entity.read(r)
    }
}

/// A failed typed boundary, naming the kind, entity and missing component.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KindError(String);
impl KindError {
    /// Missing a required gameplay name.
    pub fn unnamed<K: Kind>(world: &World, entity: Entity) -> Self {
        Self(format!(
            "name {} {}: entity is unnamed",
            std::any::type_name::<K>(),
            entity.describe(world)
        ))
    }
    /// Diagnostic used by generated component checks.
    #[doc(hidden)]
    pub fn missing<K: Kind, C: Component>(world: &World, entity: Entity, operation: &str) -> Self {
        Self(format!(
            "{operation} {} {}: missing component {}",
            std::any::type_name::<K>(),
            entity.describe(world),
            C::NAME
        ))
    }
    /// Refuse declared child IDs that Data omits.
    #[doc(hidden)]
    pub fn saved_field<K: Kind, C: Component>(field: &str) -> Result<(), Self> {
        if C::SAVED_FIELDS.contains(&field) {
            Ok(())
        } else {
            Err(Self(format!("{} component {} field {field}: child binding must be saved; data(skip) is forbidden", std::any::type_name::<K>(), C::NAME)))
        }
    }
    /// Reject aliases of the same component before spawning or leasing.
    #[doc(hidden)]
    pub fn unique<K: Kind>(fields: &[(std::any::TypeId, &str, &str)]) -> Result<(), Self> {
        for (i, (id, field, ty)) in fields.iter().enumerate() {
            if let Some((_, previous, _)) = fields[..i].iter().find(|(other, _, _)| other == id) {
                return Err(Self(format!("{}: duplicate component {ty} in fields {previous} and {field} (including aliases); preflight before spawn or lease", std::any::type_name::<K>())));
            }
        }
        Ok(())
    }
}
impl fmt::Display for KindError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}
impl std::error::Error for KindError {}

/// A bundle of components with named row views, generated by derive(Kind).
/// Optional fields do not restrict membership; #[read] keeps an edit field shared.
/// Kinds have no storage or serialization of their own.
///
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Hero { pose: Transform }
/// #[derive(Kind)] struct Lamp { light: PointLight }
/// let mut world = World::new(60, 0);
/// let lamp = world.spawn_kind("lamp", Lamp { light: PointLight::default() });
/// world.row::<Hero>(lamp); // Id<Lamp> cannot address a Hero row.
/// ```
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Hero { pose: Transform, mesh: Mesh }
/// let hero = Hero { pose: Transform::default() }; // Missing required field.
/// ```
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Bad { score: u32 } // Data alone is not Component.
/// ```
/// ```compile_fail
/// use exact_game::*;
/// #[derive(Kind)] struct Generic<T> { value: T }
/// ```
pub trait Kind: Sized + 'static {
    /// Component spellings for stale-identity diagnostics.
    #[doc(hidden)]
    const COMPONENTS: &'static str;
    /// Resolve owned spawn values before any world mutation.
    #[doc(hidden)]
    fn prepare_spawn(&mut self, world: &World, name: &str) -> Result<(), KindError>;
    /// Attach prevalidated child entities to the new parent.
    #[doc(hidden)]
    fn attach(world: &mut World, entity: Entity);
    /// Whether this kind declares saved child bindings.
    #[doc(hidden)]
    const HAS_BINDINGS: bool;
    /// Shared row view.
    type Ref<'w>;
    /// Editing row view.
    type Mut<'w>;
    /// Existing shared storage query.
    #[doc(hidden)]
    type Read: Query;
    /// Existing editing storage query.
    #[doc(hidden)]
    type Write: Query;
    /// Reject duplicate types, including aliases, before any mutation or lease.
    #[doc(hidden)]
    fn preflight() -> Result<(), KindError>;
    /// Preflight all column leases without acquiring any.
    #[doc(hidden)]
    fn leases(
        world: &World,
        entity: Option<Entity>,
        operation: &str,
        mutable: bool,
    ) -> Result<(), KindError>;
    /// Initialize declared saved bindings at setup, or validate them on use.
    #[doc(hidden)]
    fn bindings(
        world: &World,
        entity: Entity,
        initialize: bool,
        operation: &str,
    ) -> Result<(), KindError>;
    /// Insert fields into the ordinary component columns.
    #[doc(hidden)]
    fn insert(self, world: &mut World, entity: Entity);
    /// Check required component membership without acquiring mutable leases.
    #[doc(hidden)]
    fn check(world: &World, entity: Entity, operation: &str) -> Result<(), KindError>;
    /// Wrap a shared query row.
    #[doc(hidden)]
    fn view<'w>(id: Id<Self>, values: <Self::Read as Query>::Owned<'w>) -> Self::Ref<'w>;
    /// Wrap an editing query row.
    #[doc(hidden)]
    fn view_mut<'w>(id: Id<Self>, values: <Self::Write as Query>::Owned<'w>) -> Self::Mut<'w>;
    /// Acquire shared leases for one entity.
    #[doc(hidden)]
    fn row<'w>(world: &'w World, id: Id<Self>, operation: &str)
        -> Result<Self::Ref<'w>, KindError>;
    /// Acquire editing leases for one entity.
    #[doc(hidden)]
    fn row_mut<'w>(
        world: &'w World,
        id: Id<Self>,
        operation: &str,
    ) -> Result<Self::Mut<'w>, KindError>;
}

/// Shared typed rows, in entity order, with one lease per column for the loop.
pub struct KindRows<'w, K: Kind>(QueryRows<'w, K::Read>);
impl<'w, K: Kind> KindRows<'w, K> {
    /// The sole row, or None; multiple matches panic with the kind's name.
    pub fn one(mut self) -> Option<K::Ref<'w>> {
        let row = self.next();
        assert!(
            self.next().is_none(),
            "expected one {}",
            std::any::type_name::<K>()
        );
        row
    }
}
impl<'w, K: Kind> Iterator for KindRows<'w, K> {
    type Item = K::Ref<'w>;
    fn next(&mut self) -> Option<Self::Item> {
        self.0
            .next_entity()
            .map(|(e, row)| K::view(Id::new(e), row))
    }
}
/// Editing typed rows. Escaping rows keep their disjoint storage leases alive.
pub struct KindRowsMut<'w, K: Kind>(QueryRows<'w, K::Write>);
impl<'w, K: Kind> KindRowsMut<'w, K> {
    /// The sole row, or None; multiple matches panic with the kind's name.
    pub fn one(mut self) -> Option<K::Mut<'w>> {
        let row = self.next();
        assert!(
            self.next().is_none(),
            "expected one {}",
            std::any::type_name::<K>()
        );
        row
    }
}
impl<'w, K: Kind> Iterator for KindRowsMut<'w, K> {
    type Item = K::Mut<'w>;
    fn next(&mut self) -> Option<Self::Item> {
        self.0
            .next_entity()
            .map(|(e, row)| K::view_mut(Id::new(e), row))
    }
}

// Active closure operations are diagnostic context only, never simulation state.
struct Operation<'w>(&'w World);
impl Drop for Operation<'_> {
    fn drop(&mut self) {
        self.0.kind_operations.borrow_mut().pop();
    }
}

impl World {
    fn kind_operation<K: Kind>(&self, entity: Option<Entity>, operation: &str) -> Operation<'_> {
        self.kind_operations.borrow_mut().push(format!(
            "{operation} {} {}",
            std::any::type_name::<K>(),
            entity.map_or_else(|| "entity-ordered rows".into(), |e| e.describe(self))
        ));
        Operation(self)
    }
    /// Preflight a generated field's column without taking a lease.
    #[doc(hidden)]
    pub fn kind_lease<K: Kind, C: Component>(
        &self,
        entity: Option<Entity>,
        operation: &str,
        mutable: bool,
    ) -> Result<(), KindError> {
        if let Some(conflict) = self.storage::<C>().and_then(|s| s.lease_conflict(mutable)) {
            return Err(KindError(format!("{operation} {} {}: component {} is already borrowed {conflict}; inside [{}]; drop the row before another overlapping operation", std::any::type_name::<K>(), entity.map_or_else(|| "entity-ordered rows".into(), |e| e.describe(self)), C::NAME, self.kind_operations.borrow().join(" -> "))));
        }
        Ok(())
    }
    fn checked<K: Kind>(&self, target: impl Target, operation: &str) -> Result<Id<K>, KindError> {
        K::preflight()?;
        let label = target.describe(self);
        let e = target.entity(self).ok_or_else(|| {
            KindError(format!(
                "{operation} {} {label}: entity is absent or stale (generation check); components {}",
                std::any::type_name::<K>(), K::COMPONENTS
            ))
        })?;
        K::check(self, e, operation)?;
        Ok(Id::new(e))
    }
    /// Spawn ordinary component columns, then initialize declared saved bindings.
    /// Duplicate types are rejected before creation; an invalid binding rolls back the entity.
    pub fn spawn_kind<K: Kind>(&mut self, name: impl AsRef<str>, mut value: K) -> Id<K> {
        K::preflight().expect("spawn_kind preflight");
        value
            .prepare_spawn(self, name.as_ref())
            .expect("spawn_kind binding preflight");
        let entity = self.spawn_named(name, ());
        value.insert(self, entity);
        K::attach(self, entity);
        match self.bind::<K>(entity) {
            Ok(id) => id,
            Err(error) => {
                self.despawn(entity);
                panic!("spawn_kind: {error}");
            }
        }
    }
    /// Setup boundary: fill default declared child IDs once; validate existing saved IDs.
    pub fn bind<K: Kind>(&self, target: impl Target) -> Result<Id<K>, KindError> {
        let id = self.checked::<K>(target, "bind")?;
        K::leases(self, Some(id.entity), "bind", false)?;
        K::bindings(self, id.entity, true, "bind")?;
        Ok(id)
    }
    /// Resolve a direct named child at setup. Persist the returned ID as state.
    pub fn child<K: Kind>(&self, parent: impl Target, name: &str) -> Result<Id<K>, KindError> {
        let label = parent.describe(self);
        let parent = parent.entity(self).ok_or_else(|| {
            KindError(format!(
                "child {} {label}: parent is absent or stale",
                std::any::type_name::<K>()
            ))
        })?;
        let prefix = self.name(parent).ok_or_else(|| {
            KindError(format!(
                "child {}: parent {label} is unnamed",
                std::any::type_name::<K>()
            ))
        })?;
        let child = self.checked::<K>(format!("{prefix}/{name}").as_str(), "child")?;
        if self
            .get::<crate::Parent>(child)
            .is_none_or(|p| p.0 != parent)
        {
            return Err(KindError(format!(
                "child {} {}: component Parent must reference {label}",
                std::any::type_name::<K>(),
                child.describe(self)
            )));
        }
        Ok(child)
    }
    /// Resolve an unparented, already spawned child before creating its parent.
    #[doc(hidden)]
    pub fn kind_spawn_child<K: Kind, C: Kind>(
        &self,
        name: &str,
        child: &str,
        saved: Id<C>,
    ) -> Result<Id<C>, KindError> {
        let id = self.checked::<C>(format!("{name}/{child}").as_str(), "spawn_kind child")?;
        if (saved != Id::default() && saved != id) || self.has::<crate::Parent>(id.entity()) {
            return Err(KindError(format!("spawn_kind {} entity {name:?} child {child}: expected unparented {} matching saved ID {saved:?}", std::any::type_name::<K>(), id.describe(self))));
        }
        Ok(id)
    }
    /// Generated child field resolution. Existing IDs are never retargeted by name.
    #[doc(hidden)]
    pub fn kind_child<K: Kind, C: Kind>(
        &self,
        entity: Entity,
        name: &str,
        field: &str,
        saved: Id<C>,
        initialize: bool,
        operation: &str,
    ) -> Result<Id<C>, KindError> {
        let result = if initialize && saved == Id::default() {
            self.child::<C>(entity, name)
        } else {
            self.checked::<C>(saved, operation).and_then(|id| {
                if self.get::<crate::Parent>(id).is_none_or(|p| p.0 != entity) {
                    Err(KindError(format!(
                        "component Parent for {} must reference {}",
                        id.describe(self),
                        entity.describe(self)
                    )))
                } else {
                    Ok(id)
                }
            })
        };
        result.map_err(|e| {
            KindError(format!(
                "{operation} {} {} field {field} (child {name}): {e}",
                std::any::type_name::<K>(),
                entity.describe(self)
            ))
        })
    }
    /// Shared row access; validates saved bindings without rebuilding or dirtying state.
    pub fn row<K: Kind>(&self, id: Id<K>) -> Result<K::Ref<'_>, KindError> {
        self.checked::<K>(id, "row")?;
        K::leases(self, Some(id.entity), "row", false)?;
        K::bindings(self, id.entity, false, "row")?;
        K::row(self, id, "row")
    }
    /// Edit an established game invariant. Failures name the operation, kind,
    /// entity and column; all validation precedes mutable leases.
    pub fn edit<K: Kind, R>(&self, id: Id<K>, f: impl FnOnce(&mut K::Mut<'_>) -> R) -> R {
        self.checked::<K>(id, "edit").expect("edit validation");
        K::leases(self, Some(id.entity), "edit", true).expect("edit lease preflight");
        K::bindings(self, id.entity, false, "edit").expect("edit binding validation");
        let _operation = self.kind_operation::<K>(Some(id.entity), "edit");
        f(&mut K::row_mut(self, id, "edit").expect("edit row"))
    }
    /// Edit a resource, releasing its lease before returning the closure's result.
    pub fn edit_resource<T: Resource, R>(&self, f: impl FnOnce(&mut T) -> R) -> R {
        f(&mut self.resource_mut::<T>())
    }
    fn prepare_kind<K: Kind>(&self, operation: &str, mutable: bool) {
        K::preflight().expect("kind preflight");
        self.kind_work_bound(operation);
        K::leases(self, None, operation, mutable).expect("kind lease preflight");
        if !K::HAS_BINDINGS {
            return;
        }
        for entity in self.entities() {
            if K::check(self, entity, operation).is_ok() {
                K::bindings(self, entity, false, operation).expect("kind binding validation");
            }
        }
    }
    /// Shared entity-ordered rows. Saved child bindings are validated before leases.
    pub fn rows<K: Kind>(&self) -> KindRows<'_, K> {
        self.prepare_kind::<K>("rows", false);
        KindRows(self.query::<K::Read>().into_iter())
    }
    /// Editing rows with one lease per column; preflight precedes every mutable lease.
    pub fn rows_mut<K: Kind>(&self) -> KindRowsMut<'_, K> {
        self.prepare_kind::<K>("rows_mut", true);
        KindRowsMut(self.query::<K::Write>().into_iter())
    }
    /// Exactly one structural match. No implicit binding initialization.
    pub fn the<K: Kind>(&self) -> Id<K> {
        K::preflight().expect("the preflight");
        self.kind_work_bound("the");
        let mut found = None;
        let mut count = 0;
        for e in self
            .entities()
            .filter(|&e| K::check(self, e, "the").is_ok())
        {
            found = Some(Id::new(e));
            count += 1;
        }
        assert!(
            count == 1,
            "expected exactly one {}, found {count}",
            std::any::type_name::<K>()
        );
        found.unwrap()
    }
}
