#!/usr/bin/env node
// Build Snapback4's web device and client (exact-snapback4-web): the wasm
// an app serves (`node snapback4/web/build.mjs <app>/assets/snapback4.wasm`)
// and its wasm-bindgen glue, which `ts/web.ts` imports (`ts/generated/`,
// never committed). With no output it writes only the glue, which every
// host's bake type-checks. Runs under Node or Bun, and from an app's build.rs. Size first (profile `wasm`), then `wasm-opt -Oz` when
// binaryen is on PATH or in Exact's cache and it transfers smaller. Files are rewritten only when their bytes change.
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { delimiter, dirname, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';

const out = process.argv[2];
const workspace = resolve(import.meta.dirname, '..');
// One absolute directory for Cargo (run in the workspace) and the paths below.
const target = resolve(process.env.SNAPBACK4_TARGET_DIR ?? resolve(workspace, 'target'));
// From an app's build.rs, the outer build's target, flags, toolchain and C
// compiler settings are in the environment; this build is its own (the
// checkout's toolchain, wasm32, no host C toolchain).
const env = Object.fromEntries(Object.entries(process.env).filter(([key]) =>
  !/^(CARGO_(?!HOME$)|RUST(FLAGS|DOCFLAGS|C|C_WRAPPER|C_WORKSPACE_WRAPPER|UP_TOOLCHAIN)$|TARGET$|HOST$|OUT_DIR$|PROFILE$|OPT_LEVEL$|DEBUG$|NUM_JOBS$|SDKROOT$|DEVELOPER_DIR$|\w+_DEPLOYMENT_TARGET$|(TARGET_|HOST_)?(CC|CXX|AR|RANLIB|CFLAGS|CXXFLAGS|CPPFLAGS|LDFLAGS|ARFLAGS)(_[\w-]+)?$)/.test(key)));
env.CARGO_TARGET_DIR = target;
// A build script's stdout is cargo's instruction channel: report on stderr.
const cargo = spawnSync('cargo', ['build', '-p', 'exact-snapback4-web', '--profile', 'wasm', '--target', 'wasm32-unknown-unknown', '--locked'],
  { cwd: workspace, stdio: ['ignore', 2, 'inherit'], env });
if (cargo.status !== 0) process.exit(cargo.status ?? 1);
const compiled = resolve(target, 'wasm32-unknown-unknown/wasm/exact_snapback4_web.wasm');
const glue = resolve(target, 'snapback4-web-bindgen');
const bindgen = spawnSync('wasm-bindgen', ['--target', 'web', '--out-dir', glue, '--out-name', 'device', compiled], { stdio: ['ignore', 2, 'inherit'], env });
if (bindgen.status !== 0) {
  console.error(`snapback4 web: ${bindgen.error?.code === 'ENOENT' ? 'wasm-bindgen not on PATH (cargo install wasm-bindgen-cli --version 0.2.127)' : 'wasm-bindgen failed'}`);
  process.exit(1);
}
const built = resolve(glue, 'device_bg.wasm');
const optimized = resolve(glue, 'device_bg.opt.wasm');
// The binaryen `exact setup` installs (scripts/app.mjs puts it on PATH for
// Exact's own builds; this script also runs on its own and from build.rs).
const cached = resolve(homedir(), '.cache/exact/binaryen');
const optEnv = { ...process.env };
if (existsSync(cached)) {
  const bins = readdirSync(cached).sort().reverse().map(version => resolve(cached, version, 'bin'))
    .filter(bin => existsSync(resolve(bin, process.platform === 'win32' ? 'wasm-opt.exe' : 'wasm-opt')));
  if (bins.length) optEnv.PATH = `${bins[0]}${delimiter}${optEnv.PATH ?? ''}`;
}
const opt = spawnSync('wasm-opt', ['-Oz', '--enable-bulk-memory', '--enable-nontrapping-float-to-int', '--enable-sign-ext', '--enable-mutable-globals', built, '-o', optimized],
  { stdio: ['ignore', 'ignore', 'pipe'], encoding: 'utf8', env: optEnv });
if (opt.status !== 0) {
  console.error(`snapback4 web: ${opt.error?.code === 'ENOENT' ? 'wasm-opt not found (`bun scripts/exact.mjs setup` installs it)' : `wasm-opt failed: ${opt.stderr.trim().split('\n').at(-1)}`}; unoptimized`);
}
// Keep whichever transfers smaller: -Oz shrinks this module raw but can grow
// it gzipped (as Snapback's own build-wasm.sh finds and compares).
const gzipped = path => gzipSync(readFileSync(path), { level: 9 }).length;
const bytes = readFileSync(opt.status === 0 && gzipped(optimized) < gzipped(built) ? optimized : built);
function write(path, bytes) {
  if (existsSync(path) && readFileSync(path).equals(bytes)) return;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path + '.tmp', bytes);
  renameSync(path + '.tmp', path);
}
if (out) write(resolve(process.cwd(), out), bytes);
// The glue as TypeScript the bake captures; it is generated, so unchecked.
const source = readFileSync(resolve(glue, 'device.js'), 'utf8');
write(resolve(workspace, 'ts/generated/device.ts'), Buffer.from(`// @ts-nocheck\n// @generated by snapback4/web/build.mjs (wasm-bindgen 0.2.127). Do not edit.\n${source}`));
console.error(`snapback4 web: ${bytes.length} B, ${gzipSync(bytes, { level: 9 }).length} B gzip${out ? ` → ${out}` : ' (glue only)'}`);
