[package]
name = "beacons-apple"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
exact-runner = { path = "../../../../runner" }
exact-apple = { path = "../../../../host/apple" }

[build-dependencies]
exact-game-app = { path = "../../../app" }
