[package]
name = "beacons-apple"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "../../../app/apple.rs"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
exact-runner.workspace = true
exact-apple.workspace = true

[build-dependencies]
exact-game-app.workspace = true
