[package]
name = "exact-crypto-gpu-data"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
exact-plan = { path = "../../../../plan" }
exact-runner = { path = "../../../../runner" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
