[package]
name = "tally-web"
version.workspace = true
edition.workspace = true
license.workspace = true
[lib]
name = "tally_web"
crate-type = ["cdylib", "rlib"]
[dependencies]
tally-data = { path = "../data" }
exact-web = { path = "../../../../host/web" }
[build-dependencies]
tally-data = { path = "../data" }
contract = { path = "../../../../contract/cli" }
