//! The art pass, an optional look (`art: "pass"`, or `"night"` for the night
//! arena) over the same fight: a dressed arena, soldiers, first-person weapons
//! with hands, particles and lights, all generated by `art-src/gen.mjs`.
//!
//! The fight is the classic one. The pass draws over the classic colliders,
//! never adds one, never draws from the world RNG, and allocates no entity
//! mid-fight (lingering effects live on pooled entities spawned in setup), so
//! the fight's own entities keep their order. What it saves is only when
//! something happened (a hit, a shot, a blast); how that looks is derived in
//! `present` (`art_present.rs`), outside saves and hashes.
use crate::{
    fighter::{self, Fighter},
    presentation::Feedback,
    weapons::{Effect, Rocket, Weapon},
};
use exact_game::{
    emitter::{Shape, WorldSpace},
    *,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Look {
    Dusk,
    Night,
}
impl Look {
    /// The look an `art` argument names; `""` is the classic greybox (None).
    pub fn of(art: &str) -> Option<Look> {
        match art {
            "pass" => Some(Look::Dusk),
            "night" => Some(Look::Night),
            _ => None,
        }
    }
    pub fn validate(art: &str) -> Result<(), String> {
        match art {
            "" | "pass" | "night" => Ok(()),
            other => Err(format!(
                "art: expected \"\" (classic), \"pass\" or \"night\", got {other:?}"
            )),
        }
    }
}

/// Fetched from the start but never awaited: the rocket is first needed
/// mid-fight (a streamed asset stays resident, so it never holds up a save);
/// textures that no model names (the skies, the smoke puff) load this way.
/// The other models load on sight when the pass's setup references them.
pub const STREAMED: &[&str] = &["rocket.model", "sky.tex", "sky_night.tex", "smoke.tex"];

/// Bot armour colours, by slot.
pub const TEAMS: [[f32; 3]; 8] = [
    [0.86, 0.22, 0.24],
    [0.94, 0.62, 0.12],
    [0.55, 0.30, 0.85],
    [0.15, 0.70, 0.45],
    [0.90, 0.35, 0.65],
    [0.20, 0.55, 0.90],
    [0.65, 0.65, 0.20],
    [0.40, 0.80, 0.85],
];
/// Weapons are modelled at life size and drawn smaller and nearer, as an FPS does.
pub const VIEW_SCALE: f32 = 0.72;
const SPARKS: u32 = 6;
const BLASTS: u32 = 3;
const TRAILS: u32 = 4;

/// A bot's soldier model, a child of its capsule. The tick records when it was
/// last hit and last fired; `present` draws the flinch and flashes from that.
#[derive(Clone, Debug, Default, Component)]
pub struct Soldier {
    pub slot: u32,
    pub hp: f32,
    pub shots: u32,
    pub hit_tick: Option<u64>,
    pub shot_tick: Option<u64>,
}
/// A bot's muzzle flash, a child of its soldier's gun.
#[derive(Clone, Debug, Default, Component)]
pub struct BotFlash {
    pub slot: u32,
}
/// One rigid part of a soldier, at its joint.
#[derive(Clone, Debug, Default, Component)]
pub struct Limb {
    pub slot: u32,
    pub joint: Joint,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Data)]
pub enum Joint {
    #[default]
    Hips,
    Spine,
    Head,
    ArmL,
    ForeL,
    ArmR,
    ForeR,
    Gun,
    LegL,
    ShinL,
    LegR,
    ShinR,
}
impl Joint {
    /// Each part, its parent part (None: the soldier), where its joint sits
    /// on the parent, and its model (`soldier_<model>.model`). Parents first.
    pub const SKELETON: [(Joint, Option<Joint>, [f32; 3], &'static str); 12] = [
        (Joint::Hips, None, [0.0, 0.0, 0.0], "hips"),
        (Joint::Spine, Some(Joint::Hips), [0.0, 0.06, 0.0], "torso"),
        (Joint::Head, Some(Joint::Spine), [0.0, 0.66, 0.0], "head"),
        (Joint::ArmL, Some(Joint::Spine), [-0.26, 0.43, 0.0], "arm"),
        (Joint::ForeL, Some(Joint::ArmL), [0.0, -0.29, 0.0], "fore"),
        (Joint::ArmR, Some(Joint::Spine), [0.26, 0.43, 0.0], "arm"),
        (Joint::ForeR, Some(Joint::ArmR), [0.0, -0.29, 0.0], "fore"),
        (Joint::Gun, Some(Joint::Spine), [0.12, 0.3, -0.28], "gun"),
        (Joint::LegL, Some(Joint::Hips), [-0.1, -0.04, 0.0], "thigh"),
        (Joint::ShinL, Some(Joint::LegL), [0.0, -0.42, 0.0], "shin"),
        (Joint::LegR, Some(Joint::Hips), [0.1, -0.04, 0.0], "thigh"),
        (Joint::ShinR, Some(Joint::LegR), [0.0, -0.42, 0.0], "shin"),
    ];
}
/// One part of an art-pass first-person weapon, posed by `present`.
#[derive(Clone, Debug, Default, Component)]
pub struct Held {
    pub weapon: Weapon,
    pub part: Part,
}
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Data)]
pub enum Part {
    #[default]
    Body,
    Magazine,
    Flash,
}
/// The pools' next slots, each blast light's start, and the last inspect (T).
#[derive(Clone, Debug, Default, Resource)]
pub struct Fx {
    pub sparks: u32,
    pub blood: u32,
    pub blasts: u32,
    pub blast_at: Vec<Option<u64>>,
    pub inspect_tick: Option<u64>,
}
/// On a rocket: the pooled trail emitter following it.
#[derive(Clone, Copy, Debug, Default, Component)]
pub struct Trail(pub u32);
/// On a rocket or a classic effect the pass has already dressed.
#[derive(Clone, Copy, Debug, Default, Component)]
pub struct Dressed;

pub fn register(w: &mut World) {
    w.register::<Soldier>()
        .register::<BotFlash>()
        .register::<Limb>()
        .register::<Held>()
        .register::<Trail>()
        .register::<Dressed>()
        .register::<Emitter>()
        .register::<WorldSpace>()
        .register::<ParticleLook>();
    w.register_resource::<Fx>()
        .register_resource::<EnvironmentMap>()
        .register_resource::<AmbientOcclusion>();
}

/// Dress the classic setup: sky, lights, the arena model, soldiers, weapons
/// and the effect pools. Runs last in setup, so every classic entity keeps
/// the index it has in the classic look.
pub fn dress(w: &mut World, look: Look, camera: Entity) {
    lighting(w, look);
    w.spawn_named(
        "arena",
        (Transform::default(), Mesh::asset("arena.model"), Ambient),
    );
    let bots: Vec<(Entity, u32, f32)> = w
        .query::<&Fighter>()
        .iter()
        .filter(|(_, f)| f.bot)
        .map(|(e, f)| (e, f.slot, f.hp))
        .collect();
    for (root, slot, hp) in bots {
        let label = w.require::<Fighter>(root).label.clone();
        let soldier = w.spawn_named(
            format!("{label}-soldier"),
            (
                Parent(root),
                Transform::default(),
                Soldier {
                    slot,
                    hp,
                    ..Soldier::default()
                },
                Ambient,
            ),
        );
        // Rigid parts, each at its joint; `present` poses them.
        let mut joints: Vec<(Joint, Entity)> = Vec::new();
        for (joint, parent, at, model) in Joint::SKELETON {
            let parent = parent
                .and_then(|p| joints.iter().find(|(j, _)| *j == p))
                .map_or(soldier, |(_, e)| *e);
            let e = w.spawn((
                Parent(parent),
                Transform::at(at[0], at[1], at[2]),
                Mesh::asset(format!("soldier_{model}.model")),
                Limb { slot, joint },
                Ambient,
            ));
            joints.push((joint, e));
        }
        // The muzzle of the rifle the soldier carries across its chest.
        let gun = joints
            .iter()
            .find(|(j, _)| *j == Joint::Gun)
            .expect("gun")
            .1;
        w.spawn_named(
            format!("{label}-flash"),
            (
                Parent(gun),
                Transform::at(0.0, 0.01, -0.66).with_scale(1.4),
                Mesh::asset("flash.model"),
                BotFlash { slot },
                Ambient,
            ),
        );
    }
    viewmodel(w, camera);
    pools(w);
}

fn lighting(w: &mut World, look: Look) {
    let night = look == Look::Night;
    let (zenith, horizon, ground) = if night {
        (
            [0.01, 0.015, 0.04],
            [0.03, 0.035, 0.06],
            [0.01, 0.01, 0.012],
        )
    } else {
        ([0.07, 0.13, 0.42], [0.95, 0.52, 0.32], [0.08, 0.06, 0.05])
    };
    w.insert_resource(Environment {
        background: None,
        zenith,
        horizon,
        ground,
        ambient: if night { 0.35 } else { 0.8 },
        sun_disc: if night { 0.012 } else { 0.01 },
        exposure: if night { 1.6 } else { 1.05 },
        fog: Some(Fog {
            color: Some(if night {
                [0.03, 0.04, 0.07]
            } else {
                [0.72, 0.55, 0.5]
            }),
            ..Fog::new(if night { 0.01 } else { 0.0028 }, 0.05)
        }),
        bloom: Some(Bloom {
            intensity: 0.22,
            ..Bloom::default()
        }),
    });
    w.insert_resource(EnvironmentMap {
        texture: if night { "sky_night.tex" } else { "sky.tex" }.into(),
        intensity: if night { 0.6 } else { 1.0 },
        rgbm: if night { 4.0 } else { 8.0 },
        visible: true,
        rotation: 0.0,
    });
    w.insert_resource(AmbientOcclusion {
        radius: 0.6,
        intensity: 0.9,
        quality: AoQuality::Medium,
    });
    // A low sun behind the red end, or the moon, high, blue and dim: where the
    // skies (art-src/textures.mjs SUN and MOON) paint them.
    let sun = if night {
        Vec3::new(-14.0, 22.0, -9.0)
    } else {
        Vec3::new(-24.0, 9.0, -34.0)
    };
    let e = w.named("sun").expect("sun");
    w.insert(
        e,
        Transform::at(sun.x, sun.y, sun.z).looking_at(Vec3::ZERO, Vec3::Y),
    );
    w.insert(
        e,
        DirectionalLight {
            color: if night {
                [0.55, 0.65, 1.0]
            } else {
                [1.0, 0.72, 0.48]
            },
            illuminance: if night { 900.0 } else { 9000.0 },
            shadows: true,
        },
    );
    // Four pylon floodlights aimed at the deck; the warm diagonal pair casts
    // shadows (two of the eight local shadow layers, about a millisecond each).
    for (i, [x, z]) in crate::tables::of(w)
        .arena
        .lights
        .clone()
        .into_iter()
        .enumerate()
    {
        let e = w.spawn_named(
            format!("flood-{i}"),
            (
                Transform::at(x * 0.97, 6.2, z * 0.97)
                    .looking_at(Vec3::new(0.0, 0.5, 0.0), Vec3::Y),
                SpotLight {
                    color: if i % 3 == 0 {
                        [1.0, 0.82, 0.6]
                    } else {
                        [0.7, 0.85, 1.0]
                    },
                    intensity: if night { 2_500_000.0 } else { 600_000.0 },
                    range: 42.0,
                    inner: 0.28,
                    outer: 0.62,
                },
            ),
        );
        if i % 3 == 0 {
            w.insert(e, LightShadows);
        }
    }
}

/// The first-person weapons, children of the camera in the viewmodel layer.
fn viewmodel(w: &mut World, camera: Entity) {
    use Part::*;
    let rifle = Vec3::new(0.14, -0.165, -0.47);
    let launcher = Vec3::new(0.2, -0.18, -0.6);
    let parts = [
        ("vm-art-rifle", Weapon::Rifle, Body, rifle, "rifle.model"),
        (
            "vm-art-mag",
            Weapon::Rifle,
            Magazine,
            rifle + Vec3::new(0.0, -0.035, -0.14) * VIEW_SCALE,
            "mag.model",
        ),
        (
            "vm-art-rifle-flash",
            Weapon::Rifle,
            Flash,
            rifle + Vec3::new(0.0, 0.012, -0.57) * VIEW_SCALE,
            "flash.model",
        ),
        (
            "vm-art-rocket",
            Weapon::Rocket,
            Body,
            launcher,
            "launcher.model",
        ),
        (
            "vm-art-rocket-flash",
            Weapon::Rocket,
            Flash,
            launcher + Vec3::new(0.0, 0.0, -0.64) * VIEW_SCALE,
            "flash.model",
        ),
        (
            "vm-art-knife",
            Weapon::Knife,
            Body,
            Vec3::new(0.19, -0.19, -0.3),
            "knife.model",
        ),
    ];
    for (name, weapon, part, at, model) in parts {
        w.spawn_named(
            name,
            (
                Parent(camera),
                Transform::at(at.x, at.y, at.z).with_scale(VIEW_SCALE),
                Mesh::asset(model),
                ViewModel,
                Held { weapon, part },
            ),
        );
    }
    // The muzzle's light, lit for a moment by each of the player's shots.
    w.spawn_named(
        "vm-light",
        (
            Parent(camera),
            Transform::at(0.15, -0.1, -0.9),
            PointLight {
                color: [1.0, 0.7, 0.35],
                intensity: 0.0,
                range: 9.0,
            },
            Ambient,
        ),
    );
}

#[allow(clippy::too_many_arguments)]
fn burst(
    life: f32,
    speed: f32,
    spread: f32,
    gravity: f32,
    size: [f32; 2],
    color: [[f32; 4]; 2],
    additive: bool,
    seed: u64,
) -> Emitter {
    Emitter {
        rate: 0.0,
        lifetime: life,
        speed,
        spread,
        gravity: Vec3::new(0.0, -gravity, 0.0),
        drag: 1.5,
        size,
        color,
        additive,
        seed,
        bound: [-30.0, -30.0, -30.0, 30.0, 30.0, 30.0],
        ..Emitter::default()
    }
}
fn smoke() -> ParticleLook {
    ParticleLook {
        texture: "smoke.tex".into(),
        soft: 0.5,
        ..ParticleLook::default()
    }
}

/// Effect pools: emitters whose particles stay where they were born
/// (`WorldSpace`), moved to each new impact, blast or rocket and fired there.
fn pools(w: &mut World) {
    let hidden = Transform::at(0.0, -40.0, 0.0);
    for i in 0..SPARKS {
        let spark = |seed, color| {
            (
                hidden,
                Emitter {
                    shape: Shape::Sphere(0.03),
                    ..burst(0.35, 5.5, 1.1, 9.0, [0.05, 0.0], color, true, seed)
                },
                WorldSpace::default(),
                ParticleLook {
                    stretch: 0.03,
                    ..ParticleLook::default()
                },
                Ambient,
            )
        };
        w.spawn_named(
            format!("fx-spark-{i}"),
            spark(
                0x5a_0000 + u64::from(i),
                [[1.0, 0.85, 0.45, 1.0], [1.0, 0.3, 0.05, 0.0]],
            ),
        );
        w.spawn_named(
            format!("fx-blood-{i}"),
            spark(
                0xb1_0000 + u64::from(i),
                [[0.9, 0.12, 0.08, 1.0], [0.35, 0.02, 0.02, 0.0]],
            ),
        );
    }
    for i in 0..BLASTS {
        let seed = 0xb7_0000 + u64::from(i) * 4;
        w.spawn_named(
            format!("fx-fire-{i}"),
            (
                hidden,
                burst(
                    0.55,
                    9.0,
                    std::f32::consts::PI,
                    2.0,
                    [0.8, 0.15],
                    [[1.0, 0.75, 0.3, 1.0], [1.0, 0.15, 0.02, 0.0]],
                    true,
                    seed,
                ),
                WorldSpace::default(),
                Ambient,
            ),
        );
        w.spawn_named(
            format!("fx-smoke-{i}"),
            (
                hidden,
                Emitter {
                    shape: Shape::Sphere(0.6),
                    ..burst(
                        1.8,
                        2.6,
                        std::f32::consts::PI,
                        -0.8,
                        [0.9, 2.6],
                        [[0.32, 0.3, 0.28, 0.75], [0.2, 0.2, 0.22, 0.0]],
                        false,
                        seed + 1,
                    )
                },
                WorldSpace::default(),
                smoke(),
                Ambient,
            ),
        );
        w.spawn_named(
            format!("fx-light-{i}"),
            (
                hidden,
                PointLight {
                    color: [1.0, 0.6, 0.25],
                    intensity: 0.0,
                    range: 14.0,
                },
                Ambient,
            ),
        );
    }
    for i in 0..TRAILS {
        w.spawn_named(
            format!("fx-trail-{i}"),
            (
                hidden,
                Emitter {
                    rate: 70.0,
                    running: false,
                    ..burst(
                        1.0,
                        0.4,
                        std::f32::consts::PI,
                        -0.6,
                        [0.12, 0.7],
                        [[0.85, 0.8, 0.75, 0.5], [0.4, 0.4, 0.42, 0.0]],
                        false,
                        0x7a_0000 + u64::from(i),
                    )
                },
                WorldSpace::default(),
                smoke(),
                Ambient,
            ),
        );
    }
    w.insert_resource(Fx {
        blast_at: vec![None; BLASTS as usize],
        ..Fx::default()
    });
}

/// Fire pool emitter `name` at `at`.
fn fire(w: &mut World, name: &str, at: Vec3, count: u32) {
    let e = w.named(name).expect("pooled effect");
    w.teleport(e, Transform::at(at.x, at.y, at.z));
    let mut emitter = w.require_mut::<Emitter>(e);
    emitter.state.burst = emitter.state.burst.saturating_add(count);
}

/// The pass's part of a tick, after the fight's: dress what the fight spawned,
/// move the pools, record hits and shots, light the muzzle.
pub fn step(w: &mut World, input: &Input) {
    let tick = w.tick();
    let hz = w.hz() as f32;
    // A rocket draws as the rocket model with its own light and a pooled trail.
    let rockets: Vec<Entity> = w
        .query::<&Rocket>()
        .without::<Dressed>()
        .iter()
        .map(|(e, _)| e)
        .collect();
    for e in rockets {
        let used: Vec<u32> = w.query::<&Trail>().iter().map(|(_, t)| t.0).collect();
        let free = (0..TRAILS).find(|i| !used.contains(i));
        w.remove::<Material>(e);
        w.insert(e, Mesh::asset("rocket.model"));
        w.insert(
            e,
            PointLight {
                color: [1.0, 0.55, 0.2],
                intensity: 300.0,
                range: 6.0,
            },
        );
        if let Some(i) = free {
            w.insert(e, Trail(i));
        }
        w.insert(e, Dressed);
    }
    for i in 0..TRAILS {
        let at = w
            .query::<(&Trail, &Transform)>()
            .iter()
            .find(|(_, (t, _))| t.0 == i)
            .map(|(_, (_, pose))| pose.position);
        let e = w.named(&format!("fx-trail-{i}")).expect("trail");
        if let Some(at) = at {
            w.teleport(e, Transform::at(at.x, at.y, at.z));
        }
        let running = at.is_some();
        if w.require::<Emitter>(e).running != running {
            w.require_mut::<Emitter>(e).running = running;
        }
    }
    // The fight's cosmetics this tick: impacts throw sparks (red off a fighter),
    // a blast fires the next pooled fireball, smoke and flash.
    let fresh: Vec<(Entity, Vec3, f32, Mesh)> = w
        .query::<(&Effect, &Transform, &Mesh)>()
        .without::<Dressed>()
        .iter()
        .map(|(e, (fx, t, mesh))| (e, t.position, fx.grow, mesh.clone()))
        .collect();
    let bodies: Vec<Vec3> = w
        .query::<(&Fighter, &Transform)>()
        .iter()
        .filter(|(_, (f, _))| f.alive)
        .map(|(_, (_, t))| t.position)
        .collect();
    for (e, at, grow, mesh) in fresh {
        w.insert(e, Dressed);
        if grow > 0.0 {
            let mut fx = w.resource_mut::<Fx>();
            let i = fx.blasts % BLASTS;
            fx.blasts += 1;
            fx.blast_at[i as usize] = Some(tick);
            drop(fx);
            fire(w, &format!("fx-fire-{i}"), at, 70);
            fire(w, &format!("fx-smoke-{i}"), at + Vec3::Y * 0.3, 30);
            let light = w.named(&format!("fx-light-{i}")).expect("light");
            w.teleport(light, Transform::at(at.x, at.y + 0.5, at.z));
        } else if matches!(mesh, Mesh::Sphere { radius } if radius < 0.1) {
            let flesh = bodies.iter().any(|b| {
                Vec2::new(at.x - b.x, at.z - b.z).length() < fighter::RADIUS + 0.15
                    && (at.y - b.y).abs() < fighter::HEIGHT * 0.55
            });
            let mut fx = w.resource_mut::<Fx>();
            let (pool, i) = if flesh {
                fx.blood += 1;
                ("blood", fx.blood % SPARKS)
            } else {
                fx.sparks += 1;
                ("spark", fx.sparks % SPARKS)
            };
            drop(fx);
            fire(w, &format!("fx-{pool}-{i}"), at, 14);
        }
    }
    let blasts = w.resource::<Fx>().blast_at.clone();
    for (i, at) in blasts.into_iter().enumerate() {
        let age = at.map_or(f32::MAX, |t| tick.saturating_sub(t) as f32 / hz);
        let left = (1.0 - age / 0.4).clamp(0.0, 1.0);
        let intensity = 9000.0 * left * left;
        let name = format!("fx-light-{i}");
        if w.require::<PointLight>(name.as_str()).intensity != intensity {
            w.require_mut::<PointLight>(name.as_str()).intensity = intensity;
        }
    }
    // The player's muzzle light, and an inspect (T) that a shot or reload ends.
    let f = w.require::<Fighter>("player").clone();
    let shot = w.resource::<Feedback>().shot_tick;
    let flashing = f.alive
        && f.weapon != Weapon::Knife
        && shot.is_some_and(|t| tick.saturating_sub(t) < (0.045 * hz) as u64);
    let light = if flashing { 1600.0 } else { 0.0 };
    if w.require::<PointLight>("vm-light").intensity != light {
        w.require_mut::<PointLight>("vm-light").intensity = light;
    }
    if input.pressed("inspect") && f.alive && f.reload_until == 0.0 && f.bandage_until == 0.0 {
        w.resource_mut::<Fx>().inspect_tick = Some(tick);
    }
    // Soldiers: when each was last hit and last fired.
    let fighters: Vec<(u32, f32, u32)> = w
        .query::<&Fighter>()
        .iter()
        .map(|(_, f)| (f.slot, f.hp, f.shots))
        .collect();
    for (_, s) in w.query::<&mut Soldier>().iter() {
        let Some(&(_, hp, shots)) = fighters.iter().find(|f| f.0 == s.slot) else {
            continue;
        };
        if hp < s.hp {
            s.hit_tick = Some(tick);
        }
        if shots != s.shots {
            s.shot_tick = Some(tick);
        }
        s.hp = hp;
        s.shots = shots;
    }
}
