[package]
name = "exact-game"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam = { version = "0.33", default-features = false, features = ["std", "scalar-math", "libm"] }
libm = "0.2"
exact-game-derive = { path = "../derive" }
exact-plan = { path = "../../plan" }
exact-motion = { path = "../../motion" }

[dev-dependencies]
exact-game-scene = { path = "../scene" }
