// Host adapters belong to the bake, never to a game author.
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, relative, resolve } from 'node:path';

// Resolve authored keys in memory; only the bake writes the resolved manifest.
const merge = (base, overrides) => {
  const result = {...base};
  for (const [key, value] of Object.entries(overrides)) {
    result[key] = value && typeof value === "object" && !Array.isArray(value) && base[key] && typeof base[key] === "object" && !Array.isArray(base[key]) ? merge(base[key], value) : value;
  }
  return result;
};
const gameRoot = resolve(import.meta.dir, '..');
const cargoHeader = "# Generated by the game bake;";
const writeChanged = (path, text, authored = true) => {
  if (!existsSync(path) || readFileSync(path, "utf8") !== text) {
    if (authored && process.env.EXACT_PROOF_REPIN === '1') throw new Error(`repin refused: manifest normalization would write ${path}; run the ordinary bake first`);
    writeFileSync(path, text);
  }
};
// Only the literal Game declaration used by the template is inferred; unusual
// Rust exports/IDs use app.json. Rust remains responsible for checking the type.
export function gameDefaults(dir, workspace = gameRoot) {
  const source = resolve(dir, 'logic/src/lib.rs'), path = resolve(dir, 'app.json');
  if (!existsSync(source)) return null;
  const authored = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : {};
  const overrides = authored;
  const rust = readFileSync(source, 'utf8');
  const declaration = /impl\s+(?:exact_(?:game|world)::)?Game\s+for\s+(\w+)\s*\{[^{}]*?\bconst\s+ID\s*:\s*&'static\s+str\s*=\s*"([a-z][a-z0-9-]*)"/.exec(rust);
  if (!declaration && !(overrides.game?.crate && overrides.game?.type)) return null;
  if (!declaration && (!(overrides.id ?? overrides.app?.id) || !(overrides.name ?? overrides.app?.name)))
    throw new Error(`${path}: explicit id and name are required when the Game declaration cannot be inferred`);
  const [, type, gameId] = declaration ?? [], name = basename(dir);
  const cargoPath = resolve(dir, 'logic/Cargo.toml');
  const cargo = existsSync(cargoPath) ? readFileSync(cargoPath, 'utf8') : null;
  const crate = overrides.game?.crate ?? (cargo && !cargo.startsWith(cargoHeader) ? Bun.TOML.parse(cargo).package.name : `${name}-logic`);
  const title = overrides.name ?? overrides.app?.name ?? name.split('-').map(word => word[0].toUpperCase() + word.slice(1)).join(' ');
  const id = overrides.id ?? overrides.app?.id ?? `com.exact.${gameId}`;
  const app = merge({
    name:title, short_name:title, id, start_url:'/', display:'standalone',
    theme_color:'#202731', background_color:'#202731',
    app:{id, name:title},
    host:{macos:{minimumOS:'14.0', window:{width:1280,height:720}}, ios:{minimumOS:'17.0',deviceFamily:['iphone','ipad']},web:{}},
    game:{crate, type}, rust:false,
    deploy:{store:{web:'0',macos:'0',ios:'0',linux:'0'}},
  }, overrides);
  const manifest = resolve(dir, 'logic/Cargo.toml');
  if (app.game && (!existsSync(manifest) || readFileSync(manifest, 'utf8').startsWith(cargoHeader))) writeChanged(manifest,
    `# Generated by the game bake; an authored manifest overrides these defaults.\n[package]\nname = "${app.game.crate}"\nversion = "0.1.0"\nedition = "2021"\nlicense = "MIT"\nworkspace = "../.shells"\n\n[dependencies]\n${app.game.world ? "exact-world" : "exact-game"} = { path = ${JSON.stringify(relative(resolve(dir, 'logic'), resolve(workspace, app.game.world ? '../world' : 'engine')))} }\n`);
  if (app.game?.world === true && (app.game.audio === true || app.game.assets === true)) {
    throw new Error("ownership-only worlds do not support game.audio or game.assets; use a device game module");
  }
  return app;
}

export function gameShells(dir, game, workspace) {
  // Only this app is materialized. Each bake owns a generated Cargo workspace.
  const app = {game, ...gameDefaults(dir, workspace)};
  if (app.game.world === true && (app.game.audio === true || app.game.assets === true)) {
    throw new Error("ownership-only worlds do not support game.audio or game.assets");
  }
  const root = resolve(dir, '.shells'), desired = new Map();
  const source = existsSync(resolve(workspace, 'Cargo.toml')) ? workspace : gameRoot;
  const cargo = Bun.TOML.parse(readFileSync(resolve(source, 'Cargo.toml'), 'utf8'));
  cargo.workspace.members = ['*-gpu','*-web','*-apple','*-linux','../logic'];
  delete cargo.workspace.exclude;
  for (const deps of [cargo.workspace.dependencies, ...Object.values(cargo.patch ?? {})]) {
    for (const dep of Object.values(deps ?? {})) if (dep.path) dep.path = relative(root, resolve(source, dep.path));
  }
  const toml = value => value && typeof value === 'object' && !Array.isArray(value)
    ? `{ ${Object.entries(value).map(([key,item])=>`${JSON.stringify(key)} = ${toml(item)}`).join(', ')} }`
    : Array.isArray(value) ? `[${value.map(toml).join(', ')}]` : JSON.stringify(value);
  mkdirSync(root,{recursive:true});
  mkdirSync(resolve(root,'.cargo'),{recursive:true});
  writeChanged(resolve(root,'.cargo/config.toml'), readFileSync(resolve(gameRoot,'.cargo/config.toml'),'utf8'), false);
  writeChanged(resolve(root, 'app.json'), JSON.stringify(app, null, 2) + '\n', false);
  writeChanged(resolve(root,'Cargo.toml'), '# Generated by the game bake.\n' + Object.entries(cargo)
    .map(([key,value])=>`[${key}]\n${Object.entries(value).map(([key,value])=>`${JSON.stringify(key)} = ${toml(value)}\n`).join('')}`).join('\n'), false);
  const lock = resolve(dir, 'Cargo.lock');
  if (existsSync(lock)) writeChanged(resolve(root, 'Cargo.lock'), readFileSync(lock, 'utf8'), false);
  const appDir = dir;
  const logicDir = resolve(appDir, 'logic'), {crate, type} = app.game;
  const manifest = resolve(logicDir, 'Cargo.toml');
  if (!existsSync(manifest) || Bun.TOML.parse(readFileSync(manifest, 'utf8')).package?.name !== crate) {
    throw new Error(`game.crate ${crate} must name the package in ${appDir}/logic`);
  }
  if (Bun.TOML.parse(readFileSync(manifest, 'utf8')).package.workspace !== '../.shells') {
    throw new Error(`${manifest}: set package.workspace = "../.shells" so the app owns its logic`);
  }
  if (app.game.audio !== undefined && typeof app.game.audio !== "boolean") throw new Error("game.audio must be a boolean");
  if (app.game.assets !== undefined && typeof app.game.assets !== "boolean") throw new Error("game.assets must be a boolean");
  // Resolve validates manifest syntax; Rust checks this path's exported type
  // when compiling the generated GPU shell, including macro/cfg exports.
  const name = crate.slice(0, -'-logic'.length);
  const key = createHash('sha256').update(app.app.id).digest('hex').slice(0, 24);
  // An absent art directory must not be a Cargo watch: missing paths are always
  // dirty. Keep the baker only for art or a final generated-output cleanup.
  const bakeArt = !app.game.world && (existsSync(resolve(appDir, 'art')) || existsSync(resolve(appDir, '.baked-assets.json')));
  for (const kind of ['gpu', 'web', 'apple', 'linux']) {
    const shellName = `${key}-${kind}`, shell = resolve(root, shellName);
    // These adapters contain entry points only; tests live in authored crates.
    const target = kind === 'linux'
      ? `[[bin]]\nname = "${name}-linux"\npath = "src/main.rs"\ntest = false`
      : `[lib]\ncrate-type = ["${kind === 'apple' ? 'staticlib' : 'cdylib'}", "rlib"]\ntest = false\ndoctest = false`;
    const header = `[package]\nname = "${name}-${kind}"\nversion.workspace = true\nedition.workspace = true\nlicense.workspace = true\npublish = false\n\n${target}\n\n[dependencies]\n`;
    const dependencies = kind === 'gpu'
      ? `${app.game.world ? "exact-world-adapter" : "exact-game-render"}.workspace = true\n${app.game.audio === true ? "exact-game-audio.workspace = true\n" : ""}game-logic = { package = "${crate}", path = ${JSON.stringify(relative(shell, logicDir))} }\n\n[target.'cfg(target_arch = "wasm32")'.dependencies]\nwasm-bindgen.workspace = true\nwasm-bindgen-futures.workspace = true\nweb-sys.workspace = true\n\n[build-dependencies]\n${app.game.world ? "exact-world-adapter" : "exact-game-app"}.workspace = true\ngame-logic = { package = "${crate}", path = ${JSON.stringify(relative(shell, logicDir))} }\n${bakeArt ? 'exact-game-bake.workspace = true\n' : ''}`
      : `exact-runner.workspace = true\nexact-${kind}.workspace = true\n\n[build-dependencies]\n${app.game.world ? "exact-app-shell" : "exact-game-app"}.workspace = true\n`;
    desired.set(shellName, {
      'Cargo.toml': header + dependencies,
      [kind === 'linux' ? 'src/main.rs' : 'src/lib.rs']: kind === 'gpu' ? `${app.game.world ? "exact_world_adapter" : "exact_game_render"}::module!(game_logic::${type}${app.game.audio === true ? ", audio" : ""}${app.game.assets === true ? ", assets" : ""});\n` : 'include!(concat!(env!("OUT_DIR"), "/entry.rs"));\n',
      'build.rs': kind === 'gpu'
        ? `fn main() {\n    ${app.game.world ? "exact_world_adapter::emit_declaration" : "exact_game_app::emit_declaration"}::<game_logic::${type}>(${JSON.stringify(relative(shell, appDir))})${app.game.world ? '.expect("world surface declaration")' : ""};\n${bakeArt ? `    exact_game_bake::bake_art(${JSON.stringify(relative(shell, appDir))}).expect("bake art");\n` : ''}    println!("cargo:rerun-if-changed=build.rs");\n}\n`
        : `fn main() {\n    ${app.game.world ? "exact_app_shell" : "exact_game_app"}::bake_declaration("${kind}", ${JSON.stringify(relative(shell, appDir))});\n}\n`,
    });
  }
  mkdirSync(root, {recursive:true});
  // The snapshot excludes this entire generated root, including its gitignore.
  if (!existsSync(resolve(root, '.gitignore'))) writeFileSync(resolve(root, '.gitignore'), '*\n!.gitignore\n');
  for (const [name, files] of desired) {
    const shell = resolve(root, name);
    if (Object.entries(files).every(([file, bytes]) => existsSync(resolve(shell, file)) && readFileSync(resolve(shell, file), 'utf8') === bytes)) continue;
    const stage = mkdtempSync(resolve(root, '.shell-stage-'));
    try {
      const replacement = resolve(stage, 'new'), backup = resolve(stage, 'old');
      for (const [file, bytes] of Object.entries(files)) {
        const path = resolve(replacement, file);
        mkdirSync(dirname(path), {recursive:true}); writeFileSync(path, bytes);
      }
      if (existsSync(shell)) renameSync(shell, backup);
      try { renameSync(replacement, shell); }
      catch (error) { if (existsSync(backup)) renameSync(backup, shell); throw error; }
    } finally { rmSync(stage, {recursive:true, force:true}); }
  }
  // Prune adapters whose app identity changed. Cargo may also put its target
  // directory here; resolving an app must never discard that build cache.
  for (const entry of readdirSync(root, {withFileTypes:true})) {
    if (entry.isDirectory() && /^[a-f0-9]{24}-(gpu|web|apple|linux)$/.test(entry.name) && !desired.has(entry.name)) {
      rmSync(resolve(root, entry.name), {recursive:true});
    }
  }
  return game.crate.slice(0, -'-logic'.length);
}

// The template supplies the source lock. Every ordinary bake is locked;
// dependency edits require an explicit update, never a publisher's cache choice.
export function prepareGame(dir, game, source = gameRoot, {updateLock = false} = {}) {
  const root = resolve(dir, '.shells'), lock = resolve(dir, 'Cargo.lock');
  const captured = existsSync(lock), cached = resolve(root, 'Cargo.lock');
  if (!captured && existsSync(cached)) {
    rmSync(cached);
    throw new Error(`${cached}: stale shell lock without a captured source Cargo.lock; removed it. Restore the source lock or explicitly --update-lock`);
  }
  gameShells(dir, game, source);
  if (!captured && !updateLock) {
    const seed = resolve(source, 'new/Cargo.lock');
    if (!existsSync(seed)) throw new Error(`${lock}: missing captured lock and template seed; create the game with game/new.mjs or explicitly --update-lock`);
    const name = game.crate.replace(/-logic$/, '');
    writeChanged(cached, readFileSync(seed, 'utf8').replaceAll('small-game', name), false);
  }
  const result = spawnSync('cargo', ['metadata', '--offline', ...(!updateLock ? ['--locked'] : []), '--format-version', '1'], {
    cwd:root, env:{...process.env}, encoding:'utf8', maxBuffer:64 * 1024 * 1024,
  });
  if (result.status !== 0) throw new Error(`game Cargo graph: ${result.stderr || result.error?.message}\nOffline resolution requires a populated Cargo cache: cargo fetch --locked --manifest-path ${JSON.stringify(resolve(root, "Cargo.toml"))}\nTo capture dependency changes: bun game/app/shells.mjs ${JSON.stringify(dir)} --update-lock`);
  if (!captured || updateLock) writeChanged(lock, readFileSync(resolve(root, 'Cargo.lock'), 'utf8'), captured);
  return JSON.parse(result.stdout);
}

if (import.meta.main) {
  if (process.argv.includes('--test')) {
    let failed=false;
    for (const group of ['games','bench']) for (const name of readdirSync(resolve(gameRoot, group))) {
      const dir=resolve(gameRoot,group,name);
      if (!existsSync(resolve(dir,'logic/src/lib.rs'))) continue;
      try {
        prepareGame(dir, gameDefaults(dir).game);
        const result=spawnSync('cargo',['test','--workspace','--locked','--offline','--no-fail-fast'], {
          cwd:resolve(dir,'.shells'),env:{...process.env,CARGO_TARGET_DIR:process.env.CARGO_TARGET_DIR ?? resolve(gameRoot,'target')},stdio:'inherit',
        });
        failed ||= result.status !== 0;
      } catch(error) {console.error(error);failed=true;}
    }
    process.exitCode=failed?1:0;
  } else {
    const dir = resolve(process.argv[2]);
    prepareGame(dir, gameDefaults(dir).game, gameRoot, {updateLock:process.argv.includes('--update-lock')});
  }
}
