// Host adapters belong to the bake, never to a game author.
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, relative, resolve } from 'node:path';

// Derive defaults in memory and retain exactly the authored override keys.
// A full manifest without the header owns the whole document.
const generated = "Generated by the game bake; authored keys override defaults. Remove this header for a whole manifest.";
const oldGenerated = "Generated by the game bake; remove this header to author overrides.";
const merge = (base, overrides) => {
  const result = {...base};
  for (const [key, value] of Object.entries(overrides)) {
    result[key] = value && typeof value === "object" && !Array.isArray(value) && base[key] && typeof base[key] === "object" && !Array.isArray(base[key]) ? merge(base[key], value) : value;
  }
  return result;
};
const gameRoot = resolve(import.meta.dir, '..');
const cargoHeader = "# Generated by the game bake;";
const writeChanged = (path, text, authored = true) => {
  if (!existsSync(path) || readFileSync(path, "utf8") !== text) {
    if (authored && process.env.EXACT_PROOF_REPIN === '1') throw new Error(`repin refused: manifest normalization would write ${path}; run the ordinary bake first`);
    writeFileSync(path, text);
  }
};
// Only the literal Game declaration used by the template is inferred; unusual
// Rust exports/IDs use app.json. Rust remains responsible for checking the type.
export function gameDefaults(dir, workspace = gameRoot) {
  const source = resolve(dir, 'logic/src/lib.rs'), path = resolve(dir, 'app.json');
  if (!existsSync(source)) return null;
  let app;
  if (existsSync(path)) app = JSON.parse(readFileSync(path, 'utf8'));
  // A compact bare override (e.g. {name:"Lanterns"}) enters the generated form.
  // Whole-manifest exports have explicit app identity and Rust entry points.
  const whole = app && !app._generated && app.app?.id && app.game?.crate && app.game?.type;
  if (!whole) {
    let overrides;
    if (app?._generated?.resolved) {
      overrides = structuredClone(app._generated.overrides);
      // Preserve authored keys across derivation, while recognizing edits to the
      // materialized document. Cargo's Contract compiler reads that full document.
      const edits = (before, after, owned) => {
        for (const key of Object.keys(before)) if (!(key in after)) delete owned[key];
        for (const [key, value] of Object.entries(after)) {
          if (key === '_generated' || JSON.stringify(value) === JSON.stringify(before[key])) continue;
          if (value && typeof value === 'object' && !Array.isArray(value) && before[key] && typeof before[key] === 'object' && !Array.isArray(before[key])) {
            owned[key] ??= {};
            edits(before[key], value, owned[key]);
          } else owned[key] = value;
        }
      };
      edits(app._generated.resolved, app, overrides);
    } else overrides = !app || app._generated === oldGenerated ? {} : {...app};
    delete overrides._generated;
    const rust = readFileSync(source, 'utf8');
    const declaration = /impl\s+(?:exact_game::)?Game\s+for\s+(\w+)\s*\{[^{}]*?\bconst\s+ID\s*:\s*&'static\s+str\s*=\s*"([a-z][a-z0-9-]*)"/.exec(rust);
    if (!declaration) return null;
    const [, type, id] = declaration, name = basename(dir);
    const cargoPath = resolve(dir, 'logic/Cargo.toml');
    const cargo = existsSync(cargoPath) ? readFileSync(cargoPath, 'utf8') : null;
    const crate = cargo && !cargo.startsWith(cargoHeader) ? Bun.TOML.parse(cargo).package.name : `${name}-logic`;
    const title = name.split('-').map(word => word[0].toUpperCase() + word.slice(1)).join(' ');
    app = {
      _generated: generated,
      name:title, short_name:title, id:`com.exact.${id}`, start_url:'/', display:'standalone',
      theme_color:'#202731', background_color:'#202731',
      app:{id:`com.exact.${id}`, name:title},
      host:{macos:{minimumOS:'14.0', window:{width:1280,height:720}}, ios:{minimumOS:'17.0',deviceFamily:['iphone','ipad']},web:{}},
      game:{crate, type}, rust:false,
      deploy:{store:{web:'0',macos:'0',ios:'0',linux:'0'}},
    };
    // Name is also the default host title and short name; explicit nested keys win.
    if (Object.hasOwn(overrides, 'name')) {
      app.short_name = overrides.name;
      app.app.name = overrides.name;
    }
    app = merge(app, overrides);
    const resolved = {...app}; delete resolved._generated;
    app._generated = {notice:generated, overrides, resolved};
    writeChanged(path, JSON.stringify(app, null, 2) + '\n');
  }
  const manifest = resolve(dir, 'logic/Cargo.toml');
  if (app.game && (!existsSync(manifest) || readFileSync(manifest, 'utf8').startsWith(cargoHeader))) writeChanged(manifest,
    `# Generated by the game bake; an authored manifest overrides these defaults.\n[package]\nname = "${app.game.crate}"\nversion = "0.1.0"\nedition = "2021"\nlicense = "MIT"\nworkspace = "../.shells"\n\n[dependencies]\nexact-game = { path = ${JSON.stringify(relative(resolve(dir, 'logic'), resolve(workspace, 'engine')))} }\n`);
  return app;
}

export function gameShells(dir, game, workspace) {
  // Only this app is materialized. Each bake owns a generated Cargo workspace.
  const apps = new Map([[dir, {game, ...gameDefaults(dir, workspace)}]]);
  const root = resolve(dir, '.shells'), desired = new Map();
  const source = existsSync(resolve(workspace, 'Cargo.toml')) ? workspace : gameRoot;
  const cargo = Bun.TOML.parse(readFileSync(resolve(source, 'Cargo.toml'), 'utf8'));
  cargo.workspace.members = ['*-gpu','*-web','*-apple','*-linux','../logic'];
  delete cargo.workspace.exclude;
  for (const deps of [cargo.workspace.dependencies, ...Object.values(cargo.patch ?? {})]) {
    for (const dep of Object.values(deps ?? {})) if (dep.path) dep.path = relative(root, resolve(source, dep.path));
  }
  const toml = value => value && typeof value === 'object' && !Array.isArray(value)
    ? `{ ${Object.entries(value).map(([key,item])=>`${JSON.stringify(key)} = ${toml(item)}`).join(', ')} }`
    : Array.isArray(value) ? `[${value.map(toml).join(', ')}]` : JSON.stringify(value);
  mkdirSync(root,{recursive:true});
  writeChanged(resolve(root,'Cargo.toml'), '# Generated by the game bake.\n' + Object.entries(cargo)
    .map(([key,value])=>`[${key}]\n${Object.entries(value).map(([key,value])=>`${JSON.stringify(key)} = ${toml(value)}\n`).join('')}`).join('\n'), false);
  const lock = resolve(dir, 'Cargo.lock');
  if (existsSync(lock)) writeChanged(resolve(root, 'Cargo.lock'), readFileSync(lock, 'utf8'), false);
  for (const [appDir, app] of apps) {
    const logicDir = resolve(appDir, 'logic'), {crate, type} = app.game;
    const manifest = resolve(logicDir, 'Cargo.toml');
    if (!existsSync(manifest) || Bun.TOML.parse(readFileSync(manifest, 'utf8')).package?.name !== crate) {
      throw new Error(`game.crate ${crate} must name the package in ${appDir}/logic`);
    }
    if (Bun.TOML.parse(readFileSync(manifest, 'utf8')).package.workspace !== '../.shells') {
      throw new Error(`${manifest}: set package.workspace = "../.shells" so the app owns its logic`);
    }
    if (app.game.audio !== undefined && typeof app.game.audio !== "boolean") throw new Error("game.audio must be a boolean");
    if (app.game.assets !== undefined && typeof app.game.assets !== "boolean") throw new Error("game.assets must be a boolean");
    // Resolve validates manifest syntax; Rust checks this path's exported type
    // when compiling the generated GPU shell, including macro/cfg exports.
    const name = crate.slice(0, -'-logic'.length);
    const key = createHash('sha256').update(app.app.id).digest('hex').slice(0, 24);
    // An absent art directory must not be a Cargo watch: missing paths are always
    // dirty. Keep the baker only for art or a final generated-output cleanup.
    const bakeArt = existsSync(resolve(appDir, 'art')) || existsSync(resolve(appDir, '.baked-assets.json'));
    for (const kind of ['gpu', 'web', 'apple', 'linux']) {
      const shellName = `${key}-${kind}`, shell = resolve(root, shellName);
      // These adapters contain entry points only; tests live in authored crates.
      const target = kind === 'linux'
        ? `[[bin]]\nname = "${name}-linux"\npath = "src/main.rs"\ntest = false`
        : `[lib]\ncrate-type = ["${kind === 'apple' ? 'staticlib' : 'cdylib'}", "rlib"]\ntest = false\ndoctest = false`;
      const header = `[package]\nname = "${name}-${kind}"\nversion.workspace = true\nedition.workspace = true\nlicense.workspace = true\npublish = false\n\n${target}\n\n[dependencies]\n`;
      const dependencies = kind === 'gpu'
        ? `exact-game-render.workspace = true\n${app.game.audio === true ? "exact-game-audio.workspace = true\n" : ""}game-logic = { package = "${crate}", path = ${JSON.stringify(relative(shell, logicDir))} }\n\n[target.'cfg(target_arch = "wasm32")'.dependencies]\nwasm-bindgen.workspace = true\nwasm-bindgen-futures.workspace = true\nweb-sys.workspace = true\n${bakeArt ? '\n[build-dependencies]\nexact-game-bake.workspace = true\n' : ''}`
        : `exact-runner.workspace = true\nexact-${kind}.workspace = true\n\n[build-dependencies]\nexact-game-app.workspace = true\ngame-logic = { package = "${crate}", path = ${JSON.stringify(relative(shell, logicDir))} }\n`;
      desired.set(shellName, {
        'Cargo.toml': header + dependencies,
        [kind === 'linux' ? 'src/main.rs' : 'src/lib.rs']: kind === 'gpu' ? `exact_game_render::module!(game_logic::${type}${app.game.audio === true ? ", audio" : ""}${app.game.assets === true ? ", assets" : ""});\n` : 'include!(concat!(env!("OUT_DIR"), "/entry.rs"));\n',
        ...(kind === 'gpu' ? bakeArt ? {'build.rs': `fn main() {\n    exact_game_bake::bake_art(${JSON.stringify(relative(shell, appDir))}).expect("bake art");\n}\n`} : {} : {'build.rs': `fn main() {\n    exact_game_app::bake_game::<game_logic::${type}>("${kind}", ${JSON.stringify(relative(shell, appDir))});\n}\n`}),
      });
    }
  }
  mkdirSync(root, {recursive:true});
  // The snapshot excludes this entire generated root, including its gitignore.
  if (!existsSync(resolve(root, '.gitignore'))) writeFileSync(resolve(root, '.gitignore'), '*\n!.gitignore\n');
  for (const [name, files] of desired) {
    const shell = resolve(root, name);
    if (Object.entries(files).every(([file, bytes]) => existsSync(resolve(shell, file)) && readFileSync(resolve(shell, file), 'utf8') === bytes)) continue;
    const stage = mkdtempSync(resolve(root, '.shell-stage-'));
    try {
      const replacement = resolve(stage, 'new'), backup = resolve(stage, 'old');
      for (const [file, bytes] of Object.entries(files)) {
        const path = resolve(replacement, file);
        mkdirSync(dirname(path), {recursive:true}); writeFileSync(path, bytes);
      }
      if (existsSync(shell)) renameSync(shell, backup);
      try { renameSync(replacement, shell); }
      catch (error) { if (existsSync(backup)) renameSync(backup, shell); throw error; }
    } finally { rmSync(stage, {recursive:true, force:true}); }
  }
  // Prune adapters whose app identity changed. Cargo may also put its target
  // directory here; resolving an app must never discard that build cache.
  for (const entry of readdirSync(root, {withFileTypes:true})) {
    if (entry.isDirectory() && /^[a-f0-9]{24}-(gpu|web|apple|linux)$/.test(entry.name) && !desired.has(entry.name)) {
      rmSync(resolve(root, entry.name), {recursive:true});
    }
  }
  return game.crate.slice(0, -'-logic'.length);
}

// The template supplies the source lock. Every ordinary bake is locked;
// dependency edits require an explicit update, never a publisher's cache choice.
export function prepareGame(dir, game, source = gameRoot, {updateLock = false} = {}) {
  const root = resolve(dir, '.shells'), lock = resolve(dir, 'Cargo.lock');
  const captured = existsSync(lock), cached = resolve(root, 'Cargo.lock');
  if (!captured && existsSync(cached)) {
    rmSync(cached);
    throw new Error(`${cached}: stale shell lock without a captured source Cargo.lock; removed it. Restore the source lock or explicitly --update-lock`);
  }
  gameShells(dir, game, source);
  if (!captured && !updateLock) {
    const seed = resolve(source, 'new/Cargo.lock');
    if (!existsSync(seed)) throw new Error(`${lock}: missing captured lock and template seed; create the game with game/new.mjs or explicitly --update-lock`);
    const name = game.crate.replace(/-logic$/, '');
    writeChanged(cached, readFileSync(seed, 'utf8').replaceAll('small-game', name), false);
  }
  const result = spawnSync('cargo', ['metadata', '--offline', ...(!updateLock ? ['--locked'] : []), '--format-version', '1'], {
    cwd:root, env:{...process.env}, encoding:'utf8', maxBuffer:64 * 1024 * 1024,
  });
  if (result.status !== 0) throw new Error(`game Cargo graph: ${result.stderr || result.error?.message}\nOffline resolution requires a populated Cargo cache: cargo fetch --locked --manifest-path ${JSON.stringify(resolve(root, "Cargo.toml"))}\nTo capture dependency changes: bun game/app/shells.mjs ${JSON.stringify(dir)} --update-lock`);
  if (!captured || updateLock) writeChanged(lock, readFileSync(resolve(root, 'Cargo.lock'), 'utf8'), captured);
  return JSON.parse(result.stdout);
}

if (import.meta.main) {
  if (process.argv.includes('--test')) {
    let failed=false;
    for (const group of ['games','bench']) for (const name of readdirSync(resolve(gameRoot, group))) {
      const dir=resolve(gameRoot,group,name);
      if (!existsSync(resolve(dir,'logic/src/lib.rs'))) continue;
      try {
        prepareGame(dir, gameDefaults(dir).game);
        const result=spawnSync('cargo',['test','--workspace','--locked','--offline','--no-fail-fast'], {
          cwd:resolve(dir,'.shells'),env:{...process.env,CARGO_TARGET_DIR:process.env.CARGO_TARGET_DIR ?? resolve(gameRoot,'target')},stdio:'inherit',
        });
        failed ||= result.status !== 0;
      } catch(error) {console.error(error);failed=true;}
    }
    process.exitCode=failed?1:0;
  } else {
    const dir = resolve(process.argv[2]);
    prepareGame(dir, gameDefaults(dir).game, gameRoot, {updateLock:process.argv.includes('--update-lock')});
  }
}
