[package]
name = "completion-storm-web"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
completion-storm-data = { path = "../data" }
exact-web = { path = "../../../host/web" }
exact-web-capabilities = { path = "../../../host/web-capabilities" }

[build-dependencies]
completion-storm-data = { path = "../data" }
contract = { path = "../../../contract/cli" }
exact-bake = { path = "../../../bake" }
