[package]
name = "update-lab-data"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
exact-data = { path = "../../../data" }
exact-plan = { path = "../../../plan" }
exact-runner = { path = "../../../runner" }

[dev-dependencies]
serde_json = "1.0"
contract = { path = "../../../contract/cli" }
exact-kernel = { path = "../../../kernel" }
