// GAP 001: bake cannot capture parent imports. Remove this copy when ancestor mounts work.
// Unchanged body from examples/t3-code/settings-catalog.ts at 887b2491b182f851b11253655f6aa84fe2a26708.
// Reference settingsSearch.ts SETTINGS_SEARCH_ITEMS (served 0.0.46 source revision), one row per item:
// [id, title, route, targetId, searchTerms, scope, availability flags]. Keybinding command items are
// derived from the connected server's keybindings at search time (settings-search.ts).
export const CATALOG: readonly (readonly [string, string, string, string, string, string, string])[] = [
  ["storage-worktrees", "Worktree cleanup", "storage", "", "disk storage delete deleted archived threads old inactive merged unchanged worktrees retention days project inherit off custom", "project-defaults", ""],
  ["storage-artifacts", "Artifacts and logs", "storage", "", "disk storage browser screenshots captures rotated logs cleanup retention", "environment-defaults", ""],
  ["project-defaults", "Project defaults and overrides", "general", "", "model workspace environments projects inheritance checkout", "project-defaults", ""],
  ["project-overview", "Project overview", "projects", "", "name icon emoji image checkout remove delete", "", ""],
  ["default-model", "Default model", "general", "", "new thread project provider reasoning effort", "project-defaults", ""],
  ["default-permissions", "Permissions", "general", "", "new thread default runtime mode supervised approvals auto accept edits full access", "project-defaults", ""],
  ["color-scheme", "Color scheme", "appearance", "appearance", "appearance light dark system mode", "", ""],
  ["theme", "Themes", "appearance", "appearance", "appearance colors palette custom import", "", ""],
  ["setting-appearance-contrast", "Contrast", "appearance", "", "colors borders interface", "", ""],
  ["setting-glass-opacity", "Glass opacity", "appearance", "", "transparent transparency solid menus dialogs composer", "", ""],
  ["diff-color-scheme", "Diff colors", "appearance", "", "red green blue orange additions deletions changes counts palette colorblind", "", ""],
  ["chat-width", "Chat width", "appearance", "", "wide full width column layout messages composer monitor", "", ""],
  ["panel-animations", "Panel animations", "appearance", "", "", "", ""],
  ["environment-identification", "Environment identification", "appearance", "appearance-interface", "dev nightly artwork pill label hide none", "", ""],
  ["interface-font", "Interface font", "appearance", "", "typography family size system sans", "", ""],
  ["prompt-font", "Prompt font", "appearance", "", "typography family size composer input", "", ""],
  ["code-font", "Code font", "appearance", "", "typography family size monospace code blocks diffs file previews", "", ""],
  ["terminal-font", "Terminal font", "appearance", "", "typography family size monospace output", "", ""],
  ["font-smoothing", "Font smoothing", "appearance", "", "typography text grayscale anti aliasing macos thin", "", "mac"],
  ["word-wrap", "Word wrap", "appearance", "", "long lines code blocks tables diffs file previews", "", ""],
  ["composer-context", "Composer context", "appearance", "", "", "", ""],
  ["project-grouping", "Project grouping", "general", "", "combine matching repositories environments sidebar", "", ""],
  ["project-order", "Project order", "general", "", "sort projects sidebar manual created recent", "", ""],
  ["snooze-limited-threads", "Snooze limited threads", "general", "", "usage quota rate limit reset wake recover continue", "", ""],
  ["auto-resume-limited-threads", "Auto-resume limited threads", "general", "", "usage quota rate limit reset recover continue", "", ""],
  ["working-shelf", "Working section (beta)", "general", "", "hide fold running monitoring threads inbox sidebar shelf", "", ""],
  ["auto-settle-inactive-threads", "Auto-settle inactive threads", "general", "", "sidebar inactivity days no activity automatically", "project-defaults", "autoSettle"],
  ["auto-settle-merged-threads", "Auto-settle merged threads", "general", "", "pull request merge closed automatically sidebar", "project-defaults", "autoSettle"],
  ["days-before-auto-settle", "Days of inactivity before auto-settle", "general", "auto-settle-inactive-threads", "thread timeout activity sidebar", "project-defaults", "autoSettle"],
  ["thread-notifications", "Thread notifications", "general", "", "notification sound alert completion input approval desktop", "", ""],
  ["in-app-notifications", "In-app notifications", "general", "", "notification toast popup completion input approval failure", "", ""],
  ["time-format", "Time format", "general", "", "timestamp clock locale system browser os 12 hour 24 hour", "", ""],
  ["response-streaming", "Response streaming", "general", "", "output token paragraph buffered wait turn legacy", "project-defaults", ""],
  ["hide-whitespace-changes", "Hide whitespace changes", "general", "", "diff ignore spaces edits default", "", ""],
  ["default-diff-file-state", "Default diff file state", "general", "", "collapsed expanded collapse expand files pull request pr code tab", "", ""],
  ["diff-layout", "Diff layout", "general", "", "stacked split side by side unified inline view", "", ""],
  ["proactive-panels", "Proactive panels", "general", "", "automatically open diff pull request pr right panel agent completion", "", ""],
  ["skills-in-slash-menu", "Show skills in slash menu", "general", "", "command menu dollar $ slash /", "", ""],
  ["composer-rich-text", "Rich text composer", "general", "", "composer rich text tiptap bold italic markdown styled wysiwyg", "", ""],
  ["composer-collapse", "Collapse composer on scroll", "general", "", "composer rest resting scroll wheel conversation timeline shrink minimize", "", ""],
  ["send-shortcut", "Send shortcut", "general", "", "enter return command ctrl multiline prompt new line composer", "", ""],
  ["follow-up-behavior", "Follow-up behavior", "general", "", "queue steer running turn send default behavior composer", "", ""],
  ["provider-update-checks", "Provider update checks", "general", "", "installed cli versions newer available codex claude cursor grok opencode", "environment-defaults", ""],
  ["continue-threads-after-server-update", "Continue threads after restarts", "general", "", "resume running active interrupted work restart reboot machine crash desktop update automatically", "project-defaults", ""],
  ["background-activity", "Background activity", "general", "", "balanced performance battery saver advanced git fetch provider health refresh host power monitor idle policy", "environment-defaults", ""],
  ["new-threads", "New threads", "general", "", "default workspace mode draft local worktree", "project-defaults", ""],
  ["worktree-submodules", "Submodules", "general", "", "git submodule init recursive top-level none worktree t3.json", "project-defaults", ""],
  ["start-from-origin", "Start from origin", "general", "", "new worktrees latest matching remote branch local", "project-defaults", ""],
  ["add-project-starts-in", "Add project starts in", "general", "", "base directory folder browser path home", "environment-defaults", ""],
  ["unpin-confirmation", "Unpin confirmation", "general", "", "ask before thread pinned section", "", ""],
  ["archive-confirmation", "Archive confirmation", "general", "", "ask before thread second click inline action", "", ""],
  ["delete-confirmation", "Delete confirmation", "general", "", "ask before thread chat history", "", ""],
  ["quit-confirmation", "Quit shortcut", "general", "", "confirmation desktop app exit direct hold double click press twice", "", "desktop"],
  ["text-generation-model", "Text generation model", "general", "", "generated thread titles source control content default provider", "project-defaults", ""],
  ["diagnostics", "Diagnostics", "general", "", "logs traces processes resource history failures spans cpu memory", "", ""],
  ["open-source-licenses", "Open source licenses", "general", "", "", "", ""],
  ["legacy-plan-mode", "Plan mode (legacy)", "general", "", "build plan composer old", "", ""],
  ["legacy-context-window-indicator", "Context window indicator (legacy)", "general", "", "composer meter usage tokens circle old", "", ""],
  ["legacy-sidebar", "Sidebar (legacy)", "general", "", "project thread tree old flat list", "", ""],
  ["keybindings", "Keybindings", "keybindings", "", "keyboard shortcuts hotkeys commands bindings json", "", ""],
  ["snap-shot-enabled", "SnapShots", "snap-shot", "", "window capture screenshot", "", ""],
  ["snap-shot-accessibility", "Include app text", "snap-shot", "snap-shot-enabled", "capture accessibility data text UI structure elements privacy omit agent context", "", ""],
  ["snap-shot-shortcut", "Capture shortcut", "snap-shot", "snap-shot-enabled", "", "", ""],
  ["snap-shot-sound", "Capture sound", "snap-shot", "snap-shot-enabled", "", "", ""],
  ["snap-shot-flash", "Capture flash", "snap-shot", "snap-shot-enabled", "", "", ""],
  ["snap-shot-animations", "Capture animations", "snap-shot", "snap-shot-enabled", "", "", ""],
  ["providers", "Providers", "providers", "", "agents cli codex claude cursor grok opencode antigravity google sign in sign out install subscription instances authentication api key models configuration binary path config directory endpoint arguments environment variables display name accent color custom favorite hidden auto compact", "", ""],
  ["usage-providers", "Usage providers", "providers", "", "usage sources CLIProxyAPI CLI proxy hub quota subscription limits management key add remove", "", "providerSettings"],
  ["cursor-keychain-usage", "Cursor account usage", "providers", "", "cursor macOS keychain usage tokens cost limits permission", "", "providerSettings,macProviderSettings"],
  ["provider-health-check-interval", "Health check interval", "providers", "", "refresh availability versions auth state models background probes seconds off", "", "providerSettings"],
  ["agent-browser-access", "Agent browser access", "integrations", "", "allow disable enable open drive preview tools sessions project override", "project-defaults", ""],
  ["device-hosts", "Device hosts", "integrations", "", "ssh remote simulator emulator ios android mac mini identity key connection", "", ""],
  ["agent-device-access", "Agent device access", "integrations", "devices", "allow simulator emulator ios android drive tools sessions", "", ""],
  ["device-hub", "Device hub", "integrations", "devices", "simulator emulator ios android install start", "", ""],
  ["device-platform-support", "Simulator support", "integrations", "devices", "xcode android studio sdk avd runtime", "", ""],
  ["browser-profiles", "Browser profiles", "integrations", "browser", "", "", ""],
  ["browser-default-profile", "Default browser profile", "integrations", "browser-profiles", "", "", ""],
  ["browser-default-viewport", "Default browser viewport", "integrations", "", "preview size width height device desktop mobile rotate", "", ""],
  ["browser-default-zoom", "Default browser zoom", "integrations", "", "preview page scale tabs percent", "", ""],
  ["browser-default-appearance", "Default browser appearance", "integrations", "", "preview color scheme light dark system os", "", ""],
  ["browser-recording-frame-rate", "Browser recording frame rate", "integrations", "", "", "", ""],
  ["browser-recording-key-presses", "Show key presses in recordings", "integrations", "", "browser preview keyboard shortcuts keystrokes overlay capture", "", ""],
  ["browser-recording-mouse-presses", "Show mouse presses in recordings", "integrations", "", "browser preview clicks buttons drag overlay capture", "", ""],
  ["browser-link-target", "Open links in", "integrations", "", "links default browser in-app browser external open", "", ""],
  ["browser-auto-show-floating-preview", "Auto-show floating preview", "integrations", "", "agent opens browser device simulator pop into view hide", "", ""],
  ["automatic-pull", "Automatically pull", "source-control", "", "auto pull default branch current checkout fast forward upstream", "project-defaults", ""],
  ["pull-request-merge-method", "Default merge method", "source-control", "", "pull request merge squash rebase last selected", "project-defaults", ""],
  ["source-control", "Source control", "source-control", "", "version control git github gitlab forgejo gitea tea codeberg bitbucket azure devops hosting integrations credentials scan server environment", "environment-defaults", ""],
  ["git-fetch-interval", "Git fetch interval", "source-control", "", "automatic remote branch refresh background credentials security keys seconds off", "environment-defaults", "environment"],
  ["worktree-branch-naming", "Worktree branch naming", "source-control", "", "static semantic prefix custom prompt instructions feat fix refactor chore", "project-defaults", "environment"],
  ["bitbucket-credentials", "Bitbucket credentials", "source-control", "", "bitbucket atlassian access token api token email credentials sign in", "environment-defaults", "environment"],
  ["source-control-writing-style", "Source control writing style", "source-control", "", "repository conventions conventional commits custom instructions change descriptions request titles", "", "environment"],
  ["follow-change-request-templates", "Follow change request templates", "source-control", "", "repository pr pull request description structure", "", "environment"],
  ["source-control-writer-model", "Source control writer model", "source-control", "", "override generated commit change request pr titles descriptions branch bookmark", "project-defaults", "environment"],
  ["project-actions", "Actions", "projects", "", "commands scripts setup run dev server checkout worktree t3.json import", "", ""],
  ["environment-icon", "Environment icon", "connections", "connections-environment", "machine glyph sidebar mac mini studio laptop desktop server cloud vm", "", "localBackend"],
  ["local-environment", "Local environment", "connections", "connections-environment", "turn off on disable enable local server agents remote only restart", "", "desktop"],
  ["network-access", "Network access", "connections", "connections-environment", "expose backend remote pairing local machine interfaces host restart", "", "localBackend"],
  ["tailscale-https", "Tailscale HTTPS", "connections", "connections-environment", "serve magicdns endpoint remote secure network", "", "desktop,localBackend"],
  ["wsl-backend", "WSL backend", "connections", "", "windows subsystem linux distro second server projects stop windows backend restart", "", "desktop,windows,localBackend,wsl"],
  ["t3-connect", "T3 Connect", "connections", "connections-environment", "managed tunnel cloud other devices remote", "", "desktop,cloud,localEnvironment"],
  ["publish-agent-activity", "Publish agent activity", "connections", "connections-environment", "mobile push notifications live activities cloud tunnel", "", "cloud,localEnvironment"],
  ["connections-environment", "This machine", "connections", "", "connections server backend local remote access administrative permissions scope pairing links qr code authorized clients sessions revoke endpoint", "", ""],
  ["remote-environments", "Environments", "connections", "", "add pair backend host code ssh config agent tunnel saved t3 connect", "", ""],
  ["load-balancing", "Load balancing", "connections", "", "automatic machine environment resources cpu memory capacity preference weight shared projects", "", ""],
  ["github-routing", "GitHub sharing", "connections", "", "pull request trusted environments shared credentials permissions read actions", "", ""],
  ["archive", "Archived threads", "archived", "", "restore reopen deleted history projects", "", ""],
];
