//! Rust's side of the data seam, derived from the plan's types as
//! `typescript` derives TypeScript's (LLP 1054.000 R4): a data crate builds
//! its records from these structs, so a field's position is the compiler's,
//! not a comment's. Two same-typed fields swapped in a hand-written
//! `Value::record` pass the runner's shape check; a named field cannot swap.

use exact_plan::{Plan, TypeKind, TypesId};
use std::collections::BTreeMap;
use std::fmt::Write;

const KEYWORDS: &[&str] = &[
    "as", "async", "await", "box", "break", "const", "continue", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut",
    "pub", "ref", "return", "static", "struct", "trait", "true", "try", "type", "unsafe", "use",
    "where", "while", "yield",
];

/// `camelCase` or `kebab-case` as a snake_case field name, escaped where it
/// is a Rust keyword.
fn field_name(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i != 0 && !out.ends_with('_') {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else if c.is_ascii_alphanumeric() {
            out.push(c);
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    match out.as_str() {
        "self" | "super" | "crate" | "Self" => format!("{out}_"),
        k if KEYWORDS.contains(&k) => format!("r#{out}"),
        _ => out,
    }
}

/// Generate Rust structs for every named record in a compiled Contract,
/// each with `From<&T> for Value` and `TryFrom<&Value> for T` in the
/// declared field order. A build-time artifact: a data crate's `build.rs`
/// writes it into `OUT_DIR` and `include!`s it; it is never committed.
pub fn rust(plan: &Plan) -> Result<String, String> {
    Plan::decode(&plan.encode()).map_err(|e| format!("invalid plan: {e:?}"))?;
    // One struct per shape name; the plan may hold a shape more than once.
    let mut named: BTreeMap<String, usize> = BTreeMap::new();
    for (i, row) in plan.types.iter().enumerate() {
        let name = plan.str(row.name);
        if row.kind == TypeKind::Record && !name.is_empty() {
            named.entry(name.to_string()).or_insert(i);
        }
    }
    let ty = |i: TypesId| -> Result<String, String> { rust_type(plan, i) };
    let mut out = String::from(
        "// @generated by `contract rust` from Contract shapes; do not edit.\n\
         // Declaration order is the record's field order.\n\n\
         /// A value the data seam carries, with its conversion both ways.\n\
         pub trait ContractValue: Sized {\n    \
             fn to_value(&self) -> exact_runner::Value;\n    \
             fn from_value(value: &exact_runner::Value) -> Option<Self>;\n\
         }\n\
         impl ContractValue for f64 {\n    \
             fn to_value(&self) -> exact_runner::Value { exact_runner::Value::Number(*self) }\n    \
             fn from_value(value: &exact_runner::Value) -> Option<Self> { value.as_number() }\n\
         }\n\
         impl ContractValue for bool {\n    \
             fn to_value(&self) -> exact_runner::Value { exact_runner::Value::Bool(*self) }\n    \
             fn from_value(value: &exact_runner::Value) -> Option<Self> { value.as_bool() }\n\
         }\n\
         impl ContractValue for String {\n    \
             fn to_value(&self) -> exact_runner::Value { exact_runner::Value::str(self) }\n    \
             fn from_value(value: &exact_runner::Value) -> Option<Self> { value.as_str().map(str::to_string) }\n\
         }\n\
         impl ContractValue for () {\n    \
             fn to_value(&self) -> exact_runner::Value { exact_runner::Value::Unit }\n    \
             fn from_value(value: &exact_runner::Value) -> Option<Self> { matches!(value, exact_runner::Value::Unit).then_some(()) }\n\
         }\n\
         impl<T: ContractValue> ContractValue for Option<T> {\n    \
             fn to_value(&self) -> exact_runner::Value {\n        \
                 self.as_ref().map_or(exact_runner::Value::Option(None), |v| exact_runner::Value::some(v.to_value()))\n    \
             }\n    \
             fn from_value(value: &exact_runner::Value) -> Option<Self> {\n        \
                 match value {\n            \
                     exact_runner::Value::Option(None) => Some(None),\n            \
                     exact_runner::Value::Option(Some(v)) => T::from_value(v).map(Some),\n            \
                     _ => None,\n        \
                 }\n    \
             }\n\
         }\n\
         impl<T: ContractValue> ContractValue for Vec<T> {\n    \
             fn to_value(&self) -> exact_runner::Value { exact_runner::Value::list(self.iter().map(T::to_value).collect()) }\n    \
             fn from_value(value: &exact_runner::Value) -> Option<Self> {\n        \
                 match value {\n            \
                     exact_runner::Value::List(items) => items.iter().map(T::from_value).collect(),\n            \
                     _ => None,\n        \
                 }\n    \
             }\n\
         }\n",
    );
    for (name, &i) in &named {
        let row = &plan.types[i];
        let fields = &plan.fields
            [row.fields.start as usize..row.fields.start as usize + row.fields.len as usize];
        writeln!(out, "\n/// Contract `shape {name}`.").unwrap();
        writeln!(
            out,
            "#[derive(Debug, Clone, PartialEq, Default)]\npub struct {name} {{"
        )
        .unwrap();
        for f in fields {
            writeln!(
                out,
                "    pub {}: {},",
                field_name(plan.str(f.name)),
                ty(f.ty)?
            )
            .unwrap();
        }
        out.push_str("}\n");
        writeln!(out, "impl ContractValue for {name} {{").unwrap();
        out.push_str("    fn to_value(&self) -> exact_runner::Value {\n        exact_runner::Value::record(vec![\n");
        for f in fields {
            writeln!(
                out,
                "            self.{}.to_value(),",
                field_name(plan.str(f.name))
            )
            .unwrap();
        }
        out.push_str("        ])\n    }\n");
        out.push_str("    fn from_value(value: &exact_runner::Value) -> Option<Self> {\n");
        writeln!(
            out,
            "        let exact_runner::Value::Record(fields) = value else {{ return None }};\n        \
             if fields.len() != {} {{ return None; }}\n        Some(Self {{",
            fields.len()
        )
        .unwrap();
        for (k, f) in fields.iter().enumerate() {
            writeln!(
                out,
                "            {}: ContractValue::from_value(&fields[{k}])?,",
                field_name(plan.str(f.name))
            )
            .unwrap();
        }
        out.push_str("        })\n    }\n}\n");
        writeln!(
            out,
            "impl From<&{name}> for exact_runner::Value {{\n    \
                 fn from(v: &{name}) -> Self {{ v.to_value() }}\n\
             }}\n\
             impl TryFrom<&exact_runner::Value> for {name} {{\n    \
                 type Error = &'static str;\n    \
                 fn try_from(v: &exact_runner::Value) -> Result<Self, Self::Error> {{\n        \
                     Self::from_value(v).ok_or(\"not a {name}\")\n    \
                 }}\n\
             }}"
        )
        .unwrap();
    }
    Ok(out)
}

fn rust_type(plan: &Plan, i: TypesId) -> Result<String, String> {
    let row = plan
        .types
        .get(i.0 as usize)
        .ok_or_else(|| format!("type {} out of range", i.0))?;
    let elem = || {
        row.elem
            .ok_or_else(|| format!("type {} has no element", i.0))
    };
    Ok(match row.kind {
        TypeKind::Number => "f64".into(),
        TypeKind::Bool => "bool".into(),
        TypeKind::String => "String".into(),
        TypeKind::Unit => "()".into(),
        TypeKind::Option => format!("Option<{}>", rust_type(plan, elem()?)?),
        TypeKind::List => format!("Vec<{}>", rust_type(plan, elem()?)?),
        TypeKind::Record => {
            let name = plan.str(row.name);
            if name.is_empty() {
                return Err(format!("type {} is a record with no shape name", i.0));
            }
            name.to_string()
        }
    })
}
