//! Shader reflection for an app's GPU crate (LLP 1009 D5): every `.wgsl`
//! under a directory is parsed and validated by naga at build, and what the
//! shader declares — its bindings, the layout of every host-shareable struct,
//! its vertex inputs, its entry points — is generated as Rust the surface
//! compiles against. The WGSL is the one declaration authority: the Rust side
//! never restates an offset, a stride, a binding number, or an entry point's
//! name, and a shader edit that moves one is a build error at the use site,
//! never a silently wrong picture. (Reflection over hand-written declarations
//! is vgpu's idea; the shape is `kernel/build.rs`'s.)
//!
//! For `aurora.wgsl` the generated `pub mod aurora` holds `NAME`,
//! `INTERFACE_DIGEST` (below), and `module()` — the `ShaderModuleDescriptor`
//! over the text the app's shader registry holds for that name at run time
//! (LLP 1030 D8: the WGSL travels as an asset, never as a string in the
//! binary; `exact_gpu::shaders`) — `entry::VS`, `entry::FS`; one
//! `BindGroupLayoutEntry` const per binding (`U`, `CHILDREN`, …) — its
//! visibility the stages that use it, a float texture filterable exactly
//! when some entry point samples it with a sampler — and a `GROUP_n`
//! descriptor per group; a Rust struct per host-shareable struct
//! (`Uniforms { time, width, height, seed }` with `SIZE`, `write`, `bytes`;
//! a trailing runtime-sized array becomes `<NAME>_OFFSET`/`<NAME>_STRIDE`
//! beside the fixed members); and, for a vertex entry point with
//! `@location` inputs, a struct with `INPUTS` (what the shader declares:
//! locations and formats) and `LAYOUT` — one per-vertex buffer, tightly
//! interleaved in declaration order, which is this generator's convention,
//! not the shader's. Every generated name is checked against every other;
//! a collision or an unsupported shape is a build error, never a comment.
//!
//! Generated code names `::exact_gpu::wgpu`, so it compiles wherever
//! `exact-gpu` does — natively and on the web alike.
//!
//! **The interface digest** (LLP 1030 D8) is a digest over what the surface's
//! Rust binds against and nothing else: the entry points with their stages
//! and workgroup sizes, every binding's group, number, type, and visibility,
//! every host-shareable struct's layout, the vertex inputs, the fragment
//! outputs, and the `override` constants — never the source text. A shader
//! edit that leaves it unchanged is an asset change the running binary can
//! take; one that moves it is a binary change, because the Rust that binds
//! the old layout is compiled in. [`interface_digest`] computes the same
//! number over a candidate at run time, so a registry can refuse a shader
//! whose interface is not the one the binary was built against. The
//! generated file ends with `SHADERS`, every shader's name and digest, which
//! the app's `Registry` carries.

#![deny(missing_docs)]

use naga::valid::{Capabilities, ModuleInfo, ValidationFlags, Validator};
use naga::{
    AddressSpace, ArraySize, Binding, GlobalVariable, Handle, ImageClass, ImageDimension, Module,
    Scalar, ScalarKind, ShaderStage, StorageAccess, Type, TypeInner, VectorSize,
};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// What [`generate`] produced: one Rust source, and the shaders it came from.
#[derive(Debug)]
pub struct Generated {
    /// The Rust: a `pub mod <stem>` per shader.
    pub rust: String,
    /// Every `.wgsl` read, for `cargo:rerun-if-changed`.
    pub sources: Vec<PathBuf>,
}

/// Reflect every `.wgsl` under `dir` (sorted by name) into one Rust source.
/// A shader that fails to parse or validate is an error naming the file,
/// line, and column; so is a file stem that is not a Rust identifier.
pub fn generate(dir: &Path) -> Result<Generated, String> {
    let mut sources: Vec<PathBuf> = Vec::new();
    for entry in std::fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))? {
        let path = entry.map_err(|e| format!("{}: {e}", dir.display()))?.path();
        if path.extension().is_some_and(|x| x == "wgsl") {
            sources.push(path);
        }
    }
    sources.sort();
    let mut rust = format!(
        "// @generated by exact-gpu-reflect from {}/*.wgsl — do not edit; edit the shader.\n",
        dir.display()
    );
    let mut table: Vec<(String, u64)> = Vec::new();
    for path in &sources {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        if !is_identifier(stem) {
            return Err(format!(
                "{}: the file stem must be a Rust identifier (a module is named after it)",
                path.display()
            ));
        }
        let source =
            std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
        let (module, digest) =
            reflect_with_digest(stem, &source).map_err(|e| format!("{}: {e}", path.display()))?;
        rust.push('\n');
        rust.push_str(&module);
        table.push((stem.to_string(), digest));
    }
    rust.push_str(
        "\n/// Every shader here, by name, with the interface digest it was reflected at: what the app's `Registry` carries so a registered shader can be checked against what the binary binds (LLP 1030 D8).\n",
    );
    rust.push_str("pub const SHADERS: &[(&str, u64)] = &[");
    for (i, (name, digest)) in table.iter().enumerate() {
        if i > 0 {
            rust.push_str(", ");
        }
        let _ = write!(rust, "({name:?}, {digest:#018x})");
    }
    rust.push_str("];\n");
    Ok(Generated { rust, sources })
}

/// The interface digest of a shader as the registry checks it at run time
/// (LLP 1030 D8): the same number `INTERFACE_DIGEST` was generated with,
/// over the validated interface and never the text. A shader that fails to
/// parse or validate is an error naming the line and column.
pub fn interface_digest(source: &str) -> Result<u64, String> {
    let module = naga::front::wgsl::parse_str(source).map_err(|e| e.emit_to_string(source))?;
    let info = Validator::new(ValidationFlags::all(), Capabilities::empty())
        .validate(&module)
        .map_err(|e| e.emit_to_string(source))?;
    let shader = Shader {
        name: "",
        module: &module,
        info: &info,
    };
    Ok(digest(&shader.canon()?))
}

/// A domain-separated SHA-256 of the canonical interface, its first eight
/// bytes as a little-endian `u64` (the shape `plan/build.rs` uses).
fn digest(canon: &str) -> u64 {
    use sha2::Digest as _;
    let mut h = sha2::Sha256::new();
    h.update(b"EXACT.GPU.SHADER.INTERFACE.SHA256.V1\0");
    h.update(canon.as_bytes());
    let out = h.finalize();
    u64::from_le_bytes(out[..8].try_into().expect("eight bytes"))
}

/// Reflect one shader into `pub mod <name> { … }`. Errors carry naga's
/// diagnostic with line and column, or name what is not supported.
pub fn reflect(name: &str, source: &str) -> Result<String, String> {
    reflect_with_digest(name, source).map(|(rust, _)| rust)
}

/// [`reflect`], and the interface digest the module was generated with.
pub fn reflect_with_digest(name: &str, source: &str) -> Result<(String, u64), String> {
    let module = naga::front::wgsl::parse_str(source).map_err(|e| e.emit_to_string(source))?;
    let info = Validator::new(ValidationFlags::all(), Capabilities::empty())
        .validate(&module)
        .map_err(|e| e.emit_to_string(source))?;
    let shader = Shader {
        name,
        module: &module,
        info: &info,
    };
    let digest = digest(&shader.canon()?);
    Ok((shader.emit(digest)?, digest))
}

/// Every identifier a generated module declares, so a collision is a build
/// error naming both sides rather than a rustc error in `OUT_DIR`.
struct Names(BTreeMap<String, String>);

impl Names {
    /// A module's registry, seeded with the names the module keeps.
    fn module() -> Names {
        let mut names = Names(BTreeMap::new());
        for (name, what) in [
            ("NAME", "the shader's name"),
            ("INTERFACE_DIGEST", "the interface digest"),
            ("module", "the shader module function"),
            ("entry", "the entry-point module"),
            ("wgpu", "the wgpu import"),
        ] {
            names.0.insert(name.into(), what.into());
        }
        names
    }

    fn claim(&mut self, name: &str, what: &str) -> Result<(), String> {
        if let Some(prev) = self.0.insert(name.to_string(), what.to_string()) {
            return Err(format!("`{name}` ({what}) collides with `{name}` ({prev})"));
        }
        Ok(())
    }
}

struct Shader<'a> {
    name: &'a str,
    module: &'a Module,
    info: &'a ModuleInfo,
}

/// A field of a generated struct: its WGSL name, type, and byte offset.
struct Field {
    name: String,
    ty: Handle<Type>,
    offset: u32,
}

/// A byte offset in generated code: a literal, or a loop variable plus one.
#[derive(Clone)]
enum Off {
    Lit(u32),
    Var(String, u32),
}

impl Off {
    fn plus(&self, d: u32) -> Off {
        match self {
            Off::Lit(a) => Off::Lit(a + d),
            Off::Var(v, a) => Off::Var(v.clone(), a + d),
        }
    }

    /// `start..start + len`.
    fn range(&self, len: u32) -> String {
        match self {
            Off::Lit(a) => format!("{a}..{}", a + len),
            Off::Var(v, 0) => format!("{v}..{v} + {len}"),
            Off::Var(v, a) => format!("{v} + {a}..{v} + {}", a + len),
        }
    }

    /// `start + term`, without a `0 +`.
    fn plus_term(&self, term: &str) -> String {
        match self {
            Off::Lit(0) => term.to_string(),
            Off::Lit(a) => format!("{a} + {term}"),
            Off::Var(v, 0) => format!("{v} + {term}"),
            Off::Var(v, a) => format!("{v} + {a} + {term}"),
        }
    }
}

impl Shader<'_> {
    fn ty(&self, h: Handle<Type>) -> &TypeInner {
        &self.module.types[h].inner
    }

    fn size(&self, h: Handle<Type>) -> u32 {
        self.ty(h).size(self.module.to_ctx())
    }

    fn emit(&self, digest: u64) -> Result<String, String> {
        let name = self.name;
        let mut out = String::new();
        let _ = writeln!(
            out,
            "/// `{name}.wgsl`, reflected at build: its entry points, bindings, and layouts; its text is the registry's (LLP 1030 D8)."
        );
        let _ = writeln!(out, "#[allow(non_camel_case_types, non_snake_case)]");
        let _ = writeln!(out, "pub mod {name} {{");
        let _ = writeln!(out, "    use ::exact_gpu::wgpu;");
        let _ = writeln!(
            out,
            "    /// The shader's name: the registry's key, and the asset file's stem."
        );
        let _ = writeln!(out, "    pub const NAME: &str = {name:?};");
        let _ = writeln!(out, "    /// The interface digest this Rust binds against (LLP 1030 D8): entry points, bindings, layouts, inputs, outputs, overrides — never the text.");
        let _ = writeln!(out, "    pub const INTERFACE_DIGEST: u64 = {digest:#018x};");
        let _ = writeln!(out, "    /// The shader module over the text the registry holds for `{name}` (`exact_gpu::shaders::set_shader`); empty until one is registered, which the module refuses to create a surface before.");
        let _ = writeln!(
            out,
            "    pub fn module() -> wgpu::ShaderModuleDescriptor<'static> {{ ::exact_gpu::shaders::shader_module(NAME) }}"
        );
        let mut names = Names::module();
        self.emit_entries(&mut out)?;
        self.emit_bindings(&mut out, &mut names)?;
        self.emit_structs(&mut out, &mut names)?;
        self.emit_vertex_inputs(&mut out, &mut names)?;
        out.push_str("}\n");
        Ok(out)
    }

    /// The canonical interface (LLP 1030 D8): one line per fact the surface's
    /// Rust depends on, in a fixed order — what [`digest`] hashes. Doc text,
    /// the shader's name, and the source are not in it, so a generator change
    /// that only rewords a comment, or a color edit, leaves it alone.
    fn canon(&self) -> Result<String, String> {
        let mut c = String::new();
        for ep in &self.module.entry_points {
            let _ = writeln!(
                c,
                "entry {} {} workgroup={:?}",
                stage_name(ep.stage)?,
                ep.name,
                ep.workgroup_size
            );
            // The fragment outputs: locations and types the target formats
            // must match; a struct result's members carry the locations.
            if let Some(result) = &ep.function.result {
                match &result.binding {
                    Some(Binding::Location { location, .. }) => {
                        let _ = writeln!(c, "  out {location} {}", self.wgsl_name(result.ty));
                    }
                    Some(Binding::BuiltIn(b)) => {
                        let _ = writeln!(c, "  out builtin {b:?}");
                    }
                    None => {
                        if let TypeInner::Struct { members, .. } = self.ty(result.ty) {
                            for m in members {
                                match &m.binding {
                                    Some(Binding::Location { location, .. }) => {
                                        let _ = writeln!(
                                            c,
                                            "  out {location} {}",
                                            self.wgsl_name(m.ty)
                                        );
                                    }
                                    Some(Binding::BuiltIn(b)) => {
                                        let _ = writeln!(c, "  out builtin {b:?}");
                                    }
                                    None => {}
                                }
                            }
                        }
                    }
                }
            }
            // The vertex inputs, as declared: locations and types.
            if matches!(ep.stage, ShaderStage::Vertex) {
                for arg in &ep.function.arguments {
                    match &arg.binding {
                        Some(Binding::Location { location, .. }) => {
                            let _ = writeln!(c, "  in {location} {}", self.wgsl_name(arg.ty));
                        }
                        Some(Binding::BuiltIn(_)) => {}
                        None => {
                            if let TypeInner::Struct { members, .. } = self.ty(arg.ty) {
                                for m in members {
                                    if let Some(Binding::Location { location, .. }) = &m.binding {
                                        let _ =
                                            writeln!(c, "  in {location} {}", self.wgsl_name(m.ty));
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        let mut bindings: Vec<(u32, u32, String)> = Vec::new();
        for (handle, gv) in self.module.global_variables.iter() {
            let Some(rb) = gv.binding else { continue };
            let (visibility, _) = self.visibility(handle)?;
            let (ty, _) = self.binding_type(handle, gv)?;
            bindings.push((rb.group, rb.binding, format!("{visibility} {ty}")));
        }
        bindings.sort();
        for (group, binding, rest) in bindings {
            let _ = writeln!(c, "bind {group} {binding} {rest}");
        }
        // Every host-shareable struct reachable from a buffer binding, in
        // the order the generator emits them, with its layout.
        let mut order: Vec<Handle<Type>> = Vec::new();
        for (_, gv) in self.module.global_variables.iter() {
            if gv.binding.is_none()
                || !matches!(
                    gv.space,
                    AddressSpace::Uniform | AddressSpace::Storage { .. }
                )
            {
                continue;
            }
            self.collect_structs(gv.ty, &mut order);
        }
        for h in order {
            let TypeInner::Struct { members, span } = self.ty(h) else {
                continue;
            };
            let _ = write!(
                c,
                "struct {} span={span}",
                self.module.types[h].name.as_deref().unwrap_or("?")
            );
            for m in members {
                let _ = write!(
                    c,
                    " {}:{}@{}",
                    m.name.as_deref().unwrap_or("?"),
                    self.wgsl_name(m.ty),
                    m.offset
                );
            }
            c.push('\n');
        }
        for (_, o) in self.module.overrides.iter() {
            let _ = writeln!(
                c,
                "override {} id={:?} {}",
                o.name.as_deref().unwrap_or("?"),
                o.id,
                self.wgsl_name(o.ty)
            );
        }
        Ok(c)
    }

    fn emit_entries(&self, out: &mut String) -> Result<(), String> {
        if self.module.entry_points.is_empty() {
            return Ok(());
        }
        out.push_str("    /// The entry points, by name.\n    pub mod entry {\n");
        let mut names = Names(BTreeMap::new());
        for ep in &self.module.entry_points {
            let stage = stage_name(ep.stage)?;
            let konst = upper_snake(&ep.name);
            names.claim(&konst, &format!("entry point `{}`", ep.name))?;
            let _ = writeln!(out, "        /// `@{stage} fn {}`.", ep.name);
            let _ = writeln!(out, "        pub const {konst}: &str = {:?};", ep.name);
            if matches!(ep.stage, ShaderStage::Compute) {
                names.claim(
                    &format!("{konst}_WORKGROUP_SIZE"),
                    &format!("the workgroup size of `{}`", ep.name),
                )?;
                let [x, y, z] = ep.workgroup_size;
                let _ = writeln!(out, "        /// The `@workgroup_size` of `{}`.", ep.name);
                let _ = writeln!(
                    out,
                    "        pub const {konst}_WORKGROUP_SIZE: [u32; 3] = [{x}, {y}, {z}];"
                );
            }
        }
        out.push_str("    }\n");
        Ok(())
    }

    fn emit_bindings(&self, out: &mut String, names: &mut Names) -> Result<(), String> {
        let mut groups: BTreeMap<u32, Vec<(u32, String)>> = BTreeMap::new();
        for (handle, gv) in self.module.global_variables.iter() {
            let Some(rb) = gv.binding else { continue };
            let wgsl = gv
                .name
                .clone()
                .ok_or_else(|| "an unnamed resource binding".to_string())?;
            let konst = upper_snake(&wgsl);
            names.claim(&konst, &format!("binding `{wgsl}`"))?;
            let (visibility, stages) = self.visibility(handle)?;
            let (ty, decl) = self.binding_type(handle, gv)?;
            let _ = writeln!(
                out,
                "    /// `@group({}) @binding({}) {decl}` — {stages}.",
                rb.group, rb.binding
            );
            let _ = writeln!(
                out,
                "    pub const {konst}: wgpu::BindGroupLayoutEntry = wgpu::BindGroupLayoutEntry {{ binding: {}, visibility: {visibility}, ty: {ty}, count: None }};",
                rb.binding
            );
            groups
                .entry(rb.group)
                .or_default()
                .push((rb.binding, konst));
        }
        for (group, mut entries) in groups {
            names.claim(&format!("GROUP_{group}"), &format!("bind group {group}"))?;
            entries.sort();
            let list: Vec<&str> = entries.iter().map(|(_, k)| k.as_str()).collect();
            let _ = writeln!(
                out,
                "    /// Bind group {group}'s layout: {}.",
                list.iter()
                    .map(|k| format!("`{k}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            let _ = writeln!(
                out,
                "    pub const GROUP_{group}: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {{ label: Some(\"{} group {group}\"), entries: &[{}] }};",
                self.name,
                list.join(", ")
            );
        }
        Ok(())
    }

    /// The stages that use a global, as a `ShaderStages` expression and prose.
    fn visibility(&self, handle: Handle<GlobalVariable>) -> Result<(String, String), String> {
        let order = ["VERTEX", "FRAGMENT", "COMPUTE"];
        let mut stages: Vec<&str> = Vec::new();
        for (i, ep) in self.module.entry_points.iter().enumerate() {
            if self.info.get_entry_point(i)[handle].is_empty() {
                continue;
            }
            let s = match ep.stage {
                ShaderStage::Vertex => "VERTEX",
                ShaderStage::Fragment => "FRAGMENT",
                ShaderStage::Compute => "COMPUTE",
                other => return Err(format!("the {other:?} stage is not supported")),
            };
            if !stages.contains(&s) {
                stages.push(s);
            }
        }
        stages.sort_by_key(|s| order.iter().position(|o| o == s));
        if stages.is_empty() {
            return Ok((
                "wgpu::ShaderStages::NONE".into(),
                "used by no entry point".into(),
            ));
        }
        let expr = stages
            .iter()
            .map(|s| format!("wgpu::ShaderStages::{s}"))
            .reduce(|a, b| format!("{a}.union({b})"))
            .unwrap_or_default();
        let prose = stages
            .iter()
            .map(|s| s.to_lowercase())
            .collect::<Vec<_>>()
            .join(" and ");
        Ok((expr, prose))
    }

    /// Whether any entry point samples a texture with a sampler (naga's
    /// per-entry-point `sampling_set`, transitive through calls). A float
    /// texture is filterable exactly then; one only ever read with
    /// `textureLoad` is unfilterable-float, which any float format binds.
    fn sampled(&self, handle: Handle<GlobalVariable>) -> bool {
        (0..self.module.entry_points.len()).any(|i| {
            self.info
                .get_entry_point(i)
                .sampling_set
                .iter()
                .any(|k| k.image == handle)
        })
    }

    /// A binding's `BindingType` expression and its WGSL declaration, for the doc.
    fn binding_type(
        &self,
        handle: Handle<GlobalVariable>,
        gv: &GlobalVariable,
    ) -> Result<(String, String), String> {
        let name = gv.name.as_deref().unwrap_or("?");
        let wgsl_ty = self.wgsl_name(gv.ty);
        match gv.space {
            AddressSpace::Uniform => Ok((
                format!(
                    "wgpu::BindingType::Buffer {{ ty: wgpu::BufferBindingType::Uniform, has_dynamic_offset: false, min_binding_size: ::core::num::NonZeroU64::new({}) }}",
                    self.size(gv.ty)
                ),
                format!("var<uniform> {name}: {wgsl_ty}"),
            )),
            AddressSpace::Storage { access } => {
                let read_only = !access.contains(StorageAccess::STORE);
                Ok((
                    format!(
                        "wgpu::BindingType::Buffer {{ ty: wgpu::BufferBindingType::Storage {{ read_only: {read_only} }}, has_dynamic_offset: false, min_binding_size: ::core::num::NonZeroU64::new({}) }}",
                        self.size(gv.ty)
                    ),
                    format!(
                        "var<storage, {}> {name}: {wgsl_ty}",
                        if read_only { "read" } else { "read_write" }
                    ),
                ))
            }
            AddressSpace::Handle => match self.ty(gv.ty) {
                TypeInner::Sampler { comparison } => Ok((
                    format!(
                        "wgpu::BindingType::Sampler(wgpu::SamplerBindingType::{})",
                        if *comparison { "Comparison" } else { "Filtering" }
                    ),
                    format!("var {name}: {wgsl_ty}"),
                )),
                TypeInner::Image {
                    dim,
                    arrayed,
                    class,
                } => {
                    let view = view_dimension(*dim, *arrayed)
                        .map_err(|e| format!("`{name}`: {e}"))?;
                    let mut note = "";
                    let ty = match class {
                        ImageClass::Sampled { kind, multi } => {
                            let sample = match kind {
                                ScalarKind::Float => {
                                    let filterable = self.sampled(handle) && !*multi;
                                    note = if filterable {
                                        " (sampled with a sampler: filterable)"
                                    } else {
                                        " (never sampled with a sampler: unfilterable-float)"
                                    };
                                    format!(
                                        "wgpu::TextureSampleType::Float {{ filterable: {filterable} }}"
                                    )
                                }
                                ScalarKind::Sint => "wgpu::TextureSampleType::Sint".into(),
                                ScalarKind::Uint => "wgpu::TextureSampleType::Uint".into(),
                                other => {
                                    return Err(format!(
                                        "`{name}`: a texture of {other:?} is not supported"
                                    ))
                                }
                            };
                            format!("wgpu::BindingType::Texture {{ sample_type: {sample}, view_dimension: wgpu::TextureViewDimension::{view}, multisampled: {multi} }}")
                        }
                        ImageClass::Depth { multi } => format!(
                            "wgpu::BindingType::Texture {{ sample_type: wgpu::TextureSampleType::Depth, view_dimension: wgpu::TextureViewDimension::{view}, multisampled: {multi} }}"
                        ),
                        ImageClass::Storage { format, access } => {
                            let a = if access.contains(StorageAccess::ATOMIC) {
                                "Atomic"
                            } else {
                                match (
                                    access.contains(StorageAccess::LOAD),
                                    access.contains(StorageAccess::STORE),
                                ) {
                                    (true, true) => "ReadWrite",
                                    (true, false) => "ReadOnly",
                                    _ => "WriteOnly",
                                }
                            };
                            format!(
                                "wgpu::BindingType::StorageTexture {{ access: wgpu::StorageTextureAccess::{a}, format: wgpu::TextureFormat::{}, view_dimension: wgpu::TextureViewDimension::{view} }}",
                                storage_format(*format)
                            )
                        }
                        ImageClass::External => {
                            return Err(format!(
                                "`{name}`: external textures are not supported"
                            ))
                        }
                    };
                    Ok((ty, format!("var {name}: {wgsl_ty}{note}")))
                }
                _ => Err(format!(
                    "`{name}`: a binding of `{wgsl_ty}` is not supported"
                )),
            },
            other => Err(format!(
                "`{name}`: address space {other:?} cannot carry a binding"
            )),
        }
    }

    fn emit_structs(&self, out: &mut String, names: &mut Names) -> Result<(), String> {
        // Host-shareable structs reachable from buffer bindings, nested first.
        let mut order: Vec<Handle<Type>> = Vec::new();
        for (_, gv) in self.module.global_variables.iter() {
            if gv.binding.is_none()
                || !matches!(
                    gv.space,
                    AddressSpace::Uniform | AddressSpace::Storage { .. }
                )
            {
                continue;
            }
            self.collect_structs(gv.ty, &mut order);
        }
        let mut generated: Vec<(Handle<Type>, bool)> = Vec::new();
        for h in order {
            let TypeInner::Struct { members, span } = self.ty(h) else {
                continue;
            };
            let name = self.module.types[h]
                .name
                .clone()
                .ok_or_else(|| "an unnamed struct in a buffer".to_string())?;
            type_name(&name)?;
            names.claim(&name, &format!("struct `{name}`"))?;
            let mut fields: Vec<Field> = members
                .iter()
                .map(|m| Field {
                    name: m.name.clone().unwrap_or_default(),
                    ty: m.ty,
                    offset: m.offset,
                })
                .collect();
            let mut size = *span;
            let mut extra = String::new();
            let mut doc =
                format!("`struct {name}` as the shader reads it: {span} bytes, at its offsets.");
            // A trailing runtime-sized array (WGSL allows one, last, in
            // storage): the fixed members are the struct; the array follows
            // at its offset, its elements at their stride.
            let trailing = fields.last().and_then(|last| match self.ty(last.ty) {
                TypeInner::Array {
                    base,
                    size: ArraySize::Dynamic,
                    stride,
                } => Some((
                    last.name.clone(),
                    last.offset,
                    *stride,
                    self.wgsl_name(*base),
                )),
                _ => None,
            });
            if let Some((array, offset, stride, elem)) = trailing {
                let konst = upper_snake(&array);
                let _ = writeln!(
                    extra,
                    "        /// `{array}: array<{elem}>` follows the fixed members at this offset, `{konst}_STRIDE` bytes per element.",
                );
                let _ = writeln!(extra, "        pub const {konst}_OFFSET: usize = {offset};");
                let _ = writeln!(extra, "        /// The stride of `{array}`'s elements.");
                let _ = writeln!(extra, "        pub const {konst}_STRIDE: usize = {stride};");
                size = offset;
                doc = format!(
                    "`struct {name}` as the shader reads it: {size} bytes of fixed members, then `{array}: array<{elem}>` at `{konst}_OFFSET` (runtime-sized; `SIZE`, `write`, and `bytes` cover the fixed members)."
                );
                fields.pop();
            }
            let (text, default) = self
                .emit_struct(&name, &doc, &fields, size, &generated, &extra)
                .map_err(|e| format!("struct `{name}`: {e}"))?;
            out.push_str(&text);
            generated.push((h, default));
        }
        Ok(())
    }

    fn collect_structs(&self, h: Handle<Type>, order: &mut Vec<Handle<Type>>) {
        match self.ty(h) {
            TypeInner::Struct { members, .. } => {
                for m in members {
                    self.collect_structs(m.ty, order);
                }
                if !order.contains(&h) {
                    order.push(h);
                }
            }
            TypeInner::Array { base, .. } => self.collect_structs(*base, order),
            _ => {}
        }
    }

    /// One generated struct with `SIZE`, `write`, and `bytes` (and `extra`
    /// items in its `impl`): the text, and whether it could derive `Default`.
    fn emit_struct(
        &self,
        name: &str,
        doc: &str,
        fields: &[Field],
        size: u32,
        generated: &[(Handle<Type>, bool)],
        extra: &str,
    ) -> Result<(String, bool), String> {
        let mut body = String::new();
        let mut writes = String::new();
        let mut default = true;
        for f in fields {
            let (rust, d) = self
                .rust_type(f.ty, generated)
                .map_err(|e| format!("member `{}` — {e}", f.name))?;
            default &= d;
            let field = ident(&f.name)?;
            let _ = writeln!(
                body,
                "        /// `{}: {}` at {}.",
                f.name,
                self.wgsl_name(f.ty),
                f.offset
            );
            let _ = writeln!(body, "        pub {field}: {rust},");
            self.write_value(
                &mut writes,
                f.ty,
                &format!("self.{field}"),
                &Off::Lit(f.offset),
                0,
                "            ",
            )?;
        }
        let mut out = String::new();
        let _ = writeln!(out, "    /// {doc}");
        let _ = writeln!(
            out,
            "    #[derive(Debug, Clone, Copy, PartialEq{})]",
            if default { ", Default" } else { "" }
        );
        let _ = writeln!(out, "    pub struct {name} {{");
        out.push_str(&body);
        out.push_str("    }\n");
        let _ = writeln!(out, "    impl {name} {{");
        out.push_str("        /// The size in a buffer, padded.\n");
        let _ = writeln!(out, "        pub const SIZE: usize = {size};");
        out.push_str(extra);
        out.push_str(
            "        /// Encode at the shader's offsets into the first `SIZE` bytes of `out`, padding zeroed.\n",
        );
        out.push_str("        pub fn write(&self, out: &mut [u8]) {\n");
        out.push_str("            out[..Self::SIZE].fill(0);\n");
        out.push_str(&writes);
        out.push_str("        }\n");
        out.push_str("        /// The encoded bytes.\n");
        let _ = writeln!(
            out,
            "        pub fn bytes(&self) -> [u8; {size}] {{\n            let mut out = [0u8; {size}];\n            self.write(&mut out);\n            out\n        }}"
        );
        out.push_str("    }\n");
        Ok((out, default))
    }

    /// The Rust type for a host-shareable type, and whether it is `Default`.
    fn rust_type(
        &self,
        h: Handle<Type>,
        generated: &[(Handle<Type>, bool)],
    ) -> Result<(String, bool), String> {
        match self.ty(h) {
            TypeInner::Scalar(s) | TypeInner::Atomic(s) => Ok((scalar_rust(*s)?.into(), true)),
            TypeInner::Vector { size, scalar } => Ok((
                format!("[{}; {}]", scalar_rust(*scalar)?, *size as u32),
                true,
            )),
            TypeInner::Matrix {
                columns,
                rows,
                scalar,
            } => Ok((
                format!(
                    "[[{}; {}]; {}]",
                    scalar_rust(*scalar)?,
                    *rows as u32,
                    *columns as u32
                ),
                true,
            )),
            TypeInner::Array {
                base,
                size: ArraySize::Constant(n),
                ..
            } => {
                let (b, d) = self.rust_type(*base, generated)?;
                Ok((format!("[{b}; {}]", n.get()), d && n.get() <= 32))
            }
            TypeInner::Array { .. } => Err("a runtime-sized array has no fixed layout".into()),
            TypeInner::Struct { .. } => {
                let name = self.module.types[h]
                    .name
                    .clone()
                    .ok_or_else(|| "an unnamed struct".to_string())?;
                match generated.iter().find(|(g, _)| *g == h) {
                    Some((_, d)) => Ok((name, *d)),
                    None => Err(format!("`{name}` is not generated")),
                }
            }
            _ => Err(format!("`{}` is not host-shareable", self.wgsl_name(h))),
        }
    }

    /// The statements that encode `expr` (of type `h`) at `off` into `out`.
    fn write_value(
        &self,
        out: &mut String,
        h: Handle<Type>,
        expr: &str,
        off: &Off,
        depth: usize,
        indent: &str,
    ) -> Result<(), String> {
        match self.ty(h) {
            TypeInner::Scalar(s) | TypeInner::Atomic(s) => {
                let w = u32::from(s.width);
                let _ = writeln!(
                    out,
                    "{indent}out[{}].copy_from_slice(&{expr}.to_le_bytes());",
                    off.range(w)
                );
            }
            TypeInner::Vector { size, scalar } => {
                let w = u32::from(scalar.width);
                for i in 0..(*size as u32) {
                    let _ = writeln!(
                        out,
                        "{indent}out[{}].copy_from_slice(&{expr}[{i}].to_le_bytes());",
                        off.plus(i * w).range(w)
                    );
                }
            }
            TypeInner::Matrix {
                columns,
                rows,
                scalar,
            } => {
                let w = u32::from(scalar.width);
                let stride = column_stride(*rows, w);
                for c in 0..(*columns as u32) {
                    for r in 0..(*rows as u32) {
                        let _ = writeln!(
                            out,
                            "{indent}out[{}].copy_from_slice(&{expr}[{c}][{r}].to_le_bytes());",
                            off.plus(c * stride + r * w).range(w)
                        );
                    }
                }
            }
            TypeInner::Array {
                base,
                size: ArraySize::Constant(_),
                stride,
            } => {
                let _ = writeln!(
                    out,
                    "{indent}for (i{depth}, e{depth}) in {expr}.iter().enumerate() {{"
                );
                let _ = writeln!(
                    out,
                    "{indent}    let o{depth} = {};",
                    off.plus_term(&format!("i{depth} * {stride}"))
                );
                self.write_value(
                    out,
                    *base,
                    &format!("e{depth}"),
                    &Off::Var(format!("o{depth}"), 0),
                    depth + 1,
                    &format!("{indent}    "),
                )?;
                let _ = writeln!(out, "{indent}}}");
            }
            TypeInner::Struct { span, .. } => {
                let _ = writeln!(out, "{indent}{expr}.write(&mut out[{}]);", off.range(*span));
            }
            _ => {
                return Err(format!(
                    "`{}` cannot be written to a buffer",
                    self.wgsl_name(h)
                ))
            }
        }
        Ok(())
    }

    /// A vertex entry point's `@location` inputs: `INPUTS` as the shader
    /// declares them, and one interleaved buffer (`LAYOUT`) by convention.
    fn emit_vertex_inputs(&self, out: &mut String, names: &mut Names) -> Result<(), String> {
        // Each generated struct: its name, the WGSL struct it came from (if
        // one), and the entry point.
        let mut emitted: Vec<(String, Option<Handle<Type>>, String)> = Vec::new();
        for ep in &self.module.entry_points {
            if !matches!(ep.stage, ShaderStage::Vertex) {
                continue;
            }
            let mut inputs: Vec<(String, Handle<Type>, u32)> = Vec::new();
            let (mut structs, mut bare, mut struct_handle) = (0, 0, None);
            for arg in &ep.function.arguments {
                match &arg.binding {
                    Some(Binding::Location { location, .. }) => {
                        bare += 1;
                        let name = arg
                            .name
                            .clone()
                            .unwrap_or_else(|| format!("location{location}"));
                        inputs.push((name, arg.ty, *location));
                    }
                    Some(Binding::BuiltIn(_)) => {}
                    None => {
                        if let TypeInner::Struct { members, .. } = self.ty(arg.ty) {
                            structs += 1;
                            struct_handle = Some(arg.ty);
                            for m in members {
                                if let Some(Binding::Location { location, .. }) = m.binding {
                                    inputs.push((
                                        m.name.clone().unwrap_or_default(),
                                        m.ty,
                                        location,
                                    ));
                                }
                            }
                        }
                    }
                }
            }
            if inputs.is_empty() {
                continue;
            }
            let (name, source) = match (structs, bare, struct_handle) {
                (1, 0, Some(h)) => (
                    self.module.types[h]
                        .name
                        .clone()
                        .ok_or_else(|| format!("`{}`: an unnamed vertex input struct", ep.name))?,
                    Some(h),
                ),
                _ => (format!("{}Input", upper_camel(&ep.name)), None),
            };
            if let Some((_, prev_source, prev_ep)) = emitted.iter().find(|(n, _, _)| *n == name) {
                if source.is_some() && *prev_source == source {
                    // The same WGSL struct: one Rust struct serves both.
                    continue;
                }
                return Err(format!(
                    "the vertex inputs of `{}` would be `{name}`, already generated for `{prev_ep}`",
                    ep.name
                ));
            }
            type_name(&name)?;
            names.claim(&name, &format!("the vertex inputs of `{}`", ep.name))?;
            let mut fields = Vec::new();
            let mut attrs = Vec::new();
            let mut declared = Vec::new();
            let mut offset = 0u32;
            for (fname, ty, location) in &inputs {
                let (format, size) = vertex_format(self.ty(*ty))
                    .map_err(|e| format!("`{}` input `{fname}`: {e}", ep.name))?;
                declared.push(format!("({location}, wgpu::VertexFormat::{format})"));
                attrs.push(format!(
                    "wgpu::VertexAttribute {{ format: wgpu::VertexFormat::{format}, offset: {offset}, shader_location: {location} }}"
                ));
                fields.push(Field {
                    name: fname.clone(),
                    ty: *ty,
                    offset,
                });
                offset += size;
            }
            let extra = format!(
                "        /// What the shader declares: each `@location` and its format, in declaration order.\n        pub const INPUTS: &[(u32, wgpu::VertexFormat)] = &[{}];\n        /// One per-vertex buffer holding `INPUTS`, tightly interleaved in declaration order, {offset} bytes per vertex — this generator's convention, not the shader's (WGSL declares locations and types only); another buffer policy is another const beside this one.\n        pub const LAYOUT: wgpu::VertexBufferLayout<'static> = wgpu::VertexBufferLayout {{ array_stride: {offset}, step_mode: wgpu::VertexStepMode::Vertex, attributes: &[{}] }};\n",
                declared.join(", "),
                attrs.join(", ")
            );
            let doc = format!(
                "The vertex inputs of `{}`, one field per `@location`, as `LAYOUT` packs them: {offset} bytes in declaration order (the convention; `INPUTS` is the declaration).",
                ep.name
            );
            let (text, _) = self.emit_struct(&name, &doc, &fields, offset, &[], &extra)?;
            out.push_str(&text);
            emitted.push((name, source, ep.name.clone()));
        }
        Ok(())
    }

    /// The type as WGSL spells it, for docs (best effort).
    fn wgsl_name(&self, h: Handle<Type>) -> String {
        let t = &self.module.types[h];
        match &t.inner {
            TypeInner::Struct { .. } => t.name.clone().unwrap_or_else(|| "struct".into()),
            TypeInner::Scalar(s) => scalar_wgsl(*s),
            TypeInner::Atomic(s) => format!("atomic<{}>", scalar_wgsl(*s)),
            TypeInner::Vector { size, scalar } => {
                format!("vec{}<{}>", *size as u32, scalar_wgsl(*scalar))
            }
            TypeInner::Matrix {
                columns,
                rows,
                scalar,
            } => format!(
                "mat{}x{}<{}>",
                *columns as u32,
                *rows as u32,
                scalar_wgsl(*scalar)
            ),
            TypeInner::Array { base, size, .. } => match size {
                ArraySize::Constant(n) => {
                    format!("array<{}, {}>", self.wgsl_name(*base), n.get())
                }
                _ => format!("array<{}>", self.wgsl_name(*base)),
            },
            TypeInner::Image {
                dim,
                arrayed,
                class,
            } => {
                let d = match dim {
                    ImageDimension::D1 => "1d",
                    ImageDimension::D2 => "2d",
                    ImageDimension::D3 => "3d",
                    ImageDimension::Cube => "cube",
                };
                let a = if *arrayed { "_array" } else { "" };
                match class {
                    ImageClass::Sampled { kind, multi } => format!(
                        "texture_{}{d}{a}<{}>",
                        if *multi { "multisampled_" } else { "" },
                        scalar_wgsl(Scalar {
                            kind: *kind,
                            width: 4
                        })
                    ),
                    ImageClass::Depth { multi } => format!(
                        "texture_depth_{}{d}{a}",
                        if *multi { "multisampled_" } else { "" }
                    ),
                    ImageClass::Storage { format, access } => format!(
                        "texture_storage_{d}{a}<{}, {}>",
                        storage_format(*format).to_lowercase(),
                        match (
                            access.contains(StorageAccess::LOAD),
                            access.contains(StorageAccess::STORE)
                        ) {
                            (true, true) => "read_write",
                            (true, false) => "read",
                            _ => "write",
                        }
                    ),
                    ImageClass::External => "texture_external".into(),
                }
            }
            TypeInner::Sampler { comparison } => if *comparison {
                "sampler_comparison"
            } else {
                "sampler"
            }
            .into(),
            _ => "?".into(),
        }
    }
}

fn stage_name(stage: ShaderStage) -> Result<&'static str, String> {
    Ok(match stage {
        ShaderStage::Vertex => "vertex",
        ShaderStage::Fragment => "fragment",
        ShaderStage::Compute => "compute",
        other => return Err(format!("the {other:?} stage is not supported")),
    })
}

fn view_dimension(dim: ImageDimension, arrayed: bool) -> Result<&'static str, String> {
    Ok(match (dim, arrayed) {
        (ImageDimension::D1, false) => "D1",
        (ImageDimension::D2, false) => "D2",
        (ImageDimension::D2, true) => "D2Array",
        (ImageDimension::D3, false) => "D3",
        (ImageDimension::Cube, false) => "Cube",
        (ImageDimension::Cube, true) => "CubeArray",
        (d, true) => return Err(format!("an arrayed {d:?} texture is not a WebGPU view")),
    })
}

/// A matrix column's stride: columns are aligned like vectors (`vec3` to 16).
fn column_stride(rows: VectorSize, width: u32) -> u32 {
    let align = match rows {
        VectorSize::Bi => 2,
        VectorSize::Tri | VectorSize::Quad => 4,
    };
    align * width
}

fn scalar_rust(s: Scalar) -> Result<&'static str, String> {
    Ok(match (s.kind, s.width) {
        (ScalarKind::Float, 4) => "f32",
        (ScalarKind::Sint, 4) => "i32",
        (ScalarKind::Uint, 4) => "u32",
        (ScalarKind::Float, 8) => "f64",
        (ScalarKind::Sint, 8) => "i64",
        (ScalarKind::Uint, 8) => "u64",
        _ => return Err(format!("`{}` has no Rust type here", scalar_wgsl(s))),
    })
}

fn scalar_wgsl(s: Scalar) -> String {
    match s.kind {
        ScalarKind::Float => format!("f{}", u32::from(s.width) * 8),
        ScalarKind::Sint => format!("i{}", u32::from(s.width) * 8),
        ScalarKind::Uint => format!("u{}", u32::from(s.width) * 8),
        ScalarKind::Bool => "bool".into(),
        ScalarKind::AbstractInt => "abstract-int".into(),
        ScalarKind::AbstractFloat => "abstract-float".into(),
    }
}

/// A vertex input's `VertexFormat` and byte size: 32-bit scalars and vectors.
fn vertex_format(inner: &TypeInner) -> Result<(String, u32), String> {
    let (scalar, n) = match inner {
        TypeInner::Scalar(s) => (*s, 1),
        TypeInner::Vector { size, scalar } => (*scalar, *size as u32),
        _ => return Err("only scalars and vectors can be vertex inputs".into()),
    };
    let base = match (scalar.kind, scalar.width) {
        (ScalarKind::Float, 4) => "Float32",
        (ScalarKind::Sint, 4) => "Sint32",
        (ScalarKind::Uint, 4) => "Uint32",
        _ => {
            return Err(format!(
                "`{}` vertex inputs are not supported (32-bit only)",
                scalar_wgsl(scalar)
            ))
        }
    };
    let name = if n == 1 {
        base.to_string()
    } else {
        format!("{base}x{n}")
    };
    Ok((name, 4 * n))
}

/// naga's storage format as wgpu's `TextureFormat` variant: the names agree
/// today; an exhaustive match is what says so when a variant appears.
macro_rules! storage_formats {
    ($($v:ident),* $(,)?) => {
        fn storage_format(f: naga::StorageFormat) -> &'static str {
            match f {
                $(naga::StorageFormat::$v => stringify!($v),)*
            }
        }
    };
}

storage_formats!(
    R8Unorm,
    R8Snorm,
    R8Uint,
    R8Sint,
    R16Uint,
    R16Sint,
    R16Float,
    Rg8Unorm,
    Rg8Snorm,
    Rg8Uint,
    Rg8Sint,
    R32Uint,
    R32Sint,
    R32Float,
    Rg16Uint,
    Rg16Sint,
    Rg16Float,
    Rgba8Unorm,
    Rgba8Snorm,
    Rgba8Uint,
    Rgba8Sint,
    Bgra8Unorm,
    Rgb10a2Uint,
    Rgb10a2Unorm,
    Rg11b10Ufloat,
    R64Uint,
    Rg32Uint,
    Rg32Sint,
    Rg32Float,
    Rgba16Uint,
    Rgba16Sint,
    Rgba16Float,
    Rgba32Uint,
    Rgba32Sint,
    Rgba32Float,
    R16Unorm,
    R16Snorm,
    Rg16Unorm,
    Rg16Snorm,
    Rgba16Unorm,
    Rgba16Snorm,
);

/// A struct name must be a Rust identifier that is not a keyword (a raw
/// type name is not worth reading; rename it in the WGSL).
fn type_name(name: &str) -> Result<(), String> {
    if !is_identifier(name) {
        return Err(format!(
            "`{name}` cannot name a Rust struct; rename it in the WGSL"
        ));
    }
    Ok(())
}

const KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl",
    "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "static", "struct", "super", "trait", "true", "try", "type", "typeof", "unsafe",
    "unsized", "use", "virtual", "where", "while", "yield",
];

fn is_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    matches!(chars.next(), Some(c) if c == '_' || c.is_ascii_alphabetic())
        && chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
        && !KEYWORDS.contains(&s)
        && !matches!(s, "self" | "Self" | "crate" | "super")
}

/// A field name as Rust: raw when it is a keyword.
fn ident(name: &str) -> Result<String, String> {
    if matches!(name, "self" | "Self" | "crate" | "super") || name.is_empty() {
        return Err(format!("`{name}` cannot be a Rust field"));
    }
    if KEYWORDS.contains(&name) {
        return Ok(format!("r#{name}"));
    }
    if !is_identifier(name) {
        return Err(format!("`{name}` is not a Rust identifier"));
    }
    Ok(name.to_string())
}

/// `childrenSampler` / `children_sampler` → `CHILDREN_SAMPLER`.
fn upper_snake(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::new();
    for (i, c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase()
            && i > 0
            && (chars[i - 1].is_ascii_lowercase() || chars[i - 1].is_ascii_digit())
        {
            out.push('_');
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

/// `vs_main` → `VsMain`.
fn upper_camel(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
