//! Shader reflection for an app's GPU crate (LLP 1009 D5): every `.wgsl`
//! under a directory is parsed and validated by naga at build, and what the
//! shader declares — its bindings, the layout of every host-shareable struct,
//! its vertex inputs, its entry points — is generated as Rust the surface
//! compiles against. The WGSL is the one declaration authority: the Rust side
//! never restates an offset, a stride, a binding number, or an entry point's
//! name, and a shader edit that moves one is a build error at the use site,
//! never a silently wrong picture. (Reflection over hand-written declarations
//! is vgpu's idea; the shape is `kernel/build.rs`'s.)
//!
//! For `aurora.wgsl` the generated `pub mod aurora` holds `SOURCE` and
//! `MODULE` (the `ShaderModuleDescriptor`); `entry::VS`, `entry::FS`; one
//! `BindGroupLayoutEntry` const per binding (`U`, `CHILDREN`, …) and a
//! `GROUP_n` descriptor per group; a Rust struct per host-shareable struct
//! (`Uniforms { time, width, height, seed }` with `SIZE`, `write`, `bytes`);
//! and, for a vertex entry point with `@location` inputs, a struct with a
//! `LAYOUT` — one buffer, interleaved in declaration order.
//!
//! Generated code names `::exact_gpu::wgpu`, so it compiles wherever
//! `exact-gpu` does — natively and on the web alike.

#![deny(missing_docs)]

use naga::valid::{Capabilities, ModuleInfo, ValidationFlags, Validator};
use naga::{
    AddressSpace, ArraySize, Binding, GlobalVariable, Handle, ImageClass, ImageDimension, Module,
    Scalar, ScalarKind, ShaderStage, StorageAccess, Type, TypeInner, VectorSize,
};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// What [`generate`] produced: one Rust source, and the shaders it came from.
pub struct Generated {
    /// The Rust: a `pub mod <stem>` per shader.
    pub rust: String,
    /// Every `.wgsl` read, for `cargo:rerun-if-changed`.
    pub sources: Vec<PathBuf>,
}

/// Reflect every `.wgsl` under `dir` (sorted by name) into one Rust source.
/// A shader that fails to parse or validate is an error naming the file,
/// line, and column; so is a file stem that is not a Rust identifier.
pub fn generate(dir: &Path) -> Result<Generated, String> {
    let mut sources: Vec<PathBuf> = std::fs::read_dir(dir)
        .map_err(|e| format!("{}: {e}", dir.display()))?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "wgsl"))
        .collect();
    sources.sort();
    let mut rust = format!(
        "// @generated by exact-gpu-reflect from {}/*.wgsl — do not edit; edit the shader.\n",
        dir.display()
    );
    for path in &sources {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        if !is_identifier(stem) {
            return Err(format!(
                "{}: the file stem must be a Rust identifier (a module is named after it)",
                path.display()
            ));
        }
        let source =
            std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
        let module = reflect(stem, &source).map_err(|e| format!("{}: {e}", path.display()))?;
        rust.push('\n');
        rust.push_str(&module);
    }
    Ok(Generated { rust, sources })
}

/// Reflect one shader into `pub mod <name> { … }`. Errors carry naga's
/// diagnostic with line and column, or name what is not supported.
pub fn reflect(name: &str, source: &str) -> Result<String, String> {
    let module = naga::front::wgsl::parse_str(source).map_err(|e| e.emit_to_string(source))?;
    let info = Validator::new(ValidationFlags::all(), Capabilities::empty())
        .validate(&module)
        .map_err(|e| e.emit_to_string(source))?;
    Shader {
        name,
        module: &module,
        info: &info,
    }
    .emit(source)
}

/// Names the generated module keeps for itself.
const RESERVED: &[&str] = &["SOURCE", "MODULE"];

struct Shader<'a> {
    name: &'a str,
    module: &'a Module,
    info: &'a ModuleInfo,
}

/// A field of a generated struct: its WGSL name, type, and byte offset.
struct Field {
    name: String,
    ty: Handle<Type>,
    offset: u32,
}

/// A byte offset in generated code: a literal, or a loop variable plus one.
#[derive(Clone)]
enum Off {
    Lit(u32),
    Var(String, u32),
}

impl Off {
    fn plus(&self, d: u32) -> Off {
        match self {
            Off::Lit(a) => Off::Lit(a + d),
            Off::Var(v, a) => Off::Var(v.clone(), a + d),
        }
    }

    /// `start..start + len`.
    fn range(&self, len: u32) -> String {
        match self {
            Off::Lit(a) => format!("{a}..{}", a + len),
            Off::Var(v, 0) => format!("{v}..{v} + {len}"),
            Off::Var(v, a) => format!("{v} + {a}..{v} + {}", a + len),
        }
    }

    /// `start + term`, without a `0 +`.
    fn plus_term(&self, term: &str) -> String {
        match self {
            Off::Lit(0) => term.to_string(),
            Off::Lit(a) => format!("{a} + {term}"),
            Off::Var(v, 0) => format!("{v} + {term}"),
            Off::Var(v, a) => format!("{v} + {a} + {term}"),
        }
    }
}

impl Shader<'_> {
    fn ty(&self, h: Handle<Type>) -> &TypeInner {
        &self.module.types[h].inner
    }

    fn size(&self, h: Handle<Type>) -> u32 {
        self.ty(h).size(self.module.to_ctx())
    }

    fn emit(&self, source: &str) -> Result<String, String> {
        let name = self.name;
        let mut out = String::new();
        let _ = writeln!(
            out,
            "/// `{name}.wgsl`, reflected at build: its source, entry points, bindings, and layouts."
        );
        let _ = writeln!(out, "#[allow(non_camel_case_types, non_snake_case)]");
        let _ = writeln!(out, "pub mod {name} {{");
        let _ = writeln!(out, "    use ::exact_gpu::wgpu;");
        let _ = writeln!(out, "    /// The WGSL, validated at build.");
        let _ = writeln!(out, "    pub const SOURCE: &str = {source:?};");
        let _ = writeln!(out, "    /// The shader module, labelled `{name}`.");
        let _ = writeln!(
            out,
            "    pub const MODULE: wgpu::ShaderModuleDescriptor<'static> = wgpu::ShaderModuleDescriptor {{ label: Some({name:?}), source: wgpu::ShaderSource::Wgsl(::std::borrow::Cow::Borrowed(SOURCE)) }};"
        );
        self.emit_entries(&mut out)?;
        self.emit_bindings(&mut out)?;
        self.emit_structs(&mut out)?;
        self.emit_vertex_inputs(&mut out)?;
        out.push_str("}\n");
        Ok(out)
    }

    fn emit_entries(&self, out: &mut String) -> Result<(), String> {
        if self.module.entry_points.is_empty() {
            return Ok(());
        }
        out.push_str("    /// The entry points, by name.\n    pub mod entry {\n");
        let mut seen: BTreeMap<String, String> = BTreeMap::new();
        for ep in &self.module.entry_points {
            let stage = stage_name(ep.stage)?;
            let konst = upper_snake(&ep.name);
            if let Some(prev) = seen.insert(konst.clone(), ep.name.clone()) {
                return Err(format!(
                    "entry points `{prev}` and `{}` both become `entry::{konst}`",
                    ep.name
                ));
            }
            let _ = writeln!(out, "        /// `@{stage} fn {}`.", ep.name);
            let _ = writeln!(out, "        pub const {konst}: &str = {:?};", ep.name);
            if matches!(ep.stage, ShaderStage::Compute) {
                let [x, y, z] = ep.workgroup_size;
                let _ = writeln!(out, "        /// The `@workgroup_size` of `{}`.", ep.name);
                let _ = writeln!(
                    out,
                    "        pub const {konst}_WORKGROUP_SIZE: [u32; 3] = [{x}, {y}, {z}];"
                );
            }
        }
        out.push_str("    }\n");
        Ok(())
    }

    fn emit_bindings(&self, out: &mut String) -> Result<(), String> {
        let mut groups: BTreeMap<u32, Vec<(u32, String)>> = BTreeMap::new();
        let mut names: BTreeMap<String, String> = BTreeMap::new();
        for (handle, gv) in self.module.global_variables.iter() {
            let Some(rb) = gv.binding else { continue };
            let wgsl = gv
                .name
                .clone()
                .ok_or_else(|| "an unnamed resource binding".to_string())?;
            let konst = upper_snake(&wgsl);
            if RESERVED.contains(&konst.as_str()) || konst.starts_with("GROUP_") {
                return Err(format!(
                    "binding `{wgsl}` would be `{konst}`, a name the generated module keeps"
                ));
            }
            if let Some(prev) = names.insert(konst.clone(), wgsl.clone()) {
                return Err(format!(
                    "bindings `{prev}` and `{wgsl}` both become `{konst}`"
                ));
            }
            let (visibility, stages) = self.visibility(handle)?;
            let (ty, decl) = self.binding_type(gv)?;
            let _ = writeln!(
                out,
                "    /// `@group({}) @binding({}) {decl}` — {stages}.",
                rb.group, rb.binding
            );
            let _ = writeln!(
                out,
                "    pub const {konst}: wgpu::BindGroupLayoutEntry = wgpu::BindGroupLayoutEntry {{ binding: {}, visibility: {visibility}, ty: {ty}, count: None }};",
                rb.binding
            );
            groups
                .entry(rb.group)
                .or_default()
                .push((rb.binding, konst));
        }
        for (group, mut entries) in groups {
            entries.sort();
            let list: Vec<&str> = entries.iter().map(|(_, k)| k.as_str()).collect();
            let _ = writeln!(
                out,
                "    /// Bind group {group}'s layout: {}.",
                list.iter()
                    .map(|k| format!("`{k}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            let _ = writeln!(
                out,
                "    pub const GROUP_{group}: wgpu::BindGroupLayoutDescriptor<'static> = wgpu::BindGroupLayoutDescriptor {{ label: Some(\"{} group {group}\"), entries: &[{}] }};",
                self.name,
                list.join(", ")
            );
        }
        Ok(())
    }

    /// The stages that use a global, as a `ShaderStages` expression and prose.
    fn visibility(&self, handle: Handle<GlobalVariable>) -> Result<(String, String), String> {
        let order = ["VERTEX", "FRAGMENT", "COMPUTE"];
        let mut stages: Vec<&str> = Vec::new();
        for (i, ep) in self.module.entry_points.iter().enumerate() {
            if self.info.get_entry_point(i)[handle].is_empty() {
                continue;
            }
            let s = match ep.stage {
                ShaderStage::Vertex => "VERTEX",
                ShaderStage::Fragment => "FRAGMENT",
                ShaderStage::Compute => "COMPUTE",
                other => return Err(format!("the {other:?} stage is not supported")),
            };
            if !stages.contains(&s) {
                stages.push(s);
            }
        }
        stages.sort_by_key(|s| order.iter().position(|o| o == s));
        if stages.is_empty() {
            return Ok((
                "wgpu::ShaderStages::NONE".into(),
                "used by no entry point".into(),
            ));
        }
        let expr = stages
            .iter()
            .map(|s| format!("wgpu::ShaderStages::{s}"))
            .reduce(|a, b| format!("{a}.union({b})"))
            .unwrap_or_default();
        let prose = stages
            .iter()
            .map(|s| s.to_lowercase())
            .collect::<Vec<_>>()
            .join(" and ");
        Ok((expr, prose))
    }

    /// A binding's `BindingType` expression and its WGSL declaration, for the doc.
    fn binding_type(&self, gv: &GlobalVariable) -> Result<(String, String), String> {
        let name = gv.name.as_deref().unwrap_or("?");
        let wgsl_ty = self.wgsl_name(gv.ty);
        match gv.space {
            AddressSpace::Uniform => Ok((
                format!(
                    "wgpu::BindingType::Buffer {{ ty: wgpu::BufferBindingType::Uniform, has_dynamic_offset: false, min_binding_size: ::core::num::NonZeroU64::new({}) }}",
                    self.size(gv.ty)
                ),
                format!("var<uniform> {name}: {wgsl_ty}"),
            )),
            AddressSpace::Storage { access } => {
                let read_only = !access.contains(StorageAccess::STORE);
                Ok((
                    format!(
                        "wgpu::BindingType::Buffer {{ ty: wgpu::BufferBindingType::Storage {{ read_only: {read_only} }}, has_dynamic_offset: false, min_binding_size: ::core::num::NonZeroU64::new({}) }}",
                        self.size(gv.ty)
                    ),
                    format!(
                        "var<storage, {}> {name}: {wgsl_ty}",
                        if read_only { "read" } else { "read_write" }
                    ),
                ))
            }
            AddressSpace::Handle => match self.ty(gv.ty) {
                TypeInner::Sampler { comparison } => Ok((
                    format!(
                        "wgpu::BindingType::Sampler(wgpu::SamplerBindingType::{})",
                        if *comparison { "Comparison" } else { "Filtering" }
                    ),
                    format!("var {name}: {wgsl_ty}"),
                )),
                TypeInner::Image {
                    dim,
                    arrayed,
                    class,
                } => {
                    let view = view_dimension(*dim, *arrayed)
                        .map_err(|e| format!("`{name}`: {e}"))?;
                    let ty = match class {
                        ImageClass::Sampled { kind, multi } => {
                            let sample = match kind {
                                ScalarKind::Float if *multi => {
                                    "wgpu::TextureSampleType::Float { filterable: false }"
                                }
                                ScalarKind::Float => {
                                    "wgpu::TextureSampleType::Float { filterable: true }"
                                }
                                ScalarKind::Sint => "wgpu::TextureSampleType::Sint",
                                ScalarKind::Uint => "wgpu::TextureSampleType::Uint",
                                other => {
                                    return Err(format!(
                                        "`{name}`: a texture of {other:?} is not supported"
                                    ))
                                }
                            };
                            format!("wgpu::BindingType::Texture {{ sample_type: {sample}, view_dimension: wgpu::TextureViewDimension::{view}, multisampled: {multi} }}")
                        }
                        ImageClass::Depth { multi } => format!(
                            "wgpu::BindingType::Texture {{ sample_type: wgpu::TextureSampleType::Depth, view_dimension: wgpu::TextureViewDimension::{view}, multisampled: {multi} }}"
                        ),
                        ImageClass::Storage { format, access } => {
                            let a = if access.contains(StorageAccess::ATOMIC) {
                                "Atomic"
                            } else {
                                match (
                                    access.contains(StorageAccess::LOAD),
                                    access.contains(StorageAccess::STORE),
                                ) {
                                    (true, true) => "ReadWrite",
                                    (true, false) => "ReadOnly",
                                    _ => "WriteOnly",
                                }
                            };
                            format!("wgpu::BindingType::StorageTexture {{ access: wgpu::StorageTextureAccess::{a}, format: wgpu::TextureFormat::{format:?}, view_dimension: wgpu::TextureViewDimension::{view} }}")
                        }
                        ImageClass::External => {
                            return Err(format!(
                                "`{name}`: external textures are not supported"
                            ))
                        }
                    };
                    Ok((ty, format!("var {name}: {wgsl_ty}")))
                }
                _ => Err(format!(
                    "`{name}`: a binding of `{wgsl_ty}` is not supported"
                )),
            },
            other => Err(format!(
                "`{name}`: address space {other:?} cannot carry a binding"
            )),
        }
    }

    fn emit_structs(&self, out: &mut String) -> Result<(), String> {
        // Host-shareable structs reachable from buffer bindings, nested first.
        let mut order: Vec<Handle<Type>> = Vec::new();
        for (_, gv) in self.module.global_variables.iter() {
            if gv.binding.is_none()
                || !matches!(
                    gv.space,
                    AddressSpace::Uniform | AddressSpace::Storage { .. }
                )
            {
                continue;
            }
            self.collect_structs(gv.ty, &mut order);
        }
        let mut generated: Vec<(Handle<Type>, bool)> = Vec::new();
        for h in order {
            let TypeInner::Struct { members, span } = self.ty(h) else {
                continue;
            };
            let name = self.module.types[h]
                .name
                .clone()
                .ok_or_else(|| "an unnamed struct in a buffer".to_string())?;
            let fields: Vec<Field> = members
                .iter()
                .map(|m| Field {
                    name: m.name.clone().unwrap_or_default(),
                    ty: m.ty,
                    offset: m.offset,
                })
                .collect();
            let doc =
                format!("`struct {name}` as the shader reads it: {span} bytes, at its offsets.");
            match self.emit_struct(&name, &doc, &fields, *span, &generated, None) {
                Ok((text, default)) => {
                    out.push_str(&text);
                    generated.push((h, default));
                }
                Err(reason) => {
                    let _ = writeln!(out, "    // `struct {name}` is not generated: {reason}.");
                }
            }
        }
        Ok(())
    }

    fn collect_structs(&self, h: Handle<Type>, order: &mut Vec<Handle<Type>>) {
        match self.ty(h) {
            TypeInner::Struct { members, .. } => {
                for m in members {
                    self.collect_structs(m.ty, order);
                }
                if !order.contains(&h) {
                    order.push(h);
                }
            }
            TypeInner::Array { base, .. } => self.collect_structs(*base, order),
            _ => {}
        }
    }

    /// One generated struct with `SIZE`, `write`, and `bytes` (and `LAYOUT`
    /// when given): the text, and whether it could derive `Default`.
    fn emit_struct(
        &self,
        name: &str,
        doc: &str,
        fields: &[Field],
        size: u32,
        generated: &[(Handle<Type>, bool)],
        layout: Option<&str>,
    ) -> Result<(String, bool), String> {
        let mut body = String::new();
        let mut writes = String::new();
        let mut default = true;
        for f in fields {
            let (rust, d) = self
                .rust_type(f.ty, generated)
                .map_err(|e| format!("member `{}` — {e}", f.name))?;
            default &= d;
            let field = ident(&f.name)?;
            let _ = writeln!(
                body,
                "        /// `{}: {}` at {}.",
                f.name,
                self.wgsl_name(f.ty),
                f.offset
            );
            let _ = writeln!(body, "        pub {field}: {rust},");
            self.write_value(
                &mut writes,
                f.ty,
                &format!("self.{field}"),
                &Off::Lit(f.offset),
                0,
                "            ",
            )?;
        }
        let mut out = String::new();
        let _ = writeln!(out, "    /// {doc}");
        let _ = writeln!(
            out,
            "    #[derive(Debug, Clone, Copy, PartialEq{})]",
            if default { ", Default" } else { "" }
        );
        let _ = writeln!(out, "    pub struct {name} {{");
        out.push_str(&body);
        out.push_str("    }\n");
        let _ = writeln!(out, "    impl {name} {{");
        out.push_str("        /// The size in a buffer, padded.\n");
        let _ = writeln!(out, "        pub const SIZE: usize = {size};");
        if let Some(l) = layout {
            out.push_str(l);
        }
        out.push_str(
            "        /// Encode at the shader's offsets into the first `SIZE` bytes of `out`.\n",
        );
        out.push_str("        pub fn write(&self, out: &mut [u8]) {\n");
        out.push_str(&writes);
        out.push_str("        }\n");
        out.push_str("        /// The encoded bytes.\n");
        let _ = writeln!(
            out,
            "        pub fn bytes(&self) -> [u8; {size}] {{\n            let mut out = [0u8; {size}];\n            self.write(&mut out);\n            out\n        }}"
        );
        out.push_str("    }\n");
        Ok((out, default))
    }

    /// The Rust type for a host-shareable type, and whether it is `Default`.
    fn rust_type(
        &self,
        h: Handle<Type>,
        generated: &[(Handle<Type>, bool)],
    ) -> Result<(String, bool), String> {
        match self.ty(h) {
            TypeInner::Scalar(s) | TypeInner::Atomic(s) => Ok((scalar_rust(*s)?.into(), true)),
            TypeInner::Vector { size, scalar } => Ok((
                format!("[{}; {}]", scalar_rust(*scalar)?, *size as u32),
                true,
            )),
            TypeInner::Matrix {
                columns,
                rows,
                scalar,
            } => Ok((
                format!(
                    "[[{}; {}]; {}]",
                    scalar_rust(*scalar)?,
                    *rows as u32,
                    *columns as u32
                ),
                true,
            )),
            TypeInner::Array {
                base,
                size: ArraySize::Constant(n),
                ..
            } => {
                let (b, d) = self.rust_type(*base, generated)?;
                Ok((format!("[{b}; {}]", n.get()), d && n.get() <= 32))
            }
            TypeInner::Array { .. } => Err("a runtime-sized array has no fixed layout".into()),
            TypeInner::Struct { .. } => {
                let name = self.module.types[h]
                    .name
                    .clone()
                    .ok_or_else(|| "an unnamed struct".to_string())?;
                match generated.iter().find(|(g, _)| *g == h) {
                    Some((_, d)) => Ok((name, *d)),
                    None => Err(format!("`{name}` is not generated")),
                }
            }
            _ => Err(format!("`{}` is not host-shareable", self.wgsl_name(h))),
        }
    }

    /// The statements that encode `expr` (of type `h`) at `off` into `out`.
    fn write_value(
        &self,
        out: &mut String,
        h: Handle<Type>,
        expr: &str,
        off: &Off,
        depth: usize,
        indent: &str,
    ) -> Result<(), String> {
        match self.ty(h) {
            TypeInner::Scalar(s) | TypeInner::Atomic(s) => {
                let w = u32::from(s.width);
                let _ = writeln!(
                    out,
                    "{indent}out[{}].copy_from_slice(&{expr}.to_le_bytes());",
                    off.range(w)
                );
            }
            TypeInner::Vector { size, scalar } => {
                let w = u32::from(scalar.width);
                for i in 0..(*size as u32) {
                    let _ = writeln!(
                        out,
                        "{indent}out[{}].copy_from_slice(&{expr}[{i}].to_le_bytes());",
                        off.plus(i * w).range(w)
                    );
                }
            }
            TypeInner::Matrix {
                columns,
                rows,
                scalar,
            } => {
                let w = u32::from(scalar.width);
                let stride = column_stride(*rows, w);
                for c in 0..(*columns as u32) {
                    for r in 0..(*rows as u32) {
                        let _ = writeln!(
                            out,
                            "{indent}out[{}].copy_from_slice(&{expr}[{c}][{r}].to_le_bytes());",
                            off.plus(c * stride + r * w).range(w)
                        );
                    }
                }
            }
            TypeInner::Array {
                base,
                size: ArraySize::Constant(_),
                stride,
            } => {
                let _ = writeln!(
                    out,
                    "{indent}for (i{depth}, e{depth}) in {expr}.iter().enumerate() {{"
                );
                let _ = writeln!(
                    out,
                    "{indent}    let o{depth} = {};",
                    off.plus_term(&format!("i{depth} * {stride}"))
                );
                self.write_value(
                    out,
                    *base,
                    &format!("e{depth}"),
                    &Off::Var(format!("o{depth}"), 0),
                    depth + 1,
                    &format!("{indent}    "),
                )?;
                let _ = writeln!(out, "{indent}}}");
            }
            TypeInner::Struct { span, .. } => {
                let _ = writeln!(out, "{indent}{expr}.write(&mut out[{}]);", off.range(*span));
            }
            _ => {
                return Err(format!(
                    "`{}` cannot be written to a buffer",
                    self.wgsl_name(h)
                ))
            }
        }
        Ok(())
    }

    /// A vertex entry point's `@location` inputs as one interleaved buffer.
    fn emit_vertex_inputs(&self, out: &mut String) -> Result<(), String> {
        let mut emitted: Vec<String> = Vec::new();
        for ep in &self.module.entry_points {
            if !matches!(ep.stage, ShaderStage::Vertex) {
                continue;
            }
            let mut inputs: Vec<(String, Handle<Type>, u32)> = Vec::new();
            let (mut structs, mut bare, mut struct_name) = (0, 0, None);
            for arg in &ep.function.arguments {
                match &arg.binding {
                    Some(Binding::Location { location, .. }) => {
                        bare += 1;
                        let name = arg
                            .name
                            .clone()
                            .unwrap_or_else(|| format!("location{location}"));
                        inputs.push((name, arg.ty, *location));
                    }
                    Some(Binding::BuiltIn(_)) => {}
                    None => {
                        if let TypeInner::Struct { members, .. } = self.ty(arg.ty) {
                            structs += 1;
                            struct_name = self.module.types[arg.ty].name.clone();
                            for m in members {
                                if let Some(Binding::Location { location, .. }) = m.binding {
                                    inputs.push((
                                        m.name.clone().unwrap_or_default(),
                                        m.ty,
                                        location,
                                    ));
                                }
                            }
                        }
                    }
                }
            }
            if inputs.is_empty() {
                continue;
            }
            let name = match (structs, bare, struct_name) {
                (1, 0, Some(n)) => n,
                _ => format!("{}Input", upper_camel(&ep.name)),
            };
            if emitted.contains(&name) {
                continue;
            }
            let mut fields = Vec::new();
            let mut attrs = Vec::new();
            let mut offset = 0u32;
            for (fname, ty, location) in &inputs {
                let (format, size) = vertex_format(self.ty(*ty))
                    .map_err(|e| format!("`{}` input `{fname}`: {e}", ep.name))?;
                attrs.push(format!(
                    "wgpu::VertexAttribute {{ format: wgpu::VertexFormat::{format}, offset: {offset}, shader_location: {location} }}"
                ));
                fields.push(Field {
                    name: fname.clone(),
                    ty: *ty,
                    offset,
                });
                offset += size;
            }
            let layout = format!(
                "        /// One vertex buffer: the `@location` inputs of `{}`, interleaved in declaration order, {offset} bytes per vertex.\n        pub const LAYOUT: wgpu::VertexBufferLayout<'static> = wgpu::VertexBufferLayout {{ array_stride: {offset}, step_mode: wgpu::VertexStepMode::Vertex, attributes: &[{}] }};\n",
                ep.name,
                attrs.join(", ")
            );
            let doc = format!(
                "The vertex inputs of `{}`, one per `@location`: {offset} bytes, packed in declaration order.",
                ep.name
            );
            let (text, _) = self.emit_struct(&name, &doc, &fields, offset, &[], Some(&layout))?;
            out.push_str(&text);
            emitted.push(name);
        }
        Ok(())
    }

    /// The type as WGSL spells it, for docs (best effort).
    fn wgsl_name(&self, h: Handle<Type>) -> String {
        let t = &self.module.types[h];
        match &t.inner {
            TypeInner::Struct { .. } => t.name.clone().unwrap_or_else(|| "struct".into()),
            TypeInner::Scalar(s) => scalar_wgsl(*s),
            TypeInner::Atomic(s) => format!("atomic<{}>", scalar_wgsl(*s)),
            TypeInner::Vector { size, scalar } => {
                format!("vec{}<{}>", *size as u32, scalar_wgsl(*scalar))
            }
            TypeInner::Matrix {
                columns,
                rows,
                scalar,
            } => format!(
                "mat{}x{}<{}>",
                *columns as u32,
                *rows as u32,
                scalar_wgsl(*scalar)
            ),
            TypeInner::Array { base, size, .. } => match size {
                ArraySize::Constant(n) => {
                    format!("array<{}, {}>", self.wgsl_name(*base), n.get())
                }
                _ => format!("array<{}>", self.wgsl_name(*base)),
            },
            TypeInner::Image {
                dim,
                arrayed,
                class,
            } => {
                let d = match dim {
                    ImageDimension::D1 => "1d",
                    ImageDimension::D2 => "2d",
                    ImageDimension::D3 => "3d",
                    ImageDimension::Cube => "cube",
                };
                let a = if *arrayed { "_array" } else { "" };
                match class {
                    ImageClass::Sampled { kind, multi } => format!(
                        "texture_{}{d}{a}<{}>",
                        if *multi { "multisampled_" } else { "" },
                        scalar_wgsl(Scalar {
                            kind: *kind,
                            width: 4
                        })
                    ),
                    ImageClass::Depth { multi } => format!(
                        "texture_depth_{}{d}{a}",
                        if *multi { "multisampled_" } else { "" }
                    ),
                    ImageClass::Storage { format, access } => format!(
                        "texture_storage_{d}{a}<{}, {}>",
                        format!("{format:?}").to_lowercase(),
                        match (
                            access.contains(StorageAccess::LOAD),
                            access.contains(StorageAccess::STORE)
                        ) {
                            (true, true) => "read_write",
                            (true, false) => "read",
                            _ => "write",
                        }
                    ),
                    ImageClass::External => "texture_external".into(),
                }
            }
            TypeInner::Sampler { comparison } => if *comparison {
                "sampler_comparison"
            } else {
                "sampler"
            }
            .into(),
            _ => "?".into(),
        }
    }
}

fn stage_name(stage: ShaderStage) -> Result<&'static str, String> {
    Ok(match stage {
        ShaderStage::Vertex => "vertex",
        ShaderStage::Fragment => "fragment",
        ShaderStage::Compute => "compute",
        other => return Err(format!("the {other:?} stage is not supported")),
    })
}

fn view_dimension(dim: ImageDimension, arrayed: bool) -> Result<&'static str, String> {
    Ok(match (dim, arrayed) {
        (ImageDimension::D1, false) => "D1",
        (ImageDimension::D2, false) => "D2",
        (ImageDimension::D2, true) => "D2Array",
        (ImageDimension::D3, false) => "D3",
        (ImageDimension::Cube, false) => "Cube",
        (ImageDimension::Cube, true) => "CubeArray",
        (d, true) => return Err(format!("an arrayed {d:?} texture is not a WebGPU view")),
    })
}

/// A matrix column's stride: columns are aligned like vectors (`vec3` to 16).
fn column_stride(rows: VectorSize, width: u32) -> u32 {
    let align = match rows {
        VectorSize::Bi => 2,
        VectorSize::Tri | VectorSize::Quad => 4,
    };
    align * width
}

fn scalar_rust(s: Scalar) -> Result<&'static str, String> {
    Ok(match (s.kind, s.width) {
        (ScalarKind::Float, 4) => "f32",
        (ScalarKind::Sint, 4) => "i32",
        (ScalarKind::Uint, 4) => "u32",
        (ScalarKind::Float, 8) => "f64",
        (ScalarKind::Sint, 8) => "i64",
        (ScalarKind::Uint, 8) => "u64",
        _ => return Err(format!("`{}` has no Rust type here", scalar_wgsl(s))),
    })
}

fn scalar_wgsl(s: Scalar) -> String {
    match s.kind {
        ScalarKind::Float => format!("f{}", u32::from(s.width) * 8),
        ScalarKind::Sint => format!("i{}", u32::from(s.width) * 8),
        ScalarKind::Uint => format!("u{}", u32::from(s.width) * 8),
        ScalarKind::Bool => "bool".into(),
        ScalarKind::AbstractInt => "abstract-int".into(),
        ScalarKind::AbstractFloat => "abstract-float".into(),
    }
}

/// A vertex input's `VertexFormat` and byte size: 32-bit scalars and vectors.
fn vertex_format(inner: &TypeInner) -> Result<(String, u32), String> {
    let (scalar, n) = match inner {
        TypeInner::Scalar(s) => (*s, 1),
        TypeInner::Vector { size, scalar } => (*scalar, *size as u32),
        _ => return Err("only scalars and vectors can be vertex inputs".into()),
    };
    let base = match (scalar.kind, scalar.width) {
        (ScalarKind::Float, 4) => "Float32",
        (ScalarKind::Sint, 4) => "Sint32",
        (ScalarKind::Uint, 4) => "Uint32",
        _ => {
            return Err(format!(
                "`{}` vertex inputs are not supported (32-bit only)",
                scalar_wgsl(scalar)
            ))
        }
    };
    let name = if n == 1 {
        base.to_string()
    } else {
        format!("{base}x{n}")
    };
    Ok((name, 4 * n))
}

const KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl",
    "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "static", "struct", "super", "trait", "true", "try", "type", "typeof", "unsafe",
    "unsized", "use", "virtual", "where", "while", "yield",
];

fn is_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    matches!(chars.next(), Some(c) if c == '_' || c.is_ascii_alphabetic())
        && chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
        && !KEYWORDS.contains(&s)
        && !matches!(s, "self" | "Self" | "crate" | "super")
}

/// A field name as Rust: raw when it is a keyword.
fn ident(name: &str) -> Result<String, String> {
    if matches!(name, "self" | "Self" | "crate" | "super") || name.is_empty() {
        return Err(format!("`{name}` cannot be a Rust field"));
    }
    if KEYWORDS.contains(&name) {
        return Ok(format!("r#{name}"));
    }
    if !is_identifier(name) {
        return Err(format!("`{name}` is not a Rust identifier"));
    }
    Ok(name.to_string())
}

/// `childrenSampler` / `children_sampler` → `CHILDREN_SAMPLER`.
fn upper_snake(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::new();
    for (i, c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase()
            && i > 0
            && (chars[i - 1].is_ascii_lowercase() || chars[i - 1].is_ascii_digit())
        {
            out.push('_');
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

/// `vs_main` → `VsMain`.
fn upper_camel(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
