// The real-GitHub lane of the T3 Code clone: its paths, the environment a lane T3 server runs
// in, the lane's `gh` and `git`, and the server's RPC. User decision 2026-10-07: pull request
// features are verified against real GitHub through the real GitHub CLI that the T3 server
// spawns, signed in by the user into lane-only config dirs (README.md).
//
// No script here reads, prints or stores a token. `gh` keeps each account's token in its own
// lane config dir (`gh auth login --insecure-storage`); the wrappers refuse to run without one,
// so the machine's `~/.config/gh` and keyring are never consulted.
import { spawnSync } from "node:child_process";
import { appendFileSync, chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

export const checkout = resolve(import.meta.dir, "../../../..");
export const example = join(checkout, "examples/t3-code");
export const ACCOUNTS = ["primary", "second"];
/** Lane servers take ports from this range (never 3773). */
export const PORTS = { primary: 16520, second: 16521 };

/**
 * `T3_GITHUB_LANE_SHARED` holds what every checkout reuses: the two config dirs the user signed
 * in to (`gh`, `gh-second`) and `sandbox.json` (the sandbox, the logins, the seeded numbers).
 * `T3_GITHUB_LANE` holds this checkout's own servers, homes, clones and logs.
 */
export function lanePaths(env = process.env) {
  const lane = resolve(env.T3_GITHUB_LANE || join(checkout, "target/github-lane"));
  const shared = resolve(env.T3_GITHUB_LANE_SHARED || join(checkout, "target/t3-ui-parity/github-lane"));
  return {
    lane, shared,
    configs: { primary: join(shared, "gh"), second: join(shared, "gh-second") },
    sandboxFile: join(shared, "sandbox.json"),
    bins: { primary: join(lane, "bin/primary"), second: join(lane, "bin/second") },
    homes: { primary: join(lane, "home/primary"), second: join(lane, "home/second") },
    logs: join(lane, "logs"), ghLog: join(lane, "logs/gh-calls.tsv"),
    work: join(lane, "work"), servers: join(lane, "servers"), runtime: join(lane, "runtime"),
  };
}

export const ghPath = (paths, account) => join(paths.bins[account], "gh");
export const serverDir = (paths, account) => join(paths.servers, account);

/** The real GitHub CLI, as found on this machine's PATH (or `T3_GITHUB_LANE_GH`). */
export function realGh(env = process.env) {
  const found = env.T3_GITHUB_LANE_GH || Bun.which("gh");
  if (!found) throw new Error("no gh on PATH: install the GitHub CLI or set T3_GITHUB_LANE_GH");
  return found;
}

/**
 * The lane's `gh`: the real CLI on the account's lane config dir. Each call is logged first
 * (time, cwd, config dir, whether a token came from the environment, argv cut to 1,500
 * characters; never stdin or output), then refused unless that dir holds the account's own token
 * (`oauth_token:` in hosts.yml, which `--insecure-storage` writes), so a missing login can never
 * fall through to the machine's keyring.
 */
export function ghWrapper({ real, config, log }) {
  const q = (value) => `'${value.replaceAll("'", "'\\''")}'`;
  return `#!/bin/sh
# Generated by examples/t3-code/tools/github-lane/lane.mjs: the real GitHub CLI on a lane config dir.
export GH_CONFIG_DIR=${q(config)}
printf '%s\\t%s\\t%s\\t%s\\t%s\\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$PWD" "$GH_CONFIG_DIR" "\${GH_TOKEN:+env-token}" "$(printf '%s ' "$@" | tr '\\n\\t' '  ' | cut -c1-1500)" >> ${q(log)}
if ! grep -q 'oauth_token:' "$GH_CONFIG_DIR/hosts.yml" 2>/dev/null; then
  echo "lane gh: $GH_CONFIG_DIR has no token of its own; sign in with --insecure-storage (examples/t3-code/tools/github-lane/README.md)" >&2
  exit 4
fi
exec ${q(real)} "$@"
`;
}

/** The isolated home's login profile: the T3 server rebuilds PATH from \`zsh -ilc\`, so the lane gh goes first here. */
export const zprofile = ({ bin, config }) =>
  `# Generated by examples/t3-code/tools/github-lane/lane.mjs.\nexport PATH="${bin}:$PATH"\nexport GH_CONFIG_DIR="${config}"\n`;

/** Git in the isolated home: no system or keychain helper, the account's lane gh for github.com. */
export const gitconfig = ({ account, gh }) => `# Generated by examples/t3-code/tools/github-lane/lane.mjs.
[user]
\tname = T3 lane ${account}
\temail = ${account}@t3-lane.invalid
[credential]
\thelper =
[credential "https://github.com"]
\thelper = !'${gh}' auth git-credential
[init]
\tdefaultBranch = main
[advice]
\tdetachedHead = false
`;

/** Writes the homes, wrappers and directories; returns the paths. Idempotent. */
export function setup(paths = lanePaths(), env = process.env) {
  const real = realGh(env);
  for (const dir of [paths.logs, paths.work, paths.servers, paths.runtime, paths.shared]) mkdirSync(dir, { recursive: true });
  for (const account of ACCOUNTS) {
    mkdirSync(paths.bins[account], { recursive: true });
    mkdirSync(paths.homes[account], { recursive: true });
    mkdirSync(paths.configs[account], { recursive: true, mode: 0o700 });
    writeFileSync(ghPath(paths, account), ghWrapper({ real, config: paths.configs[account], log: paths.ghLog }));
    chmodSync(ghPath(paths, account), 0o755);
    writeFileSync(join(paths.homes[account], ".zprofile"), zprofile({ bin: paths.bins[account], config: paths.configs[account] }));
    writeFileSync(join(paths.homes[account], ".gitconfig"), gitconfig({ account, gh: ghPath(paths, account) }));
    const s = serverDir(paths, account);
    for (const dir of ["t3home", "codex", "claude", "xdg/config", "xdg/data", "xdg/cache", "xdg/state", "tmp", "repos"]) mkdirSync(join(s, dir), { recursive: true });
  }
  return paths;
}

/** Whether the account's lane config dir holds its own token, without reading the token. */
export function signedIn(paths, account) {
  const hosts = join(paths.configs[account], "hosts.yml");
  return existsSync(hosts) && /^\s*oauth_token:/m.test(readFileSync(hosts, "utf8"));
}

/**
 * The environment of a lane T3 server, built from nothing: none of this shell's tokens,
 * config or home reach it. GH_CONFIG_DIR is set here and again by the wrapper and the profile.
 */
export function serverEnv(paths, account, base = process.env) {
  const s = serverDir(paths, account);
  return {
    PATH: [paths.bins[account], "/usr/bin", "/bin", "/usr/sbin", "/sbin"].join(":"),
    HOME: paths.homes[account], SHELL: "/bin/zsh", USER: base.USER ?? "", LOGNAME: base.LOGNAME ?? base.USER ?? "",
    LANG: base.LANG ?? "en_US.UTF-8", TMPDIR: join(s, "tmp"),
    CODEX_HOME: join(s, "codex"), CLAUDE_CONFIG_DIR: join(s, "claude"),
    XDG_CONFIG_HOME: join(s, "xdg/config"), XDG_DATA_HOME: join(s, "xdg/data"), XDG_CACHE_HOME: join(s, "xdg/cache"), XDG_STATE_HOME: join(s, "xdg/state"),
    T3CODE_HOME: join(s, "t3home"), T3CODE_TELEMETRY_ENABLED: "false",
    GH_CONFIG_DIR: paths.configs[account], GH_NO_UPDATE_NOTIFIER: "1", GIT_CONFIG_NOSYSTEM: "1", GIT_TERMINAL_PROMPT: "0",
  };
}

/** The environment the seed and probe run `gh` and `git` in: the account's lane home, nothing else. */
export function toolEnv(paths, account, base = process.env) {
  return {
    PATH: [paths.bins[account], "/usr/bin", "/bin", "/usr/sbin", "/sbin"].join(":"),
    HOME: paths.homes[account], USER: base.USER ?? "", LANG: base.LANG ?? "en_US.UTF-8",
    TMPDIR: join(serverDir(paths, account), "tmp"), GH_CONFIG_DIR: paths.configs[account],
    GH_NO_UPDATE_NOTIFIER: "1", GH_PROMPT_DISABLED: "1", GIT_CONFIG_NOSYSTEM: "1", GIT_TERMINAL_PROMPT: "0", NO_COLOR: "1",
  };
}

/** Runs a command; returns { status, stdout, stderr }. Throws with stderr unless `allowFail`. */
export function run(command, args, { env, cwd, input, allowFail = false } = {}) {
  const result = spawnSync(command, args, { env, cwd, input, encoding: "utf8", maxBuffer: 256 << 20 });
  if (result.error) throw result.error;
  const out = { status: result.status ?? 1, stdout: result.stdout ?? "", stderr: result.stderr ?? "" };
  if (out.status !== 0 && !allowFail) throw new Error(`${command.split("/").at(-1)} ${args.join(" ").slice(0, 300)}: exit ${out.status}: ${out.stderr.trim().slice(0, 800)}`);
  return out;
}

/** The account's lane gh. `json: true` parses stdout. */
export function gh(paths, account, args, options = {}) {
  const result = run(ghPath(paths, account), args, { env: toolEnv(paths, account), ...options });
  if (options.json) return result.status === 0 && result.stdout.trim() ? JSON.parse(result.stdout) : null;
  return result;
}

/** `gh api` with a status: { status, body } where status is the HTTP code (0 when gh failed before a response). */
export function api(paths, account, args, { input, allowFail = true } = {}) {
  const result = run(ghPath(paths, account), ["api", "-i", ...args], { env: toolEnv(paths, account), input, allowFail: true });
  const split = result.stdout.indexOf("\r\n\r\n") >= 0 ? result.stdout.indexOf("\r\n\r\n") : result.stdout.indexOf("\n\n");
  const head = split >= 0 ? result.stdout.slice(0, split) : "";
  const status = Number(/^HTTP\/\S+ (\d+)/.exec(head)?.[1] ?? 0);
  const text = split >= 0 ? result.stdout.slice(split).trim() : result.stdout.trim();
  let body = null;
  try { body = text ? JSON.parse(text) : null; } catch { body = text; }
  if (!allowFail && (status < 200 || status >= 300)) throw new Error(`gh api ${args.join(" ").slice(0, 200)}: HTTP ${status}: ${JSON.stringify(body)?.slice(0, 600)} ${result.stderr.trim().slice(0, 300)}`);
  return { status, body, stderr: result.stderr };
}

/** git with the account's lane home (its credential helper is that account's lane gh). */
export function git(paths, account, args, options = {}) {
  return run("/usr/bin/git", args, { env: { ...toolEnv(paths, account), ...(options.env ?? {}) }, cwd: options.cwd, input: options.input, allowFail: options.allowFail });
}

export function readSandbox(paths) {
  return existsSync(paths.sandboxFile) ? JSON.parse(readFileSync(paths.sandboxFile, "utf8")) : null;
}
export function writeSandbox(paths, value) { writeFileSync(paths.sandboxFile, `${JSON.stringify(value, null, 2)}\n`); }

/** Lines the lane gh wrappers logged since `offset` (bytes), parsed. */
export function ghCallsSince(paths, offset) {
  if (!existsSync(paths.ghLog)) return [];
  return readFileSync(paths.ghLog, "utf8").slice(offset).split("\n").filter(Boolean).map((line) => {
    const [at, cwd, config, tokenFrom, argv] = line.split("\t");
    return { at, cwd, config, tokenFromEnv: tokenFrom === "env-token", argv: (argv ?? "").trim() };
  });
}
export const ghLogSize = (paths) => (existsSync(paths.ghLog) ? readFileSync(paths.ghLog).length : 0);
export const note = (paths, line) => appendFileSync(join(paths.logs, "lane.log"), `${new Date().toISOString()} ${line}\n`);

/**
 * A lane T3 server's RPC over its WebSocket, after exchanging a pairing token for an access
 * token (the pairing flow the clone uses). `request` resolves the Exit value or rejects with the
 * typed failure; `stream` collects chunks until `until` says stop, then interrupts.
 */
export async function connect(origin, pairingToken, scopes = "orchestration:read orchestration:operate review:write terminal:operate") {
  const form = new URLSearchParams({ grant_type: "urn:ietf:params:oauth:grant-type:token-exchange", subject_token: pairingToken,
    subject_token_type: "urn:t3:params:oauth:token-type:environment-bootstrap", requested_token_type: "urn:ietf:params:oauth:token-type:access_token",
    scope: scopes, client_label: "GitHub lane probe", client_device_type: "desktop", client_os: "macos" });
  const access = (await (await fetch(`${origin}/oauth/token`, { method: "POST", body: form })).json()).access_token;
  if (!access) throw new Error("pairing failed: the server did not issue an access token");
  const auth = { authorization: `Bearer ${access}` };
  const ticket = (await (await fetch(`${origin}/api/auth/websocket-ticket`, { method: "POST", headers: auth })).json()).ticket;
  const ws = new WebSocket(`${origin.replace("http", "ws")}/ws?${new URLSearchParams({ wsTicket: ticket, orchestrationProtocol: "2", clientSurface: "desktop", clientOs: "macos", clientDeviceType: "desktop" })}`);
  await new Promise((done, fail) => { ws.onopen = done; ws.onerror = () => fail(new Error("socket failed")); });
  const pending = new Map();
  ws.onmessage = (event) => {
    for (const frame of [JSON.parse(event.data)].flat()) {
      if (frame._tag === "Ping") { ws.send(JSON.stringify({ _tag: "Pong" })); continue; }
      const entry = pending.get(String(frame.requestId));
      if (!entry) continue;
      if (frame._tag === "Chunk") { ws.send(JSON.stringify({ _tag: "Ack", requestId: frame.requestId })); entry.chunk?.(frame.values ?? []); continue; }
      if (frame._tag === "Exit") {
        pending.delete(String(frame.requestId));
        if (frame.exit?._tag === "Success") entry.resolve(frame.exit.value);
        else entry.reject(Object.assign(new Error(failureMessage(frame.exit)), { failure: frame.exit }));
      }
    }
  };
  const send = (tag, payload, entry, timeoutMs) => {
    const id = crypto.randomUUID();
    pending.set(id, entry);
    ws.send(JSON.stringify({ _tag: "Request", id, tag, payload, headers: [["x-t3-orchestration-protocol", "2"]] }));
    const timer = setTimeout(() => { if (pending.delete(id)) entry.reject(new Error(`timeout after ${timeoutMs} ms: ${tag}`)); }, timeoutMs);
    timer.unref?.();
    return id;
  };
  return {
    origin, auth,
    request: (tag, payload = {}, timeoutMs = 120_000) => new Promise((resolve, reject) => send(tag, payload, { resolve, reject }, timeoutMs)),
    stream: (tag, payload, until, timeoutMs = 30_000) => new Promise((resolve, reject) => {
      const values = [];
      let id = "";
      const entry = { resolve: () => resolve(values), reject, chunk: (chunk) => {
        values.push(...chunk);
        if (until(values)) { pending.delete(id); ws.send(JSON.stringify({ _tag: "Interrupt", requestId: id })); resolve(values); }
      } };
      id = send(tag, payload, entry, timeoutMs);
    }),
    http: async (path, body) => {
      const response = await fetch(`${origin}${path}`, { method: "POST", headers: { ...auth, "content-type": "application/json" }, body: JSON.stringify(body) });
      const text = await response.text();
      let value = text;
      try { value = JSON.parse(text); } catch {}
      if (!response.ok) throw Object.assign(new Error(`HTTP ${response.status}: ${typeof value === "string" ? value.slice(0, 400) : failureMessage(value)}`), { failure: value });
      return value;
    },
    close: () => ws.close(),
  };
}

/**
 * The server's project for `workspaceRoot`, created when missing. `scripts` (ProjectScript[])
 * replaces the project's scripts when given, e.g. a worktree setup script for hand-off checks.
 */
export async function ensureProject(conn, workspaceRoot, { title = "GitHub sandbox", scripts } = {}) {
  const response = await fetch(`${conn.origin}/api/projects`, { headers: conn.auth });
  const snapshot = await response.json();
  let project = (snapshot.projects ?? []).find((entry) => entry.workspaceRoot === workspaceRoot && !entry.deletedAt);
  if (!project) {
    const projectId = crypto.randomUUID();
    await conn.request("projects.mutate", { type: "project.create", commandId: crypto.randomUUID(), projectId, title, workspaceRoot, createWorkspaceRootIfMissing: false, defaultModelSelection: null, ...(scripts ? { scripts } : {}) });
    project = { id: projectId, workspaceRoot };
  } else if (scripts) {
    await conn.request("projects.mutate", { type: "project.update", commandId: crypto.randomUUID(), projectId: project.id, scripts });
  }
  return project.id;
}

/** The first typed failure's tag and message (T3Protocol.swift `failure`, in brief). */
export function failureMessage(value) {
  const seen = new Set();
  const walk = (node) => {
    if (!node || typeof node !== "object" || seen.has(node)) return null;
    seen.add(node);
    if (Array.isArray(node)) { for (const item of node) { const found = walk(item); if (found) return found; } return null; }
    if (node._tag === "Fail" && node.error) return describe(node.error);
    if (node._tag === "Die" && node.defect) return describe(node.defect);
    for (const key of ["exit", "cause", "error", "defect"]) { const found = walk(node[key]); if (found) return found; }
    return node.message || node._tag ? describe(node) : null;
  };
  const describe = (error) => typeof error === "object" && error
    ? [error._tag ?? error.name, error.reason, error.message ?? error.detail].filter(Boolean).join(": ")
    : String(error);
  return walk(value) ?? "the request failed";
}
