import Lake
open Lake DSL System

/-- Aeneas's checkout (`AENEAS_DIR`, else `~/tools/aeneas`): its Lean library
and the packages (mathlib) it already built are used in place. -/
def aeneasDir : FilePath := run_io do
  match ← IO.getEnv "AENEAS_DIR" with
  | some d => return d
  | none => return FilePath.mk ((← IO.getEnv "HOME").getD "") / "tools" / "aeneas"

package «vm-extract» where
  packagesDir := aeneasDir / "backends" / "lean" / ".lake" / "packages"

require aeneas from aeneasDir / "backends" / "lean"

/-- The semantics' VM model, `semantics/Contract`, compiled here at Aeneas's
Lean version. -/
lean_lib Contract where
  srcDir := "../.."
  globs := #[.submodules `Contract]

/-- The extraction (`Types`, `Funs`: generated by `../check.sh`) and its proofs. -/
@[default_target]
lean_lib VmExtract where
  globs := #[.andSubmodules `VmExtract]
