[package]
name = "exact-game-bake"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
exact-game = { path = "../engine" }
gltf = { version = "1.4.1", features = ["import", "KHR_materials_emissive_strength", "KHR_texture_transform", "extensions", "extras"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
serde_json = "1"
sha2 = "0.10"
