//! The art pass's scenery (`art="pass"`): models generated by `artgen/` and
//! baked from `art/`, put on the entities the greybox spawns, plus the parts
//! only the art pass has. Its rules keep the game itself unchanged:
//!
//! - every simulated entity is spawned in the same order with the same pose;
//!   the art pass only swaps what it draws (`Mesh`, `Material`);
//! - nothing here draws from the world's random stream: scenery rolls its own
//!   `Rng` from the seed, so every later gameplay draw is the greybox's;
//! - entities only the art pass has (survivor bodies, legs, undergrowth, the
//!   beam, more fire) are spawned by `finish`, after every simulated entity;
//! - what moves without the simulation (walk cycles, facing, wind, fading
//!   crowns, carried logs on the backpack) is presentation, in `look.rs`.
use crate::forest::{frustum, height, Grove, CELL};
use crate::player::Child;
use exact_game::asset::{MaterialData, MeshBuilder, MeshData, Model, Node};
use exact_game::*;
use std::f32::consts::{FRAC_PI_2, PI, TAU};

/// One drawn part of a character. `swing` zero is a body that turns to face the
/// way its `owner` goes; otherwise a limb swinging `swing` radians about its
/// pivot at `phase`, as fast as its owner walks. Read only by `look::present`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Component)]
pub struct Part {
    pub owner: Entity,
    pub swing: f32,
    pub phase: f32,
}

/// The tree models and the share of the forest each takes, with its far level.
const KINDS: [(&str, f32); 5] = [
    ("pine_a", 0.42),
    ("pine_b", 0.26),
    ("pine_c", 0.08),
    ("oak", 0.14),
    ("birch", 0.10),
];
/// Undergrowth models with their shares and scale ranges.
const UNDER: [(&str, f32, f32, f32); 5] = [
    ("fern.model", 0.32, 0.8, 1.4),
    ("bush.model", 0.2, 0.7, 1.3),
    ("grass.model", 0.26, 0.8, 1.5),
    ("rock_a.model", 0.1, 0.6, 1.6),
    ("rock_b.model", 0.12, 0.6, 1.4),
];
/// Camera distances: a tree's generated far level, where trees stop drawing
/// (the camera sees under 70 m; sun shadows reach 60 m), where undergrowth stops.
const FAR: f32 = 45.0;
const TREES_HIDE: f32 = 150.0;
const UNDER_HIDE: f32 = 60.0;
/// Undergrowth only where the player can walk to in a night.
const UNDER_REACH: f32 = 160.0;

/// A scenery roll: uniform in [0, 1) from the seed, a salt and an index, never
/// the world's stream.
fn roll(seed: u64, salt: u64, i: u64) -> Rng {
    Rng::new(
        seed ^ salt.wrapping_mul(0x9E37_79B9_7F4A_7C15) ^ i.wrapping_mul(0xD1B5_4A32_D192_ED03),
    )
}
fn pick<T: Copy>(table: &[(T, f32)], mut r: f32) -> usize {
    for (k, &(_, share)) in table.iter().enumerate() {
        r -= share;
        if r <= 0.0 {
            return k;
        }
    }
    table.len() - 1
}

/// The generated terrain, textured: the forest floor tiles every 4 m and the
/// vertex colours lay moss, soil and leaf litter over it, worn earth round the fire.
pub fn terrain(w: &mut World, mut mesh: MeshData) -> Mesh {
    let at: Vec<[f32; 3]> = mesh
        .positions
        .chunks_exact(3)
        .map(|p| [p[0], p[1], p[2]])
        .collect();
    mesh.colors = at
        .iter()
        .flat_map(|&[x, y, z]| ground_color(x, y, z))
        .collect();
    mesh.uvs = at
        .iter()
        .flat_map(|&[x, _, z]| [x / 4.0, z / 4.0])
        .collect();
    mesh.material = 0;
    let model = Model {
        bounds: mesh.bounds,
        meshes: vec![mesh],
        materials: vec![MaterialData {
            metallic: 0.0,
            roughness: 0.95,
            base_color_texture: Some(0),
            ..Default::default()
        }],
        textures: vec!["forest_floor.tex".into()],
        nodes: vec![Node {
            mesh: Some(0),
            ..Default::default()
        }],
        ..Default::default()
    };
    w.generated_model("terrain-art.model", model)
        .expect("art terrain")
}

/// Floor tint over the texture: moss, bare soil and leaf litter in drifting
/// patches tens of metres across (the texture carries the detail; anything
/// finer would alias at the 2 m vertex spacing), worn earth around the fire.
/// Linear multipliers.
fn ground_color(x: f32, y: f32, z: f32) -> [f32; 4] {
    let n1 = math::sin(x * 0.11 + z * 0.07) * math::sin(x * 0.05 - z * 0.13 + 1.3);
    let n2 = math::sin(x * 0.23 + 2.0 * math::sin(z * 0.09)) * math::cos(z * 0.21 - x * 0.05);
    let moss = [0.34, 0.58, 0.25];
    let soil = [0.52, 0.43, 0.35];
    let litter = [0.78, 0.56, 0.35];
    let a = math::smoothstep(-0.4, 0.5, n1);
    let b = math::smoothstep(0.3, 0.9, n2) * 0.6;
    let r = (x * x + z * z).sqrt();
    let worn = 1.0 - math::smoothstep(3.0, 9.0, r);
    let lift = 1.0 + y * 0.05;
    let mut c = [0.0, 0.0, 0.0, 1.0];
    for k in 0..3 {
        let patch = (moss[k] * a + soil[k] * (1.0 - a)) * (1.0 - b) + litter[k] * b;
        c[k] = (patch * (1.0 - worn) + [0.5, 0.42, 0.36][k] * worn) * lift;
    }
    c
}

/// Each tree kind's baked model and generated far level.
pub struct TreeLooks {
    seed: u64,
    lods: Vec<(Mesh, ModelLod)>,
}
impl TreeLooks {
    /// The look of the tree in `cell`: a kind rolled from the cell, never drawn
    /// from the world's stream.
    pub fn of(&self, cell: u32) -> (Mesh, ModelLod) {
        let k = pick(&KINDS, roll(self.seed, 1, cell as u64).next_f32());
        self.lods[k].clone()
    }
}
pub fn tree_looks(w: &mut World) -> TreeLooks {
    let lods = KINDS
        .iter()
        .map(|&(name, _)| {
            let far = format!("{name}_far.model");
            w.generated(&far, far_tree(name)).expect("far tree");
            let lod = ModelLod {
                levels: vec![LodLevel {
                    distance: FAR,
                    model: far,
                }],
                hide: Some(TREES_HIDE),
            };
            (Mesh::asset(format!("{name}.model")), lod)
        })
        .collect();
    TreeLooks {
        seed: w.seed(),
        lods,
    }
}

/// A far tree: the baked one's silhouette in a few dozen flat-shaded triangles,
/// coloured like its textures at a distance.
fn far_tree(name: &str) -> MeshData {
    let mut m = MeshBuilder::flat();
    let bark = [0.05, 0.028, 0.014];
    match name {
        "oak" | "birch" => {
            let (h, canopy, leaf, wood) = if name == "oak" {
                (7.0, 2.6, [0.035, 0.08, 0.012], bark)
            } else {
                (7.6, 1.8, [0.1, 0.13, 0.025], [0.33, 0.31, 0.27])
            };
            frustum(&mut m, 6, 0.0, 0.3, h * 0.66, 0.1, wood);
            globe(
                &mut m,
                Vec3::new(0.0, h * 0.78, 0.0),
                Vec3::new(canopy, h * 0.2, canopy),
                leaf,
            );
            globe(
                &mut m,
                Vec3::new(canopy * 0.4, h * 0.88, -canopy * 0.2),
                Vec3::splat(canopy * 0.55),
                leaf,
            );
        }
        _ => {
            let (tiers, h, spread, droop, leaf, wood) = match name {
                "pine_a" => (4, 7.4, 2.2, 0.25, [0.016, 0.05, 0.017], bark),
                "pine_b" => (5, 8.8, 1.7, 0.35, [0.015, 0.038, 0.03], bark),
                _ => (
                    3,
                    6.0,
                    1.6,
                    0.5,
                    [0.045, 0.036, 0.017],
                    [0.03, 0.022, 0.015],
                ),
            };
            frustum(&mut m, 6, 0.0, 0.3, h * 0.6, 0.12, wood);
            for k in 0..tiers {
                let t = k as f32 / tiers as f32;
                let base = h * (0.18 + t * 0.7);
                let radius = spread * (1.0 - t * 0.78);
                let shade = 0.6 + 0.4 * t;
                let color = [leaf[0] * shade, leaf[1] * shade, leaf[2] * shade];
                frustum(
                    &mut m,
                    7,
                    base - droop * radius,
                    radius,
                    base + h * (0.42 - t * 0.12),
                    0.0,
                    color,
                );
            }
        }
    }
    m.finish()
}

/// Append a flat-shaded ellipsoid of 8 × 5 facets.
fn globe(m: &mut MeshBuilder, at: Vec3, radii: Vec3, color: [f32; 3]) {
    m.ellipsoid(at, radii, Quat::IDENTITY, (5, 8), |_| color);
}

/// The campfire's eighteen entities, where the greybox spawns its eighteen
/// (the flame, the embers, six logs and ten stones): glowing coals, embers,
/// four charred logs crossed in them, two seat logs and a ring of stones.
pub fn campfire(w: &mut World) {
    w.spawn_named(
        "flame",
        (
            Transform::at(0.0, 0.12, 0.0).with_scale(Vec3::new(1.0, 0.35, 1.0)),
            Mesh::sphere(0.42),
            Material {
                color: [1.0, 0.4, 0.1, 1.0],
                ..Material::glow([5.0, 1.2, 0.15])
            },
        ),
    );
    w.spawn_named(
        "embers",
        (
            Transform::at(0.0, 0.5, 0.0),
            Emitter {
                gravity: Vec3::new(0.0, 1.5, 0.0),
                speed: 1.6,
                spread: 0.45,
                size: [0.06, 0.0],
                color: [[1.0, 0.7, 0.2, 1.0], [1.0, 0.2, 0.0, 0.0]],
                bound: [-3.0, -1.0, -3.0, 3.0, 7.0, 3.0],
                ..Emitter::sparks().rate(30.0).lifetime(2.2).seed(9)
            },
        ),
    );
    for k in 0..4 {
        // The log stands along Y; lay it along X, tip it 0.35 rad, turn it about the fire.
        let a = k as f32 / 4.0 * TAU + 0.4;
        w.spawn((
            Transform {
                position: Vec3::new(0.0, 0.2, 0.0),
                rotation: Quat::from_rotation_y(a) * Quat::from_rotation_z(0.35 - FRAC_PI_2),
                scale: Vec3::splat(0.9),
            },
            Mesh::asset("firelog.model"),
        ));
    }
    for k in 0..2 {
        seat(w, k);
    }
    for k in 0..10 {
        let a = k as f32 / 10.0 * TAU;
        let (s, c) = math::sin_cos(a);
        w.spawn((
            Transform {
                position: Vec3::new(c * 1.2, 0.02, s * 1.2),
                rotation: Quat::from_rotation_y(a * 3.0),
                scale: Vec3::splat(0.38 + 0.06 * math::sin(a * 5.0)),
            },
            Mesh::asset("rock_b.model"),
        ));
    }
}
/// A seat log lying on the ground, tangent to a circle round the fire.
fn seat(w: &mut World, k: u32) {
    let a = k as f32 / 3.0 * TAU + 0.9;
    let (s, c) = math::sin_cos(a);
    w.spawn((
        Transform {
            position: Vec3::new(c * 3.4, 0.22, s * 3.4),
            rotation: Quat::from_rotation_y(-a + FRAC_PI_2) * Quat::from_rotation_z(-FRAC_PI_2),
            scale: Vec3::new(1.3, 1.5, 1.3),
        },
        Mesh::asset("log.model"),
    ));
}

/// The fire as fuel changes it: the coals' size and every layer's rate. Read
/// before writing: an unchanged emitter is not rewritten.
pub fn fire(w: &World, radius: f32) {
    let size = (radius / 14.0).clamp(0.15, 1.6);
    let coals = Vec3::new(1.0, 0.35, 1.0) * (0.6 + 0.4 * size);
    if w.require::<Transform>("flame").scale != coals {
        w.require_mut::<Transform>("flame").scale = coals;
    }
    for (name, rate) in [
        ("flame-core", 90.0),
        ("flame-outer", 60.0),
        ("smoke", 9.0),
        ("embers", 30.0),
    ] {
        let next = if radius > 0.0 { rate * size } else { 0.0 };
        if w.get::<Emitter>(name).is_some_and(|e| e.rate != next) {
            w.get_mut::<Emitter>(name).unwrap().rate = next;
        }
    }
}

/// Everything only the art pass draws, after every simulated entity: the
/// survivors, the creatures' legs, the beam, more fire, the undergrowth.
pub fn finish(w: &mut World) {
    let player = w.resolve("player").expect("player");
    let avatar = w.spawn_named(
        "avatar",
        (
            Parent(player),
            Transform::at(0.0, -0.9, 0.0),
            Mesh::asset("survivor_body.model"),
            Part {
                owner: player,
                ..Part::default()
            },
        ),
    );
    survivor_limbs(w, avatar, player, None);
    let children: Vec<Entity> = w.query::<&Child>().iter().map(|(e, _)| e).collect();
    for child in children {
        let tint = Material::rgb(0.45, 0.65, 1.0);
        let body = w.spawn((
            Parent(child),
            Transform::at(0.0, -0.6, 0.0).with_scale(0.62),
            Mesh::asset("survivor_body.model"),
            tint,
            Part {
                owner: child,
                ..Part::default()
            },
        ));
        survivor_limbs(w, body, child, Some(tint));
    }
    let deer = w.resolve("deer").expect("deer");
    legs(
        w,
        deer,
        "deer_leg.model",
        [0.18, 0.25, 0.12],
        [0.15, 0.02, -0.5],
        1.14,
        0.5,
    );
    let wolves: Vec<Entity> = w
        .query::<&crate::creatures::Wolf>()
        .iter()
        .map(|(e, _)| e)
        .collect();
    for wolf in wolves {
        legs(
            w,
            wolf,
            "wolf_leg.model",
            [0.12, 0.17, 0.3],
            [0.12, 0.15, -0.38],
            1.0,
            0.6,
        );
    }
    let flashlight = w.resolve("flashlight").expect("flashlight");
    w.spawn_named(
        "beam",
        (
            Parent(flashlight),
            Transform::default(),
            Mesh::asset("beam.model"),
        ),
    );
    seat(w, 2);
    flames(w);
    undergrowth(w);
}

/// Arms swing against the legs; all four hang from pivots on the survivor.
fn survivor_limbs(w: &mut World, body: Entity, owner: Entity, tint: Option<Material>) {
    for side in [-1.0f32, 1.0] {
        let phase = if side < 0.0 { 0.0 } else { PI };
        for (model, at, phase, swing) in [
            (
                "survivor_leg.model",
                Vec3::new(side * 0.1, 0.84, 0.0),
                phase,
                0.55,
            ),
            (
                "survivor_arm.model",
                Vec3::new(side * 0.25, 1.42, 0.0),
                phase + PI,
                0.45,
            ),
        ] {
            let part = w.spawn((
                Parent(body),
                Transform::at(at.x, at.y, at.z),
                Mesh::asset(model),
                Part {
                    owner,
                    swing,
                    phase,
                },
            ));
            if let Some(tint) = tint {
                w.insert(part, tint);
            }
        }
    }
}

/// A quadruped's legs at mirrored front and back hips: diagonal pairs together.
fn legs(
    w: &mut World,
    body: Entity,
    model: &str,
    front: [f32; 3],
    back: [f32; 3],
    reach: f32,
    swing: f32,
) {
    for (at, phase, stretch) in [
        (Vec3::new(front[0], front[1], front[2]), 0.0, reach),
        (Vec3::new(-front[0], front[1], front[2]), PI, reach),
        (Vec3::new(back[0], back[1], back[2]), PI, 1.0),
        (Vec3::new(-back[0], back[1], back[2]), 0.0, 1.0),
    ] {
        w.spawn((
            Parent(body),
            Transform::at(at.x, at.y, at.z).with_scale(Vec3::new(1.0, stretch, 1.0)),
            Mesh::asset(model),
            Part {
                owner: body,
                swing,
                phase,
            },
        ));
    }
}

/// Two additive flame layers over the coals and a straight-alpha smoke column
/// that drifts with the wind; `fire` keeps their rates with the fuel.
fn flames(w: &mut World) {
    let layer = |rate, life, size: [f32; 2], speed, color, seed| Emitter {
        shape: emitter::Shape::Sphere(0.32),
        gravity: Vec3::new(0.0, 2.6, 0.0),
        speed,
        spread: 0.3,
        drag: 0.6,
        size,
        color,
        ease: emitter::Ease::Smooth,
        bound: [-2.0, -0.5, -2.0, 2.0, 4.0, 2.0],
        ..Emitter::sparks().rate(rate).lifetime(life).seed(seed)
    };
    w.spawn_named(
        "flame-core",
        (
            Transform::at(0.0, 0.25, 0.0),
            layer(
                90.0,
                0.45,
                [0.42, 0.08],
                0.9,
                [[1.0, 0.85, 0.45, 1.0], [1.0, 0.35, 0.05, 0.0]],
                11,
            ),
        ),
    );
    w.spawn_named(
        "flame-outer",
        (
            Transform::at(0.0, 0.3, 0.0),
            layer(
                60.0,
                0.75,
                [0.7, 0.15],
                0.7,
                [[1.0, 0.45, 0.08, 0.9], [0.6, 0.08, 0.02, 0.0]],
                12,
            ),
        ),
    );
    w.spawn_named(
        "smoke",
        (
            Transform::at(0.0, 1.1, 0.0),
            Emitter {
                shape: emitter::Shape::Sphere(0.2),
                gravity: Vec3::new(0.25, 0.9, 0.05),
                speed: 0.5,
                spread: 0.4,
                drag: 0.35,
                size: [0.5, 2.6],
                color: [[0.07, 0.065, 0.06, 0.45], [0.05, 0.05, 0.05, 0.0]],
                ease: emitter::Ease::Smooth,
                additive: false,
                bound: [-6.0, -1.0, -6.0, 6.0, 12.0, 6.0],
                ..Emitter::sparks().rate(9.0).lifetime(5.0).seed(13)
            },
        ),
    );
}

/// About half the cells within reach of camp carry a fern, bush, tuft or rock,
/// kept off the trunks; `Ambient`, and hidden past `UNDER_HIDE` by the GPU cull.
fn undergrowth(w: &mut World) {
    let seed = w.seed();
    let props: Vec<(Transform, &str)> = {
        let g = w.resource::<Grove>();
        let n = g.side * g.side;
        (0..n)
            .filter_map(|c| {
                let (i, j) = ((c % g.side) as f32, (c / g.side) as f32);
                let (cx, cz) = (-g.half + (i + 0.5) * CELL, -g.half + (j + 0.5) * CELL);
                let r = (cx * cx + cz * cz).sqrt();
                let edge = g.half - CELL;
                let mut rng = roll(seed, 2, c as u64);
                if !(7.0..UNDER_REACH).contains(&r)
                    || cx.abs() > edge
                    || cz.abs() > edge
                    || !rng.chance(0.5)
                {
                    return None;
                }
                let x = cx + rng.range(-2.2..2.2);
                let z = cz + rng.range(-2.2..2.2);
                let kind = UNDER[pick(&UNDER.map(|u| (u.0, u.1)), rng.next_f32())];
                let s = rng.range(kind.2..kind.3);
                let turn = rng.range(0.0..TAU);
                let (x, z) = g.resolve(x, z, 0.7);
                Some((
                    Transform {
                        position: Vec3::new(x, height(x, z) - 0.03, z),
                        rotation: Quat::from_rotation_y(turn),
                        scale: Vec3::splat(s),
                    },
                    kind.0,
                ))
            })
            .collect()
    };
    for (pose, model) in props {
        w.spawn((
            pose,
            Mesh::asset(model),
            Ambient,
            ModelLod {
                levels: Vec::new(),
                hide: Some(UNDER_HIDE),
            },
        ));
    }
}
